Repository iterative/dvc, pull requests merged in 2019-06, with the labels that each got.

#2075 dvc: path info refactoring
  dvc/command/diff.py
  dvc/command/version.py
  dvc/dependency/http.py
  dvc/exceptions.py
  dvc/output/base.py
  dvc/output/hdfs.py
  dvc/output/local.py
  dvc/output/s3.py
  dvc/output/ssh.py
  dvc/path/__init__.py
  dvc/path/azure.py
  dvc/path/base.py
  dvc/path/gs.py
  dvc/path/hdfs.py
  dvc/path/http.py
  dvc/path/https.py
  dvc/path/local.py
  dvc/path/oss.py
  dvc/path/s3.py
  dvc/path/ssh.py
  dvc/path_info.py
  dvc/remote/azure.py
  dvc/remote/base.py
  dvc/remote/gs.py
  dvc/remote/hdfs.py
  dvc/remote/http.py
  dvc/remote/local/__init__.py
  dvc/remote/oss.py
  dvc/remote/s3.py
  dvc/remote/ssh/__init__.py
  dvc/repo/__init__.py
  dvc/repo/checkout.py
  dvc/repo/metrics/show.py
  dvc/repo/move.py
  dvc/repo/pkg/install.py
  dvc/scm/git/temp_git_repo.py
  dvc/stage.py
  dvc/state.py
  dvc/utils/__init__.py
  dvc/utils/collections.py
  dvc/utils/compat.py
  setup.py
  tests/func/remote/test_local.py
  tests/func/test_api.py
  tests/func/test_cache.py
  tests/func/test_data_cloud.py
  tests/func/test_dependency.py
  tests/func/test_diff.py
  tests/func/test_remote.py
  tests/func/test_repo.py
  tests/func/test_repro.py
  tests/func/test_run.py
  tests/func/test_s3.py
  tests/func/test_state.py
  tests/unit/remote/ssh/test_ssh.py
  tests/unit/remote/test_azure.py
  tests/unit/remote/test_base.py
  tests/unit/remote/test_gs.py
  tests/unit/remote/test_oss.py
  tests/unit/test_stage.py
Labels: c13-half-a-week, refactoring

#2124 system: handle PurePath
  dvc/ignore.py
  dvc/state.py
  dvc/system.py
  dvc/utils/__init__.py
  dvc/utils/fs.py
  tests/func/test_state.py
  tests/func/test_system.py
Labels: bug, p0-critical

#2012 Initial pkg implementation
  .dvc/.gitignore
  dvc/command/pkg.py
  dvc/dependency/__init__.py
  dvc/dependency/pkg.py
  dvc/output/base.py
  dvc/pkg.py
  dvc/remote/local/__init__.py
  dvc/repo/__init__.py
  dvc/repo/imp.py
  dvc/repo/pkg/__init__.py
  dvc/repo/pkg/install.py
  dvc/scm/git/temp_git_repo.py
  dvc/scm/git/tree.py
  dvc/stage.py
  dvc/utils/compat.py
  setup.py
  tests/basic_env.py
  tests/conftest.py
  tests/func/test_data_cloud.py
  tests/func/test_pkg.py
  tests/unit/command/test_pkg.py
  tests/unit/remote/test_local.py
Labels: c13-half-a-week

#2156 http: enable progress bar
  dvc/remote/http.py
Labels: bug, c1-quick-fix, p0-critical

#2131 ssh: increase jobs and parallelize batch_exists
  dvc/logger.py
  dvc/main.py
  dvc/remote/ssh/__init__.py
  dvc/remote/ssh/connection.py
  dvc/utils/compat.py
Labels: c8-full-day, p1-important, performance

#2112 dvc: "DVC-file" term revision, `targets` argument help update, other small changes
  dvc/command/add.py
  dvc/command/checkout.py
  dvc/command/commit.py
  dvc/command/data_sync.py
  dvc/command/diff.py
  dvc/command/lock.py
  dvc/command/pipeline.py
  dvc/command/remote.py
  dvc/command/remove.py
  dvc/command/repro.py
  dvc/command/unprotect.py
  dvc/exceptions.py
  dvc/repo/add.py
  dvc/repo/metrics/show.py
  dvc/repo/move.py
  dvc/stage.py
  scripts/completion/dvc.zsh
  tests/func/test_add.py
  tests/func/test_repro.py
  tests/func/test_stage.py
Labels: refactoring
