Repository iterative/dvc, pull requests merged in 2019-12, with the labels that each got.

#2778 Snap
  .travis.yml
  README.rst
  dvc/updater.py
  scripts/build_package.sh
  snap/snapcraft.yaml
Labels: awaiting response, build, enhancement, feature request, p3-nice-to-have, research

#2875 Stream progress
  dvc/remote/gdrive.py
  dvc/remote/gdrive/utils.py
  dvc/remote/gs.py
  setup.py
Labels: enhancement, refactoring, ui

#2857 lengthen bars unless nested/threaded
  dvc/progress.py
Labels: c1-quick-fix, discussion, enhancement, ui

#2883 much grammar such fix
  README.rst
Labels: c3-small-fix, discussion, enhancement, ui

#2906 add: test: convert to dir helpers 2
  tests/func/test_add.py
Labels: refactoring, testing

#2826 analytics: refactor into a module
  dvc/analytics.py
  dvc/command/daemon.py
  dvc/config.py
  dvc/main.py
  dvc/repo/init.py
  tests/func/test_analytics.py
  tests/unit/test_analytics.py
Labels: c21-full-week, enhancement, refactoring

#2926 test: move: convert to dir helpers
  tests/func/test_move.py
Labels: refactoring, testing

#2939 snap: remove plugs (incompatible with classic)
  snap/snapcraft.yaml
Labels: bug

#2932 commit: test: refactor to dir helpers
  tests/func/test_commit.py
Labels: refactoring, testing

#2934 checkout: test: refactor to dir helpers
  tests/func/test_checkout.py
Labels: refactoring, testing

#2938 test: a couple of dir helpers fixes
  tests/dir_helpers.py
Labels: refactoring, testing

#2935 import: test: refactor to dir helpers
  tests/func/test_import.py
Labels: refactoring, testing

#2952 tests: use dir helpers on updater
  tests/func/test_updater.py
  tests/unit/test_updater.py
Labels: refactoring, testing

#2950 tests: use dir_helpers on repo
  tests/func/test_destroy.py
  tests/func/test_repo.py
  tests/unit/test_repo.py
Labels: refactoring, testing

#2986 dvc: use ' to mark dynamic command output, et al.
  dvc/analytics.py
  dvc/command/remove.py
  dvc/config.py
  dvc/remote/base.py
  dvc/remote/oss.py
  dvc/repo/add.py
  dvc/repo/gc.py
  dvc/stage.py
  dvc/updater.py
  dvc/utils/__init__.py
  tests/func/test_add.py
Labels: question
