Repository iterative/dvc, pull requests merged in 2019-10, with the labels that each got.

#2610 get/import/url: handle existing output directory
  dvc/repo/get.py
  dvc/repo/get_url.py
  dvc/repo/imp_url.py
  dvc/utils/__init__.py
  scripts/ci/before_install.sh
  tests/func/test_get.py
  tests/func/test_get_url.py
  tests/func/test_import.py
  tests/func/test_import_url.py
Labels: p0-critical

#2627 fix ncols_desc=0
  dvc/progress.py
Labels: bug, p0-critical

#2550 isatty
  dvc/analytics.py
  dvc/progress.py
  dvc/updater.py
  dvc/utils/__init__.py
  tests/__main__.py
  tests/conftest.py
  tests/func/test_data_cloud.py
  tests/unit/test_progress.py
Labels: enhancement, ui

#2656 output: base: don't forget to return empty cache
  dvc/exceptions.py
  dvc/output/base.py
  tests/func/test_gc.py
Labels: p0-critical

#2660 ssh credential prompt before progress
  dvc/remote/ssh/__init__.py
Labels: enhancement, p1-important, ui

#2546 add: output improvements
  dvc/command/add.py
  dvc/command/base.py
  dvc/exceptions.py
  dvc/logger.py
  dvc/remote/base.py
  dvc/repo/add.py
  dvc/stage.py
  tests/unit/test_logger.py
Labels: enhancement, research, ui
