Repository iterative/dvc, pull requests merged in 2019-11, with the labels that each got.

#2735 system: win: use win32file for _getdirinfo
  dvc/system.py
  setup.py
Labels: p0-critical

#2748 system: use logging instead of dvc.logger
  dvc/system.py
Labels: p0-critical

#2767 non-blocking intermediate progress IO
  dvc/progress.py
  setup.py
Labels: enhancement, performance, research, ui

#2817 use SI prefixes for progress
  dvc/progress.py
Labels: c1-quick-fix, discussion, enhancement, feature request, p3-nice-to-have, ui

#2809 GS progress for push & pull
  dvc/remote/gs.py
  tests/unit/remote/test_gs.py
Labels: enhancement, p3-nice-to-have, refactoring, research, ui
