Repository iterative/dvc, pull requests merged in 2020-02, with the labels that each got.

#3292 analytics: ignore request.post errors
  dvc/analytics.py
  tests/unit/test_analytics.py
Labels: p0-critical

#2975 add: auto convert absolute_path => relative
  dvc/output/local.py
  tests/func/test_add.py
  tests/unit/output/test_local.py
Labels: p2-medium, ui

#3295 repo: raise exception if root_dir is not a directory path
  dvc/exceptions.py
  dvc/repo/__init__.py
Labels: enhancement

#3301 repro: fix bug in _get_active_graph
  dvc/repo/reproduce.py
  tests/unit/repo/test_repo.py
  tests/unit/repo/test_reproduce.py
Labels: p0-critical

#3307 black: bump version 19.3b0 -> 19.10b0
  .pre-commit-config.yaml
  .restyled.yaml
  setup.py
  tests/func/remote/test_local.py
  tests/func/test_add.py
  tests/func/test_commit.py
  tests/func/test_gc.py
  tests/func/test_stage.py
  tests/func/test_status.py
  tests/func/test_update.py
  tests/unit/repo/test_repo.py
  tests/unit/repo/test_reproduce.py
Labels: refactoring

#3298 dvc: refactor config
  dvc/analytics.py
  dvc/cache.py
  dvc/command/add.py
  dvc/command/base.py
  dvc/command/cache.py
  dvc/command/config.py
  dvc/command/remote.py
  dvc/config.py
  dvc/data_cloud.py
  dvc/external_repo.py
  dvc/remote/__init__.py
  dvc/remote/azure.py
  dvc/remote/base.py
  dvc/remote/config.py
  dvc/remote/gdrive.py
  dvc/remote/gs.py
  dvc/remote/hdfs.py
  dvc/remote/http.py
  dvc/remote/local.py
  dvc/remote/oss.py
  dvc/remote/s3.py
  dvc/remote/slow_link_detection.py
  dvc/remote/ssh/__init__.py
  dvc/repo/__init__.py
  dvc/repo/init.py
  dvc/repo/reproduce.py
  dvc/state.py
  tests/dir_helpers.py
  tests/func/test_add.py
  tests/func/test_api.py
  tests/func/test_cache.py
  tests/func/test_config.py
  tests/func/test_data_cloud.py
  tests/func/test_get.py
  tests/func/test_import.py
  tests/func/test_install.py
  tests/func/test_remote.py
  tests/func/test_repo.py
  tests/func/test_repro.py
  tests/func/test_state.py
  tests/remotes.py
  tests/unit/remote/test_remote.py
  tests/unit/remote/test_slow_link_detection.py
  tests/unit/test_analytics.py
  tests/unit/test_config.py
Labels: p1-important, refactoring

#3326 checkout: change loglevel to debug and simplifymessage
  dvc/remote/base.py
Labels: enhancement

#3327 tests: fix typo on gdrive_client_secret
  tests/func/test_data_cloud.py
Labels: p0-critical, testing

#3330 snap: test: add build and deploy checks
  .travis.yml
  snap/snapcraft.yaml
Labels: build, research, testing

#3316 ui: make progress bars respect `--quiet`
  dvc/progress.py
  dvc/repo/add.py
  tests/unit/test_progress.py
Labels: bug, enhancement, refactoring, research, ui

#3350 external_repo: fix bug in path resolution
  dvc/external_repo.py
  tests/func/test_external_repo.py
Labels: p0-critical

#3335 ui: fix missing progress & tidy
  dvc/remote/gdrive.py
  dvc/remote/gs.py
Labels: discussion, enhancement, refactoring, research, ui

#3360 Fix bash completion
  scripts/completion/dvc.bash
Labels: bug, completion, enhancement, ui

#3367 completion: bash: allow multi-arg completion, minor tidy
  scripts/completion/dvc.bash
Labels: bug, completion, enhancement, ui

#3368 test: repro: prevent dvc.stages resetting
  tests/func/test_repro.py
Labels: p0-critical, testing

#3373 metadata: add Zenodo, tidy badges and keywords
  .zenodo.json
  README.rst
  setup.py
Labels: discussion, enhancement, research

#3374 completion: bash: properly recurse targets
  scripts/completion/dvc.bash
Labels: bug, completion, enhancement, refactoring, research, ui

#3413 pull: fetch: external: respect `--jobs`
  dvc/repo/fetch.py
Labels: bug, performance, ui

#3380 docs: update badges
  README.rst
Labels: enhancement
