Repository iterative/dvc, pull requests merged in 2020-08, with the labels that each got.

#4320 experiments: more intelligent checkout behavior
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
Labels: experiments

#4329 tests: fix regex
  tests/func/test_version.py
Labels: c1-quick-fix, testing

#4345 experiments: add --no-pager option for `dvc exp show`
  dvc/command/experiments.py
Labels: experiments

#4337 completion: bump shtab
  setup.py
Labels: bug, c1-quick-fix, completion, ui

#4331 experiments: support `dvc repro --exp` command line params
  dvc/command/repro.py
  dvc/exceptions.py
  dvc/repo/experiments/__init__.py
  dvc/repo/reproduce.py
  dvc/utils/toml.py
  tests/unit/command/test_repro.py
Labels: experiments

#4375 experiments: add options to include/exclude columns in `exp show`
  dvc/command/experiments.py
Labels: experiments

#4396 tests: add .dvcignore on the tests expectations
  tests/unit/repo/test_repo_tree.py
Labels: c1-quick-fix, testing

#4403 update flake8 to latest version
  .pre-commit-config.yaml
  dvc/repo/plots/data.py
  setup.py
  tests/remotes/__init__.py
Labels: c1-quick-fix

#4405 cleanup RepoTree
  dvc/repo/ls.py
  dvc/repo/tree.py
Labels: refactoring

#4399 upgrade to isort5
  .pre-commit-config.yaml
  .restyled.yaml
  dvc/command/daemon.py
  dvc/command/dag.py
  dvc/command/experiments.py
  dvc/command/init.py
  dvc/command/metrics.py
  dvc/config.py
  dvc/daemon.py
  dvc/repo/__init__.py
  dvc/repo/experiments/__init__.py
  dvc/repo/gc.py
  dvc/repo/get.py
  dvc/repo/graph.py
  dvc/repo/move.py
  dvc/repo/plots/__init__.py
  dvc/repo/plots/data.py
  dvc/repo/reproduce.py
  dvc/repo/run.py
  dvc/repo/tree.py
  dvc/scm/git.py
  dvc/stage/cache.py
  dvc/stage/decorators.py
  dvc/stage/utils.py
  dvc/system.py
  dvc/tree/azure.py
  dvc/tree/gs.py
  dvc/updater.py
  dvc/utils/__init__.py
  setup.cfg
  tests/__init__.py
  tests/func/test_add.py
  tests/func/test_ls.py
  tests/func/test_repro_multistage.py
  tests/func/test_run_multistage.py
  tests/remotes/azure.py
  tests/remotes/hdfs.py
  tests/unit/scm/test_git.py
  tests/utils/httpd.py
Labels: refactoring

#4389 experiments: include experiment timestamps in `dvc exp show` output
  dvc/command/experiments.py
  dvc/repo/experiments/show.py
  tests/func/experiments/test_show.py
Labels: experiments

#4411 refactor: move toml/yaml serialization to dvc.utils.serialize
  dvc/dvcfile.py
  dvc/repo/experiments/__init__.py
  dvc/stage/cache.py
  dvc/stage/serialize.py
  dvc/utils/serialize/__init__.py
  dvc/utils/serialize/_toml.py
  dvc/utils/serialize/_yaml.py
  tests/func/test_add.py
  tests/func/test_checkout.py
  tests/func/test_commit.py
  tests/func/test_data_cloud.py
  tests/func/test_dvcfile.py
  tests/func/test_lockfile.py
  tests/func/test_move.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_run_multistage.py
  tests/func/test_run_single_stage.py
  tests/func/test_stage.py
  tests/unit/dependency/test_params.py
  tests/unit/test_dvcfile.py
Labels: refactoring

#4414 experiments: fix flaky tests
  dvc/repo/experiments/__init__.py
  tests/func/experiments/test_show.py
Labels: experiments

#4422 git: handle rev_parse exception
  dvc/scm/git.py
Labels: bug, experiments

#4402 experiments: abstract executor output collection using trees
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
Labels: experiments

#4427 dvc: move Dvc/RepoTree to dvc/tree
  dvc/dependency/repo.py
  dvc/external_repo.py
  dvc/repo/__init__.py
  dvc/repo/experiments/executor.py
  dvc/repo/ls.py
  dvc/repo/metrics/show.py
  dvc/repo/plots/__init__.py
  dvc/tree/dvc.py
  dvc/tree/repo.py
  tests/func/test_tree.py
  tests/unit/tree/__init__.py
  tests/unit/tree/test_dvc.py
  tests/unit/tree/test_repo.py
Labels: refactoring

#4452 experiments: support binary and untracked files in experiment patches
  dvc/repo/experiments/__init__.py
Labels: bug, experiments

#4450 experiments: fix bug where wrong git branch checked-out before pull
  dvc/repo/experiments/__init__.py
  tests/func/experiments/test_experiments.py
Labels: bug, experiments

#4462 experiments: only show queued experiments for the current commit
  dvc/repo/experiments/show.py
  tests/func/experiments/test_show.py
Labels: bug, experiments

#4474 changelog: categorize changelog entry using labels
  .github/release-drafter.yml
Labels: chore, maintenance

#4459 diff: Add sort logic to sort diff ouput irrespective of output format…
  dvc/command/diff.py
  tests/unit/command/test_diff.py
Labels: enhancement

#4472 tests: install hook just before using it
  tests/func/test_install.py
Labels: skip-changelog

#4471 tests: speedup lock tests
  tests/func/test_lock.py
Labels: skip-changelog, testing

#4480 s3: provide more helpful messages on common errors
  dvc/config.py
  dvc/exceptions.py
  dvc/main.py
  dvc/tree/s3.py
  dvc/utils/__init__.py
  tests/func/test_s3.py
  tests/unit/remote/test_remote_tree.py
  tests/unit/tree/test_s3.py
Labels: enhancement, ui

#4488 plots: add `dvc plots -e/--experiment` option
  dvc/command/plots.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/show.py
  dvc/repo/plots/__init__.py
  dvc/repo/plots/diff.py
  tests/func/experiments/test_experiments.py
  tests/unit/command/test_plots.py
  tests/unit/repo/plots/test_diff.py
Labels: enhancement, experiments

#4486 external: avoid unnecessary hash computation
  dvc/cache/local.py
  dvc/data_cloud.py
  dvc/tree/dvc.py
  dvc/tree/repo.py
  tests/unit/tree/test_dvc.py
  tests/unit/tree/test_repo.py
Labels: bug

#4489 experiments: make `dvc exp show` more consistent w/viewer
  dvc/command/experiments.py
  dvc/repo/experiments/show.py
  tests/func/experiments/test_show.py
  tests/unit/command/test_experiments.py
Labels: enhancement, experiments, ui

#4490 Keep `status` output format consistents
  dvc/repo/status.py
  dvc/stage/__init__.py
  tests/func/test_status.py
Labels: enhancement, ui

#4503 experiments: support column ordering & sorting in `dvc exp show`
  dvc/command/experiments.py
Labels: enhancement, experiments, ui

#4502 deps/outs: get rid of self.info
  dvc/cache/base.py
  dvc/dependency/param.py
  dvc/dependency/repo.py
  dvc/external_repo.py
  dvc/hash_info.py
  dvc/output/base.py
  dvc/stage/loader.py
  dvc/stage/serialize.py
  dvc/tree/base.py
  tests/func/test_add.py
  tests/func/test_run_cache.py
  tests/func/test_tree.py
  tests/unit/dependency/test_params.py
  tests/unit/output/test_load.py
  tests/unit/stage/test_loader_pipeline_file.py
  tests/unit/stage/test_serialize_pipeline_lock.py
Labels: refactoring
