Repository iterative/dvc, pull requests merged in 2020-01, with the labels that each got.

#3063 Snap classic deployment
  .travis.yml
  README.rst
Labels: build

#3064 fix snap deploy stage
  .travis.yml
Labels: build

#3123 test: refactor ssh related functions in test helper classes
  tests/func/test_data_cloud.py
  tests/func/test_repro.py
  tests/remotes.py
  tests/unit/remote/ssh/test_ssh.py
Labels: refactoring

#3128 test: move hdfs and gcp functions into helper classes
  tests/func/test_data_cloud.py
  tests/func/test_repro.py
  tests/remotes.py
Labels: refactoring

#3134 test: merge local related function in Local helper class
  tests/func/test_data_cloud.py
  tests/func/test_remote.py
  tests/remotes.py
Labels: refactoring

#3136 test: use helper remotes in TestCases
  tests/func/test_data_cloud.py
  tests/remotes.py
Labels: refactoring

#3148 test: use helper remotes in child classes of TestDataCloudCLIBase
  tests/func/test_data_cloud.py
Labels: refactoring, testing

#3149 test: use helper remotes in external repro
  tests/func/test_repro.py
Labels: refactoring, testing

#3158 major deploy tidy
  .travis.yml
  scripts/ci/deploy_condition.sh
Labels: build, refactoring, testing

#3142 conftest: remove dvc_repo, erepo, git, git_erepo
  tests/conftest.py
  tests/func/test_get.py
Labels: p1-important, refactoring, testing

#2956 add snap tests
  .travis.yml
  scripts/build_package.sh
  scripts/build_posix.sh
  scripts/build_snap.sh
  scripts/ci/before_install.sh
  snap/snapcraft.yaml
Labels: build, research, testing, ui

#3199 py2: remove use of `six`
  dvc/repo/add.py
Labels: refactoring

#3205 exception: fix spelling
  dvc/exceptions.py
Labels: c1-quick-fix

#3209 fix snap stable & edge release errors
  .travis.yml
  scripts/ci/before_install.sh
  snap/snapcraft.yaml
Labels: build, research

#3211 brancher: do not get tree if there's no revs
  dvc/repo/brancher.py
Labels: bug

#3212 another attempt at travis dpl snap
  .travis.yml
  scripts/ci/before_install.sh
Labels: build, research

#3223 hooks: checkout: fix incorrect dvc repo detection
  dvc/scm/git/__init__.py
Labels: bug

#3088 dvc: add sanity checks for hard/symlinks
  dvc/command/version.py
  dvc/remote/base.py
  dvc/remote/local.py
  tests/func/test_version.py
Labels: enhancement

#2846 UI progress cleanup
  dvc/cli.py
  dvc/output/base.py
  dvc/progress.py
  dvc/remote/base.py
  dvc/repo/__init__.py
  dvc/repo/add.py
  dvc/repo/get_url.py
Labels: discussion, enhancement, feature request, performance, refactoring, research, ui

#3263 lint:beautysh pre-commit hook
  .pre-commit-config.yaml
  scripts/build_package.sh
  scripts/build_posix.sh
  scripts/build_snap.sh
  scripts/ci/before_install.sh
  scripts/ci/check_patch.sh
  scripts/ci/check_python.sh
  scripts/ci/deploy_condition.sh
  scripts/ci/install.sh
  scripts/ci/install_azurite.sh
  scripts/ci/install_hadoop.sh
  scripts/ci/install_oss.sh
  scripts/ci/retry.sh
  scripts/ci/script.sh
  scripts/completion/dvc.bash
  scripts/completion/dvc.zsh
  scripts/pypi_upload.sh
Labels: refactoring, testing
