Repository iterative/dvc, pull requests merged in 2020-07, with the labels that each got.

#4148 completion: update dependency
  dvc/command/add.py
  dvc/command/cache.py
  dvc/command/checkout.py
  dvc/command/commit.py
  dvc/command/completion.py
  dvc/command/daemon.py
  dvc/command/data_sync.py
  dvc/command/freeze.py
  dvc/command/get.py
  dvc/command/get_url.py
  dvc/command/imp.py
  dvc/command/imp_url.py
  dvc/command/ls/__init__.py
  dvc/command/metrics.py
  dvc/command/move.py
  dvc/command/plots.py
  dvc/command/remove.py
  dvc/command/repro.py
  dvc/command/unprotect.py
  dvc/command/update.py
  setup.py
Labels: completion, ui

#4149 s3,gs: don't append "/" to prefixed path when listing objects
  dvc/remote/azure.py
  dvc/remote/base.py
  dvc/remote/gdrive.py
  dvc/remote/gs.py
  dvc/remote/oss.py
  dvc/remote/s3.py
  tests/unit/remote/test_base.py
Labels: bug

#4157 gdrive: pop prefix kwarg
  dvc/remote/gdrive.py
Labels: c1-quick-fix, p0-critical

#4170 snap: deprecate v0
  scripts/ci/before_install.sh
Labels: build, c1-quick-fix, ci

#4185 params: fix skipping of params dvc.lock when it's a falsy value
  dvc/dependency/param.py
  tests/func/test_run_multistage.py
  tests/unit/dependency/test_params.py
Labels: bug

#4208 deps/outs: get rid of remotes in favor of trees
  dvc/dependency/__init__.py
  dvc/dependency/repo.py
  dvc/output/__init__.py
  dvc/output/base.py
  dvc/output/local.py
  dvc/output/ssh.py
  dvc/repo/tree.py
  tests/func/test_tree.py
  tests/unit/dependency/test_local.py
  tests/unit/output/test_local.py
Labels: refactoring

#4222 snap: deploy: fix major channels not being pushed
  .travis.yml
  scripts/ci/before_install.sh
Labels: bug, build, c1-quick-fix, research

#4290 experiments: temporarily disable styling in `show` table
  dvc/command/experiments.py
Labels: experiments

#4300 Exclude pylint==6.0
  setup.py
Labels: build

#4257 experiments: support local parallel execution in temp directories
  dvc/command/experiments.py
  dvc/command/repro.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
  dvc/repo/experiments/show.py
  dvc/repo/reproduce.py
  tests/func/experiments/test_show.py
  tests/unit/command/test_repro.py
Labels: experiments

#4304 dvc: fix --quiet mode
  dvc/main.py
  tests/func/test_status.py
Labels: p1-important

#4308 Update pytest to >=6.0.1
  setup.py
Labels: build
