Repository iterative/dvc, pull requests merged in 2020-06, with the labels that each got.

#3922 bugfix: rerun stage when command is changed
  dvc/stage/run.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
Labels: c1-quick-fix

#3923 refactor: rename utils.stage to utils.yaml
  dvc/dvcfile.py
  dvc/exceptions.py
  dvc/serialize.py
  dvc/stage/cache.py
  dvc/utils/yaml.py
  tests/func/test_add.py
  tests/func/test_checkout.py
  tests/func/test_commit.py
  tests/func/test_data_cloud.py
  tests/func/test_dvcfile.py
  tests/func/test_lockfile.py
  tests/func/test_move.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_run_single_stage.py
  tests/func/test_stage.py
Labels: refactoring

#3953 tests: move mock-ssh-server git dependency
  scripts/ci/install.sh
  setup.py
Labels: bug, build, c1-quick-fix, p0-critical

#3949 refactor/test multistage load for params and outputs
  dvc/dependency/__init__.py
  dvc/dependency/param.py
  dvc/output/__init__.py
  dvc/repo/run.py
  dvc/stage/loader.py
  tests/unit/dependency/test_params.py
  tests/unit/output/test_load.py
  tests/unit/test_run.py
Labels: enhancement, testing

#3878 snap: restrict site-package checks
  snap/snapcraft.yaml
Labels: bug, build, c1-quick-fix, p0-critical, research

#3979 issue template: do not auto-add labels on new issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#3976 tests: StageLoader for Pipeline file stages
  dvc/stage/loader.py
  dvc/stage/utils.py
  tests/unit/stage/test_loader_pipeline_file.py
  tests/unit/stage/test_utils.py
Labels: refactoring, testing

#3978 log: show modifying if entry already exists in dvcfile
  dvc/dvcfile.py
Labels: bug, c1-quick-fix

#3986 tests: update mock ssh server
  scripts/ci/install.sh
  setup.py
Labels: testing

#3987 remove unnecessary dependencies
  setup.py
Labels: enhancement

#3983 plots: fix help message
  dvc/command/plots.py
Labels: enhancement, ui

#3985 tests: serialize pipeline file
  dvc/dependency/__init__.py
  dvc/dvcfile.py
  dvc/stage/cache.py
  dvc/stage/serialize.py
  dvc/stage/utils.py
  tests/func/test_lockfile.py
  tests/func/test_repro_multistage.py
  tests/unit/stage/test_loader_pipeline_file.py
  tests/unit/stage/test_serialize_pipeline_file.py
Labels: refactoring, testing

#3988 tests serializing of stage to lockfile
  dvc/stage/serialize.py
  setup.cfg
  tests/unit/stage/test_serialize_pipeline_lock.py
  tests/unit/stage/test_stage.py
Labels: testing

#3993 stage: don't consider stage as cached if checksum/cmd changed
  dvc/stage/__init__.py
  dvc/stage/imports.py
  dvc/stage/run.py
Labels: enhancement, refactoring

#3990 snap: build fixes
  .travis.yml
  scripts/build_snap.sh
  scripts/ci/before_install.sh
Labels: bug, build, ci, p0-critical

#4000 config/remote/cache: make --system/--global/--local mutually exclusive
  dvc/command/config.py
Labels: bug, enhancement, p3-nice-to-have, ui

#4008 dvc.yaml: preserve meta
  dvc/dvcfile.py
  tests/func/test_dvcfile.py
Labels: bug, c1-quick-fix

#4018 tests: cover run cache with functional tests
  dvc/repo/fetch.py
  dvc/repo/push.py
  dvc/repo/reproduce.py
  dvc/stage/cache.py
  tests/func/test_run_cache.py
Labels: run-cache

#4032 tests: unittests for dvcfile and some small fixes
  tests/func/test_dvcfile.py
  tests/unit/test_dvcfile.py
Labels: testing

#4028 schema: provide a jsonschema for dvc.yaml
  scripts/schema/dvc-yaml.json
Labels: enhancement

#4036 fix error message on dag.py
  dvc/command/dag.py
Labels: bug

#3999 snap: v0: build fixes & updates
  .travis.yml
  dvc/updater.py
  scripts/build_snap.sh
  scripts/ci/before_install.sh
  scripts/remove_update_warning.patch
Labels: bug, build, ci, p1-important

#4037 CI: fix Mac builds
  scripts/ci/before_install.sh
Labels: c1-quick-fix, testing

#4038 snap: make future major version upgrades easier
  .travis.yml
  scripts/ci/before_install.sh
Labels: build, ci, discussion, testing

#3916 gdrive: add open
  dvc/exceptions.py
  dvc/remote/gdrive.py
  dvc/utils/http.py
  dvc/utils/stream.py
  setup.py
  tests/func/test_api.py
  tests/remotes.py
Labels: enhancement, refactoring, research, ui

#4051 remote: rename "checksum" -> "hash"
  dvc/api.py
  dvc/data_cloud.py
  dvc/dependency/repo.py
  dvc/output/base.py
  dvc/remote/azure.py
  dvc/remote/base.py
  dvc/remote/gdrive.py
  dvc/remote/gs.py
  dvc/remote/hdfs.py
  dvc/remote/http.py
  dvc/remote/index.py
  dvc/remote/local.py
  dvc/remote/s3.py
  dvc/remote/ssh/__init__.py
  dvc/repo/diff.py
  dvc/repo/tree.py
  tests/func/remote/test_index.py
  tests/func/test_add.py
  tests/func/test_cache.py
  tests/func/test_checkout.py
  tests/func/test_data_cloud.py
  tests/func/test_gc.py
  tests/func/test_remote.py
  tests/func/test_tree.py
  tests/unit/remote/test_azure.py
  tests/unit/remote/test_base.py
  tests/unit/remote/test_index.py
  tests/unit/remote/test_local.py
  tests/unit/remote/test_remote.py
Labels: refactoring

#4052 optimize: remove `fsync` when dumping rwlock data
  dvc/rwlock.py
  tests/func/test_repro_multistage.py
Labels: performance

#4053 cache relpath on stage
  dvc/stage/__init__.py
  tests/func/test_stage.py
Labels: enhancement, performance

#4067 Add flake8 extensions
  .pre-commit-config.yaml
  dvc/command/diff.py
  dvc/dagascii.py
  dvc/remote/ssh/connection.py
  dvc/repo/__init__.py
  dvc/repo/plots/data.py
  dvc/repo/tree.py
  dvc/scm/git/__init__.py
  dvc/scm/tree.py
  dvc/stage/serialize.py
  setup.cfg
  setup.py
  tests/func/test_dvcfile.py
  tests/func/test_gc.py
Labels: enhancement

#3921 completion: autogenerate
  .github/PULL_REQUEST_TEMPLATE.md
  dvc/cli.py
  dvc/command/add.py
  dvc/command/cache.py
  dvc/command/checkout.py
  dvc/command/commit.py
  dvc/command/completion.py
  dvc/command/daemon.py
  dvc/command/data_sync.py
  dvc/command/freeze.py
  dvc/command/get.py
  dvc/command/get_url.py
  dvc/command/imp.py
  dvc/command/imp_url.py
  dvc/command/ls/__init__.py
  dvc/command/metrics.py
  dvc/command/move.py
  dvc/command/plots.py
  dvc/command/remove.py
  dvc/command/repro.py
  dvc/command/unprotect.py
  dvc/command/update.py
  scripts/build_posix.sh
  scripts/completion/dvc.bash
  scripts/completion/dvc.zsh
  setup.cfg
  setup.py
  snap/snapcraft.yaml
Labels: ci, completion, enhancement, refactoring, research, testing, ui

#4076 completion: misc fixes
  dvc/command/add.py
  dvc/command/cache.py
  dvc/command/checkout.py
  dvc/command/commit.py
  dvc/command/daemon.py
  dvc/command/data_sync.py
  dvc/command/freeze.py
  dvc/command/get.py
  dvc/command/get_url.py
  dvc/command/imp.py
  dvc/command/imp_url.py
  dvc/command/ls/__init__.py
  dvc/command/metrics.py
  dvc/command/move.py
  dvc/command/plots.py
  dvc/command/remove.py
  dvc/command/repro.py
  dvc/command/unprotect.py
  dvc/command/update.py
  setup.py
Labels: bug, completion, enhancement, p0-critical, ui

#4089 tests: use pytest-lazyfixture
  tests/func/test_data_cloud.py
  tests/func/test_get.py
Labels: enhancement, testing

#4098 rpm/deb/osxpkg: add url and license
  scripts/build_posix.sh
Labels: build, enhancement

#4119 pylint: enable attribute-outside-init check
  .pylintrc
  dvc/updater.py
  tests/basic_env.py
  tests/dir_helpers.py
  tests/func/test_add.py
  tests/func/test_repro.py
  tests/remotes/local.py
  tests/remotes/ssh.py
  tests/unit/test_updater.py
  tests/unit/utils/test_collections.py
Labels: enhancement, refactoring

#4128 hdfs: implement makedirs separately
  dvc/remote/hdfs.py
Labels: refactoring

#4130 metrics: skip missing metrics silently
  dvc/repo/metrics/show.py
  tests/func/metrics/test_show.py
Labels: bug, p0-critical

#4122 pylint: enable additional checks
  .pylintrc
  dvc/api.py
  dvc/cache.py
  dvc/cli.py
  dvc/command/git_hook.py
  dvc/dvcfile.py
  dvc/external_repo.py
  dvc/lock.py
  dvc/logger.py
  dvc/main.py
  dvc/output/base.py
  dvc/path_info.py
  dvc/remote/base.py
  dvc/remote/gs.py
  dvc/remote/local.py
  dvc/remote/ssh/connection.py
  dvc/repo/__init__.py
  dvc/repo/add.py
  dvc/repo/gc.py
  dvc/repo/plots/data.py
  dvc/repo/plots/template.py
  dvc/repo/pull.py
  dvc/repo/tree.py
  dvc/scm/git/__init__.py
  dvc/scm/git/tree.py
  dvc/stage/decorators.py
  dvc/stage/loader.py
  dvc/stage/run.py
  dvc/stage/serialize.py
  dvc/state.py
  dvc/system.py
  dvc/utils/fs.py
  fastentrypoints.py
  setup.cfg
  setup.py
  tests/func/test_api.py
  tests/func/test_checkout.py
  tests/func/test_data_cloud.py
  tests/func/test_dvcfile.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_state.py
  tests/func/test_tree.py
  tests/pylint_plugin_disable.py
  tests/remotes/http.py
  tests/remotes/ssh.py
  tests/unit/output/test_local.py
  tests/unit/remote/test_base.py
  tests/unit/remote/test_slow_link_detection.py
  tests/unit/stage/test_stage.py
Labels: enhancement
