Repository iterative/dvc, pull requests merged in 2020-03, with the labels that each got.

#3464 deps: upgrade jsonpath_ng to latest version
  setup.py
Labels: bug

#3467 completion: bash: misc fixes and updates
  scripts/completion/dvc.bash
Labels: bug, completion, enhancement, research, ui

#3480 tests: remove use of mocker as context-manager
  tests/func/test_ls.py
  tests/unit/command/test_imp_url.py
  tests/unit/test_logger.py
  tests/unit/utils/test_utils.py
Labels: testing

#3401 checkout: show summary by default and introduce --show-changes flag
  dvc/command/checkout.py
  dvc/command/data_sync.py
  dvc/exceptions.py
  dvc/external_repo.py
  dvc/remote/base.py
  dvc/repo/checkout.py
  dvc/repo/pull.py
  dvc/stage.py
  dvc/state.py
  tests/func/test_checkout.py
  tests/func/test_state.py
  tests/unit/command/test_checkout.py
Labels: completion

#3463 dvc: support Python3.8
  .travis.yml
  dvc/system.py
  scripts/ci/before_install.sh
  scripts/ci/install_hadoop.sh
  setup.py
  tests/func/test_checkout.py
Labels: build

#3491 completion: add --summary flag on checkout
  scripts/completion/dvc.bash
  scripts/completion/dvc.zsh
Labels: completion

#3493 gc: do not work without specifier when using -c flag
  dvc/command/gc.py
  dvc/repo/gc.py
  tests/func/test_data_cloud.py
  tests/func/test_gc.py
Labels: bug

#3495 template: pr update
  .github/PULL_REQUEST_TEMPLATE.md
Labels: completion

#3432 import-url: allow queries in URL
  dvc/path_info.py
  dvc/remote/http.py
  tests/unit/test_path_info.py
Labels: bug, enhancement, p1-important

#3508 version: fix bug when .git dir is removed, show more info regarding repo
  dvc/command/version.py
  tests/func/test_version.py
Labels: bug

#3509 import: fix output message on not-existing output directory
  dvc/stage.py
Labels: bug

#3512 external_repo: do not try too hard to fix upstream
  dvc/external_repo.py
  tests/func/test_import.py
Labels: bug

#3503 pull: support pulling git-only imports
  dvc/remote/base.py
  dvc/repo/fetch.py
  tests/func/test_data_cloud.py
Labels: bug, enhancement

#3520 pull/checkout: fix empty log output if no state gets changed
  dvc/command/checkout.py
  tests/unit/command/test_checkout.py
Labels: bug

#3529 metrics: diff: handle deleted/new metric
  dvc/repo/metrics/diff.py
  tests/func/test_metrics.py
  tests/unit/command/test_metrics.py
Labels: p0-critical

#3531 params: use dpath for xpaths
  dvc/dependency/param.py
  setup.py
  tests/unit/dependency/test_params.py
Labels: bug, p0-critical

#3535 metrics: diff: fix bug with unchanged raw metrics
  dvc/repo/metrics/diff.py
  tests/func/test_metrics.py
Labels: bug, p0-critical

#3524 s3/gs: do not try to make directory on top level path
  dvc/remote/gs.py
  dvc/remote/s3.py
  tests/func/test_s3.py
  tests/unit/remote/test_remote.py
Labels: bug

#3522 progress: wrappers
  dvc/progress.py
  dvc/remote/base.py
  dvc/remote/http.py
  dvc/utils/fs.py
Labels: bug, refactoring, research, ui

#3532 remote: use progress bar when paginating
  dvc/remote/azure.py
  dvc/remote/base.py
  dvc/remote/gdrive.py
  dvc/remote/gs.py
  dvc/remote/hdfs.py
  dvc/remote/local.py
  dvc/remote/oss.py
  dvc/remote/s3.py
  dvc/remote/ssh/__init__.py
  tests/unit/remote/test_base.py
Labels: enhancement, ui

#3547 deploy: snap: timeout after 10 min
  .travis.yml
Labels: build, research, testing

#3500 progress: limit maximum running bars
  setup.py
Labels: bug, p1-important, research, ui

#3551 snap: deploy: fix authentication
  .travis.yml
Labels: bug, build, c1-quick-fix, testing
