Repository iterative/dvc, pull requests merged in 2020-09, with the labels that each got.

#4506 dvc: use HashInfo to interact with cache
  dvc/api.py
  dvc/cache/base.py
  dvc/cache/local.py
  dvc/external_repo.py
  dvc/hash_info.py
  dvc/output/base.py
  dvc/repo/diff.py
  dvc/stage/cache.py
  dvc/tree/base.py
  dvc/tree/dvc.py
  tests/func/remote/test_index.py
  tests/func/test_add.py
  tests/func/test_cache.py
  tests/func/test_checkout.py
  tests/func/test_data_cloud.py
  tests/func/test_gc.py
  tests/func/test_remote.py
  tests/func/test_repro.py
  tests/func/test_run_single_stage.py
  tests/func/test_tree.py
  tests/unit/output/test_local.py
  tests/unit/output/test_output.py
  tests/unit/stage/test_loader_pipeline_file.py
Labels: refactoring

#4505 tree.repo: fix race condition when walking subrepos
  dvc/tree/repo.py
  tests/unit/tree/test_repo.py
Labels: bugfix

#4481 lock: retry when trying to acquire lock
  dvc/lock.py
Labels: enhancement

#4515 experiments: suppress repro --params option by default
  dvc/command/repro.py
Labels: bugfix, experiments

#4465 support subrepos for get/list/api/import/ls
  dvc/api.py
  dvc/data_cloud.py
  dvc/dependency/repo.py
  dvc/external_repo.py
  dvc/repo/__init__.py
  dvc/repo/fetch.py
  dvc/repo/get.py
  dvc/repo/ls.py
  dvc/tree/_metadata.py
  dvc/tree/dvc.py
  dvc/tree/git.py
  dvc/tree/repo.py
  tests/func/test_api.py
  tests/func/test_external_repo.py
  tests/func/test_get.py
  tests/func/test_import.py
  tests/func/test_ls.py
  tests/func/test_run_multistage.py
  tests/func/test_update.py
  tests/unit/test_external_repo.py
  tests/unit/tree/test_repo_metadata.py
Labels: enhancement, feature, minor

#4518 diff: use RepoTree to compare directory contents
  dvc/repo/diff.py
  dvc/tree/dvc.py
  tests/func/test_diff.py
Labels: bugfix

#4530 diff: add state for files missing from both workspace and cache
  dvc/command/diff.py
  dvc/repo/diff.py
  tests/func/test_diff.py
  tests/unit/command/test_diff.py
Labels: enhancement, ui

#4544 dvc: change Dvcfile.dump to be synchronized by default
  dvc/dvcfile.py
  dvc/repo/commit.py
  dvc/repo/freeze.py
  dvc/repo/plots/__init__.py
  dvc/repo/reproduce.py
  dvc/repo/run.py
  tests/func/test_dvcfile.py
  tests/unit/test_dvcfile.py
Labels: refactoring

#4569 tree: validate resolved remote:// sections
  dvc/cache/__init__.py
  dvc/tree/__init__.py
  dvc/tree/base.py
  tests/unit/remote/test_remote.py
  tests/unit/tree/test_tree.py
Labels: bugfix, p0-critical

#4570 Fix error during external outputs checkout
  dvc/cache/base.py
  dvc/cache/local.py
  tests/func/test_checkout.py
Labels: bugfix, p0-critical

#4573 experiments: support committing to existing experiment branches
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
  dvc/repo/experiments/show.py
  tests/func/experiments/test_experiments.py
Labels: enhancement, experiments

#4469 github actions tests: initial
  .github/workflows/tests.yaml
  .travis.yml
  setup.py
  tests/func/test_add.py
  tests/func/test_api.py
  tests/func/test_cache.py
  tests/func/test_import_url.py
  tests/func/test_run_multistage.py
  tests/func/test_update.py
  tests/remotes/__init__.py
  tests/unit/output/test_local.py
Labels: build, ci

#4456 add py support for ParamsDependency
  dvc/utils/serialize/__init__.py
  dvc/utils/serialize/_py.py
  tests/func/experiments/test_experiments.py
  tests/func/params/test_show.py
  tests/unit/dependency/test_params.py
Labels: feature

#4611 experiments: support cloning parent in detached-head state
  dvc/repo/experiments/__init__.py
  tests/func/experiments/test_experiments.py
Labels: bugfix, experiments

#4612 experiments: fix --all-tags/--all-branches bug
  dvc/repo/brancher.py
  dvc/repo/experiments/show.py
Labels: bugfix, experiments

#4629 repo: move templates to plots
  dvc/repo/__init__.py
  dvc/repo/init.py
  dvc/repo/plots/__init__.py
  dvc/repo/plots/diff.py
  tests/func/plots/test_plots.py
Labels: refactoring

#4631 repo: move index_dir to RemoteIndex
  dvc/remote/index.py
  dvc/repo/__init__.py
  dvc/repo/experiments/executor.py
  tests/unit/remote/test_index.py
Labels: refactoring

#4643 hdfs: add a progress bar
  dvc/tree/hdfs.py
  tests/func/test_data_cloud.py
Labels: enhancement, p0-critical, ui

#4620 metrics, plots: update cmd targets help
  dvc/command/metrics.py
  dvc/command/plots.py
Labels: ui

#4644 gha: enable hdfs tests
  tests/func/test_add.py
  tests/func/test_api.py
  tests/func/test_gc.py
  tests/func/test_import_url.py
  tests/func/test_run_multistage.py
  tests/func/test_update.py
  tests/remotes/hdfs.py
Labels: ci, testing

#4651 bump shtab dependency
  setup.py
Labels: bugfix, completion, ui
