Repository iterative/dvc, pull requests merged in 2020-05, with the labels that each got.

#3721 progress: add postfix info to avoid overwriting desc
  dvc/progress.py
  dvc/remote/base.py
  dvc/remote/ssh/__init__.py
  dvc/repo/add.py
  dvc/repo/checkout.py
  dvc/scm/git/__init__.py
Labels: discussion, enhancement, refactoring, ui

#3731 Make comparisons in is_cached independent of order
  dvc/serialize.py
  dvc/stage/__init__.py
Labels: enhancement

#3730 ui: simplify/shorten error messages
  dvc/command/run.py
  dvc/exceptions.py
  dvc/main.py
  dvc/stage/__init__.py
  dvc/stage/exceptions.py
Labels: ui

#3735 pull/fetch/push: add stats
  dvc/command/checkout.py
  dvc/command/data_sync.py
  dvc/repo/pull.py
  dvc/utils/humanize.py
  tests/func/test_checkout.py
  tests/func/test_data_cloud.py
  tests/unit/command/test_checkout.py
  tests/unit/command/test_data_sync.py
  tests/unit/utils/test_humanize.py
Labels: ui

#3722 gdrive: download: stream & add progress
  dvc/remote/gdrive.py
  setup.py
Labels: performance, refactoring, research, ui

#3747 repro: use dvc.yaml by default
  dvc/command/base.py
  dvc/command/pipeline.py
  tests/func/test_repro.py
  tests/unit/command/test_repro.py
Labels: enhancement, pipeline-file

#3757 params/metrics: diff: implement tabulated markdown output (--show-md)
  dvc/command/diff.py
  dvc/command/metrics.py
  dvc/command/params.py
  dvc/utils/diff.py
  setup.py
  tests/unit/command/test_diff.py
  tests/unit/command/test_metrics.py
  tests/unit/command/test_params.py
Labels: enhancement

#3767 pipeline file: disallow punctuation characters in stage name
  dvc/repo/run.py
  dvc/stage/__init__.py
  dvc/stage/exceptions.py
  tests/func/test_repro.py
  tests/func/test_run_multistage.py
Labels: enhancement, pipeline-file

#3786 diff: autocompletion script for params, and show-md
  scripts/completion/dvc.bash
  scripts/completion/dvc.zsh
Labels: completion

#3793 stage: moving things around, refactor
  dvc/serialize.py
  dvc/stage/__init__.py
  dvc/stage/exceptions.py
  dvc/stage/imports.py
  dvc/stage/loader.py
  dvc/stage/run.py
  dvc/stage/utils.py
  tests/func/test_repro.py
  tests/func/test_run_single_stage.py
  tests/func/test_stage.py
  tests/unit/test_stage.py
Labels: enhancement, refactoring

#3800 refactor: simplify checkouts and run, get rid of check_can_commit
  dvc/repo/checkout.py
  dvc/repo/commit.py
  dvc/stage/__init__.py
  dvc/stage/run.py
Labels: refactoring

#3785 dvc.yaml: remove outs_no_cache, etc. keys, merge inside metrics/outs
  dvc/output/__init__.py
  dvc/schema.py
  dvc/serialize.py
  dvc/stage/loader.py
  tests/dir_helpers.py
  tests/func/test_lockfile.py
  tests/func/test_run_multistage.py
Labels: pipeline-file

#3816 stage: fix commit
  dvc/stage/__init__.py
  tests/func/test_commit.py
Labels: bug, p0-critical

#3823 repro: do not log when stage is locked and is import
  dvc/repo/reproduce.py
Labels: enhancement, ui

#3806 logger: add trace, count --verbose/--quiet
  dvc/cli.py
  dvc/logger.py
  dvc/main.py
  dvc/state.py
  tests/unit/test_logger.py
Labels: discussion, enhancement, refactoring, research, ui

#3831 repro: fix help message for default target
  dvc/command/repro.py
Labels: ui

#3864 test: fix hdfs/azurite/oss tests
  dvc/remote/hdfs.py
  dvc/remote/local.py
  dvc/remote/ssh/__init__.py
  scripts/ci/before_install.sh
  scripts/ci/install_azurite.sh
  setup.py
  tests/func/test_repro.py
  tests/unit/remote/test_azure.py
Labels: build, p0-critical, testing

#3865 snap: release non-stable-semver tags to beta
  README.rst
  scripts/ci/before_install.sh
Labels: build, discussion, enhancement, feature request, research, testing

#3834 log: reduce log, make it readable/easier
  dvc/dvcfile.py
  dvc/output/base.py
  dvc/repo/reproduce.py
  dvc/repo/run.py
  dvc/stage/__init__.py
  dvc/stage/imports.py
  dvc/stage/run.py
  tests/unit/stage/test_run.py
Labels: ui

#3850 run: raise error when command is not specified
  dvc/repo/run.py
  tests/func/metrics/conftest.py
  tests/func/metrics/test_diff.py
  tests/func/metrics/test_show.py
  tests/func/params/test_diff.py
  tests/func/params/test_show.py
  tests/func/plots/__init__.py
  tests/func/plots/conftest.py
  tests/func/plots/test_diff.py
  tests/func/plots/test_plots.py
  tests/func/test_ls.py
  tests/func/test_remote.py
  tests/func/test_repro.py
  tests/func/test_run_multistage.py
  tests/func/test_run_single_stage.py
Labels: ui

#3887 modify issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#3910 use fork of mockssh-server
  setup.py
Labels: build, c1-quick-fix, ci, testing

#3881 Implement removing of the stage
  dvc/command/remove.py
  dvc/command/run.py
  dvc/dvcfile.py
  dvc/repo/remove.py
  dvc/repo/run.py
  dvc/stage/__init__.py
  tests/func/test_dvcfile.py
  tests/func/test_gc.py
  tests/func/test_remove.py
  tests/func/test_repro.py
  tests/func/test_run_multistage.py
  tests/func/test_run_single_stage.py
  tests/func/test_stage.py
  tests/unit/command/test_run.py
Labels: pipeline-file
