Repository iterative/dvc, pull requests merged in 2020-12, with the labels that each got.

#4952 git: add support for working with refspecs and stashes
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/__init__.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/stash.py
  setup.py
  tests/func/test_scm.py
  tests/unit/scm/test_git.py
Labels: experiments, skip-changelog

#5002 parametrization: show interpolated vars in params diff
  dvc/parsing/__init__.py
  dvc/repo/params/show.py
  dvc/stage/__init__.py
  dvc/stage/loader.py
  tests/func/params/test_diff.py
  tests/func/test_stage_resolver.py
Labels: enhancement, parametrization, skip-changelog

#5004 parametrization: convert bool to string as "true"/"false"
  dvc/parsing/interpolate.py
  tests/func/test_stage_resolver.py
  tests/unit/test_context.py
Labels: bugfix, parametrization, skip-changelog

#4975 plots: make linear and scatter interactive
  dvc/repo/plots/template.py
Labels: enhancement, ui

#4910 experiments: store experiments in refs/exps instead of heads
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/apply.py
  dvc/repo/experiments/base.py
  dvc/repo/experiments/branch.py
  dvc/repo/experiments/checkout.py
  dvc/repo/experiments/diff.py
  dvc/repo/experiments/executor.py
  dvc/repo/experiments/gc.py
  dvc/repo/experiments/run.py
  dvc/repo/experiments/show.py
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/stage/__init__.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_diff.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_gc.py
  tests/func/experiments/test_show.py
  tests/unit/command/test_experiments.py
Labels: breaking-change, experiments

#4706 Organize metrics as table
  dvc/command/metrics.py
  tests/func/test_repro.py
  tests/unit/command/test_metrics.py
Labels: awaiting response

#5016 snap: publish to v1 channel
  .github/workflows/packages.yaml
Labels: build, c1-quick-fix, maintenance

#4973 hdfs: Replace deprecated pyarrow.hdfs.connect
  dvc/tree/hdfs.py
  tests/remotes/hdfs.py
Labels: awaiting response

#5018 Enable parametrization by default
  dvc/config.py
  dvc/stage/loader.py
  tests/func/params/test_diff.py
  tests/func/test_dvcfile.py
  tests/func/test_feature_flags.py
  tests/func/test_stage_load.py
Labels: enhancement, parametrization

#5019 experiments: enable by default, support no_scm
  dvc/command/experiments.py
  dvc/config.py
  dvc/repo/__init__.py
  dvc/repo/experiments/__init__.py
  dvc/repo/plots/diff.py
  tests/func/experiments/test_experiments.py
  tests/unit/command/test_experiments.py
Labels: enhancement, experiments

#5020 provide a callback to handle error during the stage collection
  dvc/repo/__init__.py
  dvc/repo/stage.py
  tests/func/test_remove.py
  tests/func/test_stage_load.py
Labels: refactoring

#5022 scm: move logic to gitpython backend
  dvc/external_repo.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/apply.py
  dvc/repo/experiments/executor.py
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/stash.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_show.py
  tests/func/test_checkout.py
  tests/func/test_import.py
  tests/func/test_install.py
  tests/func/test_scm.py
  tests/func/test_status.py
  tests/func/test_update.py
  tests/unit/scm/test_git.py
Labels: refactoring, skip-changelog

#5026 scm/git: add support for resolving experiment names
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/apply.py
  dvc/repo/experiments/base.py
  dvc/repo/experiments/branch.py
  dvc/repo/experiments/gc.py
  dvc/repo/experiments/utils.py
  dvc/scm/git/__init__.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_show.py
Labels: enhancement, experiments

#5029 experiments: ignore untracked files
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/stage/run.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_experiments.py
Labels: bugfix, experiments

#5041 run/repro: show command on dry-run, add ">" to script output
  dvc/stage/run.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_stage.py
  tests/unit/stage/test_run.py
Labels: bugfix

#4991 update issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: maintenance

#5052 experiments: handle state where tmp args file was committed to git
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/stash.py
  tests/func/experiments/test_experiments.py
Labels: bugfix, experiments

#5049 git: drop scm requirement from backends
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/stash.py
  tests/unit/scm/test_git.py
Labels: maintenance, refactoring

#5042 experiments: add `dvc exp push/pull/list`
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
  dvc/repo/experiments/ls.py
  dvc/repo/experiments/pull.py
  dvc/repo/experiments/push.py
  dvc/repo/experiments/utils.py
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_remote.py
  tests/unit/command/test_experiments.py
  tests/unit/scm/test_git.py
Labels: enhancement, experiments

#5057 [1.11] [BACKPORT] pin numpy for windows build
  scripts/build-requirements.txt
Labels: build

#5054 tests: fix windows tests
  dvc/repo/experiments/executor.py
  dvc/scm/git/backend/dulwich.py
  tests/func/experiments/test_experiments.py
Labels: maintenance, p0-critical, testing

#5063 parametrization: disable `set` keyword
  dvc/parsing/__init__.py
  dvc/schema.py
Labels: breaking-change, enhancement, parametrization

#5064 experiments: support experiments cache collection for exp push/pull/gc
  dvc/command/experiments.py
  dvc/command/gc.py
  dvc/repo/__init__.py
  dvc/repo/brancher.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/pull.py
  dvc/repo/experiments/push.py
  dvc/repo/experiments/utils.py
  dvc/repo/fetch.py
  dvc/repo/gc.py
  dvc/repo/push.py
  dvc/scm/git/backend/gitpython.py
  tests/func/experiments/test_remote.py
  tests/func/test_gc.py
  tests/unit/command/test_experiments.py
  tests/unit/scm/test_git.py
Labels: enhancement, experiments

#5072 experiments: fix mypy errors
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
Labels: maintenance, skip-changelog

#5071 exp show: fix --exclude-...
  dvc/command/experiments.py
  tests/func/experiments/test_show.py
Labels: bugfix, ui

#5073 git: fix mypy errors
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
Labels: maintenance, skip-changelog

#5035 Run graph checks on `collect`/`find_outs_by_path`
  dvc/repo/__init__.py
  dvc/repo/collect.py
  tests/func/metrics/test_common.py
  tests/unit/repo/test_repo.py
Labels: bugfix

#5075 git: don't list all commits to check for an empty repo
  dvc/scm/git/__init__.py
Labels: performance

#5079 misc: fix remaining mypy errors
  dvc/command/experiments.py
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/utils/__init__.py
Labels: maintenance, skip-changelog

#5086 [1.11] [BACKPORT] system: _reflink_darwin: use fsencode for path
  dvc/system.py
Labels: bug

#5090 cli: config: check name format
  dvc/command/config.py
  tests/func/test_cli.py
  tests/func/test_config.py
  tests/unit/command/test_config.py
Labels: backport 1.11, bug, ui

#5077 parametrization: refactor resolver and optimize
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/parsing/interpolate.py
  dvc/stage/loader.py
  tests/func/parsing/__init__.py
  tests/func/parsing/test_errors.py
  tests/func/parsing/test_foreach.py
  tests/func/parsing/test_interpolated_entry.py
  tests/func/parsing/test_resolver.py
  tests/func/test_stage_resolver.py
  tests/func/test_stage_resolver_error_msg.py
  tests/unit/test_context.py
  tests/unit/test_interpolate.py
  tests/unit/test_stage_resolver.py
Labels: parametrization, refactoring

#4733 fix making too many ssh connections when pushing run cache (#4732)
  dvc/tree/pool.py
Labels: awaiting response

#5098 dvcignore: don't walk directories twice
  dvc/ignore.py
Labels: performance

#5103 Skip building graph for dependencies without path_info
  dvc/repo/graph.py
Labels: bugfix

#5106 remove key/value magic/special string
  dvc/parsing/__init__.py
Labels: enhancement, parametrization, refactoring

#5104 disallow overriding `item` and `key` in the foreach loop
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  tests/func/parsing/test_errors.py
Labels: bugfix, enhancement, parametrization

#5107 Prevent loading non-dictionary based params/vars file
  dvc/parsing/context.py
Labels: bugfix, enhancement, parametrization

#5093 experiments: handle `exp run` from within subdirs/subrepos
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
  dvc/repo/reproduce.py
  dvc/scm/git/backend/dulwich.py
  dvc/stage/run.py
  tests/func/experiments/test_experiments.py
Labels: bugfix, experiments

#5123 params diff: skip params dependency for vars
  dvc/repo/params/show.py
Labels: backport-11.1, bugfix, parametrization

#5121 params/metrics diff: collect from revisions/workspace twice
  dvc/repo/metrics/diff.py
  dvc/repo/params/diff.py
Labels: backport-1.11, bugfix, optimize

#5125 Cleanup debug log messages when loading stages
  dvc/parsing/__init__.py
  dvc/stage/__init__.py
  dvc/stage/loader.py
Labels: enhancement, ui

#5124 experiments: run single experiments in user's workspace by default
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/apply.py
  dvc/repo/experiments/base.py
  dvc/repo/experiments/executor/__init__.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/executor/local.py
  dvc/repo/experiments/run.py
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/dulwich.py
  tests/func/experiments/conftest.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_gc.py
  tests/func/experiments/test_show.py
  tests/unit/command/test_experiments.py
Labels: enhancement, experiments

#5032 pull: add glob option
  dvc/command/data_sync.py
  dvc/repo/add.py
  dvc/repo/pull.py
  dvc/utils/__init__.py
  tests/func/test_import.py
Labels: awaiting response

#5139 tree: local: remove misc redundant logic
  dvc/tree/local.py
Labels: refactoring, skip-changelog

#5142 parametrization: move comment, fix exception error msg
  dvc/parsing/__init__.py
  dvc/parsing/context.py
Labels: refactoring

#5143 git: show progress when pushing/fetching git refs
  dvc/scm/git/backend/dulwich.py
Labels: ui

#5147 experiments: cleanup minor UI issues
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/apply.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/executor/local.py
Labels: skip-changelog, ui

#5152 lock: fix AttributeError in dvc.lock.HardlinkLock
  dvc/lock.py
Labels: bugfix

#5078 experiments: commit with --no-verify in executors
  dvc/repo/experiments/executor/base.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/backend/pygit2.py
  setup.py
  tests/unit/scm/test_git.py
Labels: bugfix, experiments

#5168 Remove Sourcerer's hall of fame
  README.rst
Labels: maintenance

#5171 parametrization: fix error when the file in `vars` is a directory
  dvc/parsing/context.py
  tests/unit/test_context.py
Labels: bugfix, parametrization

#5175 experiments: fix checkout error for unexisting outputs
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/base.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/reproduce.py
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/backend/pygit2.py
  dvc/scm/git/stash.py
  dvc/stage/__init__.py
  tests/func/experiments/conftest.py
  tests/func/experiments/test_experiments.py
Labels: bugfix, skip-changelog

#5174 erepo: make repo configuration explicit
  dvc/config.py
  dvc/external_repo.py
  dvc/repo/__init__.py
  tests/unit/test_external_repo.py
Labels: refactoring, skip-changelog
