Repository iterative/dvc, pull requests merged in 2020-04, with the labels that each got.

#3576 metrics: diff: don't print "No changes"
  dvc/command/metrics.py
  tests/unit/command/test_metrics.py
Labels: p0-critical

#3583 progress: better threading
  setup.py
Labels: p1-important, ui

#3592 GDrive: use lates PyDrive2 version to fix large file uploads
  setup.py
Labels: bug, p0-critical

#3609 metrics: diff: fix float precision formatting
  dvc/command/metrics.py
  tests/unit/command/test_metrics.py
Labels: c3-small-fix, p0-critical

#3615 params: fix bug when collecting multiple params
  dvc/repo/params/show.py
  tests/func/params/test_show.py
Labels: bug, p0-critical

#3617 params: diff: sort table
  dvc/command/params.py
  tests/unit/command/test_params.py
Labels: p0-critical, ui

#3613 completion: bash: fix files
  scripts/completion/dvc.bash
Labels: bug, c1-quick-fix, ui

#3619 refactor: extract stage's relationship with Dvcfile out from Stage
  dvc/command/base.py
  dvc/command/pipeline.py
  dvc/command/run.py
  dvc/dvcfile.py
  dvc/output/base.py
  dvc/repo/__init__.py
  dvc/repo/add.py
  dvc/repo/checkout.py
  dvc/repo/commit.py
  dvc/repo/get.py
  dvc/repo/imp_url.py
  dvc/repo/lock.py
  dvc/repo/metrics/modify.py
  dvc/repo/move.py
  dvc/repo/remove.py
  dvc/repo/reproduce.py
  dvc/repo/run.py
  dvc/repo/tag/add.py
  dvc/repo/tag/remove.py
  dvc/repo/update.py
  dvc/stage/__init__.py
  dvc/stage/decorators.py
  dvc/stage/exceptions.py
  dvc/stage/schema.py
  dvc/utils/__init__.py
  tests/func/test_add.py
  tests/func/test_checkout.py
  tests/func/test_commit.py
  tests/func/test_import.py
  tests/func/test_move.py
  tests/func/test_remove.py
  tests/func/test_repro.py
  tests/func/test_run.py
  tests/func/test_stage.py
  tests/func/test_update.py
  tests/unit/command/test_run.py
  tests/unit/test_stage.py
Labels: enhancement, refactoring

#3632 remote: use .dir checksum existence to infer file contents existence
  dvc/cache.py
  dvc/data_cloud.py
  dvc/output/base.py
  dvc/remote/base.py
  dvc/remote/local.py
  dvc/repo/__init__.py
  dvc/repo/fetch.py
  tests/func/test_gc.py
  tests/func/test_remote.py
  tests/unit/repo/test_repo.py
Labels: performance

#3584 dvc: implement multi-stage dvcfile
  dvc/command/pipeline.py
  dvc/command/run.py
  dvc/dvcfile.py
  dvc/lockfile.py
  dvc/repo/__init__.py
  dvc/repo/add.py
  dvc/repo/imp_url.py
  dvc/repo/lock.py
  dvc/repo/reproduce.py
  dvc/repo/run.py
  dvc/schema.py
  dvc/stage/__init__.py
  dvc/stage/params.py
  dvc/stage/schema.py
  dvc/utils/__init__.py
  tests/func/test_dvcfile.py
  tests/func/test_pipeline.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_run_multistage.py
  tests/func/test_run_single_stage.py
  tests/unit/command/test_run.py
  tests/unit/test_lockfile.py
Labels: p1-important, product

#3595 scm: git: clone: add progress
  dvc/scm/git/__init__.py
Labels: enhancement, ui

#3655 refactor: extract stage loading outside of dvcfile
  dvc/command/pipeline.py
  dvc/dvcfile.py
  dvc/loader.py
  dvc/lockfile.py
  dvc/output/base.py
  dvc/repo/__init__.py
  dvc/repo/add.py
  dvc/repo/imp_url.py
  dvc/repo/lock.py
  dvc/repo/remove.py
  dvc/repo/reproduce.py
  dvc/repo/run.py
  dvc/repo/update.py
  dvc/serialize.py
  dvc/stage/__init__.py
  tests/func/test_checkout.py
  tests/func/test_dvcfile.py
  tests/func/test_import.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_run_multistage.py
  tests/func/test_stage.py
  tests/func/test_update.py
  tests/unit/test_lockfile.py
Labels: refactoring

#3634 remote: locally index list of checksums available on cloud remotes
  dvc/remote/base.py
  dvc/remote/index.py
  dvc/remote/local.py
  dvc/repo/__init__.py
  tests/func/remote/test_index.py
  tests/unit/remote/test_base.py
  tests/unit/remote/test_index.py
Labels: performance

#3660 gc: don't forget to load remote index
  dvc/remote/base.py
Labels: bug, p0-critical

#3663 output: use strings instead of PathInfo for performance reasons
  dvc/output/base.py
Labels: performance

#3674 flake8: fix ambiguous var names
  dvc/dagascii.py
  tests/func/test_repro.py
Labels: refactoring

#3594 progress: add main bars
  dvc/remote/local.py
Labels: enhancement, ui

#3672 remote: use string paths over PathInfo for performance reasons
  dvc/remote/base.py
  dvc/remote/local.py
  dvc/state.py
Labels: performance

#3689 repo: use reverse post-order DFS in repro --downstream
  dvc/repo/reproduce.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
Labels: bug

#3699 tag: getting rid of it
  dvc/cli.py
  dvc/command/pipeline.py
  dvc/command/tag.py
  dvc/dvcfile.py
  dvc/output/__init__.py
  dvc/output/base.py
  dvc/repo/__init__.py
  dvc/repo/lock.py
  dvc/repo/remove.py
  dvc/repo/reproduce.py
  dvc/repo/tag/__init__.py
  dvc/repo/tag/add.py
  dvc/repo/tag/list.py
  dvc/repo/tag/remove.py
  dvc/stage/__init__.py
  dvc/stage/loader.py
  dvc/utils/__init__.py
  tests/func/test_tag.py
  tests/unit/utils/test_utils.py
Labels: enhancement, refactoring

#3686 gdrive: fix multi-remote workflow, cont. cleanup
  dvc/config.py
  dvc/data_cloud.py
  dvc/remote/gdrive.py
  tests/func/remote/test_gdrive.py
  tests/unit/remote/test_gdrive.py
Labels: bug, enhancement

#3705 remote: adjust traverse threshold multiplier
  dvc/remote/base.py
Labels: performance

#3711 dump: deterministic lockfile dump
  dvc/serialize.py
  dvc/utils/stage.py
  tests/func/test_lockfile.py
Labels: enhancement, pipeline-file
