Repository iterative/dvc, pull requests merged in 2020-10, with the labels that each got.

#4652 api.open: fix error if uncached file inside a dir is accessed
  dvc/repo/__init__.py
  dvc/tree/dvc.py
  dvc/tree/repo.py
  tests/func/test_api.py
Labels: bugfix

#4647 Run CI for Python3.9
  .github/workflows/tests.yaml
  dvc/scm/git.py
  setup.py
  tests/__init__.py
  tests/func/test_output.py
  tests/func/test_version.py
  tests/remotes/hdfs.py
  tests/unit/dependency/test_hdfs.py
  tests/unit/output/test_hdfs.py
  tests/unit/test_info.py
Labels: build, ci

#4626 diff/dvctree: optimize dir cache access
  dvc/cache/base.py
  dvc/hash_info.py
  dvc/output/base.py
  dvc/repo/diff.py
  dvc/tree/base.py
  dvc/tree/dvc.py
Labels: bugfix, performance

#4666 dvc: print version to debug log
  dvc/main.py
Labels: ui

#4591 experiments: checkpoints proof of concept
  dvc/api.py
  dvc/command/experiments.py
  dvc/output/base.py
  dvc/repo/checkout.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
  dvc/repo/experiments/show.py
  dvc/repo/reproduce.py
  dvc/stage/decorators.py
  dvc/stage/run.py
  tests/func/experiments/test_experiments.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_stage.py
  tests/unit/command/test_experiments.py
Labels: experiments, feature

#4676 state: use granularly
  dvc/api.py
  dvc/cache/base.py
  dvc/cache/local.py
  dvc/repo/__init__.py
  dvc/state.py
  dvc/tree/base.py
  tests/func/test_commit.py
  tests/func/test_data_cloud.py
  tests/func/test_remote.py
  tests/func/test_run_cache.py
  tests/func/test_state.py
  tests/func/test_tree.py
  tests/unit/dependency/test_params.py
  tests/unit/repo/test_repo.py
  tests/unit/tree/test_dvc.py
  tests/unit/tree/test_repo.py
Labels: refactoring

#4678 experiments: fix checkpoints callback bug when pipeline includes data stages
  dvc/repo/experiments/__init__.py
  dvc/repo/reproduce.py
Labels: bugfix, experiments

#4685 dvc: get rid of ExternalGitRepo
  dvc/external_repo.py
Labels: refactoring

#4677 experiments: migrate `dvc repro -e` to `dvc exp run`
  dvc/command/experiments.py
  dvc/command/repro.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/run.py
  dvc/repo/reproduce.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_show.py
  tests/unit/command/test_experiments.py
  tests/unit/command/test_repro.py
Labels: experiments, maintenance

#4689 experiments: add `--show-json` for `exp show`
  dvc/command/experiments.py
Labels: enhancement, experiments

#4680 tests build: buil on push/pr to master
  .github/workflows/tests.yaml
Labels: ci

#4646 Fixed the bug #4251, and fixed a minor bug which causes of OS default character.
  dvc/repo/get_url.py
  setup.py
Labels: awaiting response

#4700 ls: pass repo_tree instead of repo
  dvc/repo/ls.py
Labels: c1-quick-fix, refactoring, skip-changelog

#4702 gha: get rid of unnecessary if
  .github/workflows/tests.yaml
Labels: build, ci, skip-changelog

#4704 Use released version of Python3.9 on CI
  .github/workflows/tests.yaml
Labels: ci, maintenance

#4701 experiments: support `exp run --checkpoint` for baseline commits
  dvc/repo/experiments/__init__.py
  dvc/scm/git.py
  dvc/stage/run.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_stage.py
Labels: bugfix, experiments

#4714 tests: fix test_remote::test_push_order
  tests/func/test_remote.py
Labels: bugfix, skip-changelog, testing

#4718 tests: mark test_extend_branch as flaky
  tests/func/experiments/test_experiments.py
Labels: skip-changelog, testing

#4716 checkpoints: cleanup --continue usage
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
Labels: experiments, skip-changelog, ui

#4679 Parametrization support on dvc.yaml
  dvc/config.py
  dvc/dvcfile.py
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/parsing/interpolate.py
  tests/func/test_feature_flags.py
  tests/unit/test_interpolate.py
  tests/unit/test_stage_resolver.py
Labels: feature, skip-changelog

#4727 experiments: fix git stash mtime race condition
  dvc/repo/experiments/__init__.py
  tests/func/experiments/test_experiments.py
Labels: bugfix, skip-changelog, testing

#4728 tests, packages: roll back environmental files change
  .github/workflows/packages.yaml
  .github/workflows/tests.yaml
Labels: ci, maintenance, skip-changelog

#4731 checkpoints: add `--reset` option
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
  tests/func/experiments/test_experiments.py
  tests/unit/command/test_experiments.py
Labels: experiments, skip-changelog, ui

#4715 checkpoints: create final checkpoint commit after repro when needed
  dvc/repo/__init__.py
  dvc/repo/experiments/__init__.py
Labels: bugfix, experiments

#4730 experiments: use general format for floating pt numbers
  dvc/command/experiments.py
Labels: experiments, skip-changelog, ui

#4670 make pull --run-cache work with local remote having relative path
  dvc/path_info.py
  tests/unit/test_path_info.py
Labels: bugfix, run-cache

#4748 Use lxml wheel instead of legacy setup.py builds
  .github/workflows/tests.yaml
Labels: maintenance, skip-changelog

#4740 experiments: fix checkpoints sorting issues in `dvc exp show`
  dvc/command/experiments.py
  dvc/repo/experiments/show.py
Labels: bugfix, experiments, skip-changelog, ui

#4745 plots: don't allow in non-dvc repo
  dvc/command/plots.py
Labels: c1-quick-fix

#4751 Support parametrization from params or vars section in dvc.yaml
  dvc/dvcfile.py
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/parsing/interpolate.py
  dvc/schema.py
  tests/unit/test_context.py
  tests/unit/test_stage_resolver.py
Labels: enhancement, feature, skip-changelog

#4750 checkpoints: allow missing outputs on checkout and stage.run
  dvc/output/base.py
  dvc/repo/checkout.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
  dvc/stage/__init__.py
  dvc/stage/run.py
Labels: enhancement, experiments, skip-changelog

#4755 Revert "Track flaky tests using Google's service"
  .github/workflows/tests.yaml
  setup.py
Labels: ci, maintenance, skip-changelog

#4753 Add tests for resolving stage data
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  tests/func/test_stage_resolver.py
  tests/unit/test_context.py
Labels: feature, skip-changelog, testing

#4758 checkpoints: `--continue` from last run experiment by default
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  tests/func/experiments/test_experiments.py
Labels: experiments, skip-changelog, ui

#4759 init: move welcome message from `Repo.init` to `command.init`
  dvc/command/init.py
  dvc/repo/init.py
Labels: skip-changelog, ui

#4771 experiments: fix list/dict params and metrics being displayed as empty string
  dvc/command/experiments.py
Labels: bugfix, build, experiments

#4754 Make codecov push results on every run
  .codecov.yml
  .github/workflows/tests.yaml
Labels: ci, maintenance, skip-changelog

#4760 Display coverage report on the GHA log and measure branch coverage
  .coveragerc
  .github/workflows/tests.yaml
Labels: ci, maintenance, skip-changelog

#4781 test_update_import: roll back skip
  tests/func/test_update.py
Labels: skip-changelog, testing

#4761 plots/metrics: support show for no repo
  dvc/repo/__init__.py
  dvc/repo/metrics/show.py
  tests/func/metrics/test_show.py
  tests/func/plots/test_plots.py
Labels: feature, ui

#4764 plot: fix no metrics data detection
  dvc/repo/plots/__init__.py
Labels: bugfix, ui

#4778 add: fix issue when adding already tracked symlinked files
  dvc/utils/__init__.py
  tests/func/test_add.py
Labels: bugfix

#4795 pyarrow: upgrade to 2.0.0
  setup.py
Labels: maintenance

#4805 experiments: fix stash ordering bug
  dvc/repo/experiments/__init__.py
  tests/func/experiments/test_experiments.py
Labels: bugfix, skip-changelog

#4809 git: use dulwich for .gitignore
  dvc/scm/git.py
  setup.py
Labels: performance, testing

#4789 metrics/plots: test metrics collection on no target on revision
  dvc/repo/experiments/show.py
  dvc/repo/metrics/show.py
  tests/func/metrics/metrics/__init__.py
  tests/func/metrics/metrics/test_diff.py
  tests/func/metrics/metrics/test_show.py
  tests/func/metrics/plots/__init__.py
  tests/func/metrics/plots/conftest.py
  tests/func/metrics/plots/test_diff.py
  tests/func/metrics/plots/test_modify.py
  tests/func/metrics/plots/test_show.py
  tests/func/metrics/test_common.py
  tests/func/metrics/utils.py
Labels: bugfix, ui

#4801 add: warn on cache link errors instead of failing
  dvc/cache/base.py
  dvc/exceptions.py
  dvc/repo/add.py
  dvc/stage/__init__.py
  tests/func/test_add.py
Labels: bugfix

#4810 git: move branch iteration functionality from experiments into scm.git
  dvc/repo/experiments/show.py
  dvc/scm/git.py
  tests/unit/scm/test_git.py
Labels: refactoring, skip-changelog
