Repository iterative/dvc, pull requests merged in 2020-11, with the labels that each got.

#4826 diff: handle empty output status
  dvc/repo/diff.py
Labels: bugfix

#4734 Implement foreach ... in loop in dvc.yaml
  dvc/parsing/__init__.py
  dvc/schema.py
  tests/func/test_stage_resolver.py
Labels: feature, skip-changelog

#4757 dvc.yaml: introduce set keyword
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/parsing/interpolate.py
  dvc/schema.py
  tests/func/test_stage_resolver.py
  tests/unit/test_stage_resolver.py
Labels: feature, skip-changelog

#4831 refactor context set/alias to Context class
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/parsing/interpolate.py
Labels: refactoring, skip-changelog

#4833 refactor context: provide interpolation through Context API
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/parsing/interpolate.py
  tests/unit/test_interpolate.py
Labels: refactoring, skip-changelog

#4834 Add flaky-service (Again)
  .github/workflows/tests.yaml
  setup.py
Labels: ci, skip-changelog

#4823 experiments: fix checkpoint checkout issues
  dvc/cache/base.py
  dvc/output/base.py
  dvc/repo/checkout.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
Labels: bugfix, skip-changelog

#4839 build: test built binary
  scripts/build_windows.cmd
Labels: build

#4785 http: raise error on unsuccessful http statuses on `exists`
  dvc/tree/http.py
  tests/unit/remote/test_http.py
Labels: bugfix

#4840 refactor: move interpolation logic inside the Context
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/parsing/interpolate.py
Labels: refactoring, skip-changelog

#4844 cache: refactor dir_info conversion
  dvc/cache/base.py
Labels: refactoring

#4852 gs: don't forget to include file size
  dvc/tree/gs.py
Labels: bugfix, skip-changelog

#4853 dvc: limit aws-sam-translator version for moto
  setup.py
Labels: build, maintenance, skip-changelog, testing

#4845 experiments: add checkpoint output type
  dvc/command/run.py
  dvc/output/__init__.py
  dvc/output/base.py
  dvc/repo/reproduce.py
  dvc/repo/run.py
  dvc/schema.py
  dvc/stage/__init__.py
  dvc/stage/serialize.py
  dvc/stage/utils.py
  tests/func/experiments/test_experiments.py
  tests/unit/command/test_run.py
Labels: experiments, skip-changelog

#4803 experiments: add `dvc exp gc`
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/gc.py
  tests/func/experiments/test_gc.py
  tests/unit/command/test_experiments.py
Labels: enhancement, experiments

#4851 dvc: use DirInfo instead of dicts/lists
  dvc/cache/base.py
  dvc/dir_info.py
  dvc/output/base.py
  dvc/tree/base.py
  dvc/tree/dvc.py
  tests/func/remote/test_index.py
  tests/func/test_add.py
  tests/func/test_cache.py
  tests/func/test_checkout.py
  tests/func/test_remote.py
  tests/func/test_tree.py
  tests/unit/output/test_local.py
  tests/unit/test_dir_info.py
  tests/unit/tree/test_repo.py
Labels: refactoring

#4846 parametrization: fix `merge_update` not converting data to `Node` object
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  tests/func/test_stage_resolver.py
  tests/unit/test_context.py
  tests/unit/test_interpolate.py
Labels: refactoring, skip-changelog

#4859 parametrization: skip loading globally used params section again locally for stages
  dvc/parsing/__init__.py
  tests/func/test_stage_resolver.py
Labels: bugfix, skip-changelog

#4866 cache: refactor cache types
  dvc/cache/__init__.py
  dvc/repo/gc.py
Labels: refactoring

#4869 parametrization: Support keys of the dictionary to be interpolated
  dvc/parsing/context.py
  tests/unit/test_context.py
Labels: enhancement, skip-changelog

#4802 [#4136] fixed recalculating relative paths in config
  dvc/config.py
  tests/func/remote/test_gdrive.py
  tests/func/test_config.py
Labels: awaiting response, bugfix

#4873 codecov: add target coverage, and threshold for patch and project
  .codecov.yml
Labels: ci, skip-changelog

#4855 checkpoints: `exp run` and `exp res[ume]` refactor
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
  dvc/repo/reproduce.py
  dvc/stage/__init__.py
  dvc/stage/run.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_experiments.py
  tests/unit/command/test_experiments.py
Labels: experiments, skip-changelog, ui

#4828 remote: avoid chunking on webdav. Fixes #4796
  dvc/tree/webdav.py
Labels: bugfix

#4877 checkpoints: set DVC_ROOT environment variable
  dvc/api.py
  dvc/env.py
  dvc/stage/run.py
  tests/func/experiments/test_checkpoints.py
Labels: experiments, skip-changelog

#4780 Simpler param updates with python-benedict
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/run.py
  setup.py
  tests/func/experiments/test_experiments.py
Labels: enhancement, experiments

#4827 Add test server and tests for webdav
  dvc/tree/webdav.py
  setup.py
  tests/func/test_api.py
  tests/func/test_data_cloud.py
  tests/remotes/__init__.py
  tests/remotes/webdav.py
  tests/unit/remote/test_webdav.py
  tests/utils/httpd.py
Labels: skip-changelog, testing

#4739 dag: add --outs option
  dvc/command/dag.py
  tests/unit/command/test_dag.py
Labels: awaiting response

#4885 experiments: fix checkpoint/persist related checkout issues
  dvc/dvcfile.py
  dvc/repo/experiments/__init__.py
Labels: bugfix, experiments, skip-changelog

#4888 send TAP result to flaky service only on master
  .github/workflows/tests.yaml
Labels: ci, skip-changelog

#4884 tests: real_s3 fixture: use specific path
  tests/remotes/s3.py
Labels: skip-changelog

#4895 dvc: add --pdb flag
  dvc/cli.py
  dvc/main.py
Labels: skip-changelog

#4892 ci: add macos-11 @ py3.8, py3.9 to build matrix
  .github/workflows/tests.yaml
Labels: ci

#4898 experiments: support branching w/modified params from intermediate checkpoint
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
  dvc/repo/experiments/show.py
  tests/func/experiments/conftest.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_show.py
Labels: experiments, skip-changelog, ui

#4890 experiments: preserve file permissions across tmpdir execution
  dvc/repo/experiments/__init__.py
  dvc/tree/base.py
  dvc/tree/gdrive.py
  dvc/tree/gs.py
  dvc/tree/http.py
  dvc/tree/local.py
  dvc/tree/s3.py
  dvc/tree/ssh/__init__.py
  dvc/tree/webdav.py
  tests/func/experiments/test_experiments.py
  tests/unit/tree/test_tree.py
Labels: bugfix, experiments, skip-changelog

#4747 Support for WebHDFS
  .pylintrc
  dvc/cache/__init__.py
  dvc/config.py
  dvc/dependency/__init__.py
  dvc/dependency/webhdfs.py
  dvc/output/__init__.py
  dvc/output/webhdfs.py
  dvc/scheme.py
  dvc/tree/__init__.py
  dvc/tree/webhdfs.py
  setup.py
  tests/docker-compose.yml
  tests/func/test_add.py
  tests/func/test_api.py
  tests/func/test_data_cloud.py
  tests/func/test_gc.py
  tests/func/test_import_url.py
  tests/func/test_update.py
  tests/remotes/__init__.py
  tests/remotes/hdfs.py
  tests/unit/remote/test_webhdfs.py
Labels: awaiting response

#4865 metrics/plots: common tests: check for particular exceptions
  dvc/command/metrics.py
  dvc/command/plots.py
  tests/func/metrics/test_common.py
Labels: skip-changelog

#4911 experiments: fix bug where repro with run-cached stages may fail
  dvc/repo/experiments/run.py
Labels: bugfix, skip-changelog

#4913 Bugfix: pop checkpoint resume from kwargs in experiments
  dvc/repo/experiments/__init__.py
  tests/func/experiments/test_checkpoints.py
Labels: bugfix, skip-changelog

#4914 Fix exp checkout queued and cleanup
  dvc/repo/experiments/__init__.py
  tests/func/experiments/test_experiments.py
Labels: bugfix, skip-changelog

#4880 parametrization: change `use` and `vars` to just `vars`
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/schema.py
  tests/func/test_stage_resolver.py
  tests/unit/test_context.py
Labels: feature, skip-changelog

#4916 parametrization: Move resolver to StageLoader from `Dvcfile`
  dvc/dvcfile.py
  dvc/parsing/__init__.py
  dvc/stage/loader.py
  tests/func/test_feature_flags.py
  tests/unit/stage/test_loader_pipeline_file.py
Labels: refactoring, skip-changelog

#4917 parametrization: Skip already used vars, even if they are in a relative path.
  dvc/parsing/__init__.py
  tests/func/test_stage_resolver.py
Labels: bugfix, skip-changelog

#4918 interpolation: support `[]` indices syntax
  dvc/parsing/interpolate.py
  setup.py
Labels: enhancement, skip-changelog

#4921 parametrization: raise appropriate error message on merge error
  dvc/parsing/context.py
  tests/unit/test_context.py
Labels: bugfix, skip-changelog

#4922 parametrization: improve key error message
  dvc/parsing/context.py
  tests/func/test_stage_resolver.py
  tests/unit/test_context.py
Labels: bugfix, skip-changelog

#4923 parametrization: improve set error message
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  tests/unit/test_context.py
  tests/unit/test_stage_resolver.py
Labels: enhancement, skip-changelog, ui

#4924 parametrization: improve 'vars' error message
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  tests/unit/test_context.py
Labels: bugfix, skip-changelog, ui

#4925 parsing: improve error messages when resolving keys of the stages
  dvc/parsing/__init__.py
  tests/func/test_stage_resolver.py
Labels: bugfix, enhancement, skip-changelog, ui

#4926 parametrization: improve error messages on foreach loop
  dvc/parsing/__init__.py
Labels: bugfix, enhancement, skip-changelog, ui

#4927 tests: add error message tests for resolving stages
  dvc/parsing/context.py
  tests/func/test_stage_resolver_error_msg.py
  tests/unit/test_context.py
Labels: skip-changelog, testing

#4928 change foreach...in to foreach...do
  dvc/parsing/__init__.py
  dvc/schema.py
  tests/func/test_stage_resolver.py
  tests/func/test_stage_resolver_error_msg.py
Labels: enhancement, skip-changelog

#4929 parametrization: change foreach stage name joiner from "-" to "@"
  dvc/parsing/__init__.py
  tests/func/test_stage_resolver.py
  tests/func/test_stage_resolver_error_msg.py
Labels: enhancement, skip-changelog

#4930 tests: indices syntax for parametrization
  tests/unit/test_interpolate.py
  tests/unit/test_stage_resolver.py
Labels: enhancement, skip-changelog, testing

#4920 tests: allow selectively running tests for remotes
  .github/workflows/tests.yaml
  tests/conftest.py
  tests/func/test_output.py
  tests/remotes/azure.py
  tests/remotes/gdrive.py
  tests/remotes/gs.py
  tests/remotes/hdfs.py
  tests/remotes/http.py
  tests/remotes/oss.py
  tests/remotes/s3.py
  tests/remotes/ssh.py
  tests/remotes/webdav.py
  tests/unit/dependency/test_hdfs.py
  tests/unit/output/test_hdfs.py
Labels: skip-changelog, testing

#4939 Fix metadata tests running with module-scoped fixtures
  tests/unit/tree/test_repo_metadata.py
Labels: bugfix, skip-changelog, testing

#4940 ci: reduce no. of macOS jobs
  .github/workflows/tests.yaml
Labels: ci, skip-changelog, testing

#4941 tree.repo: use PathStringTrie consistently
  dvc/tree/repo.py
Labels: refactoring, skip-changelog

#4942 tests: increase ulimit to 4096
  tests/__init__.py
Labels: skip-changelog, testing

#4943 tests: move some flags from `python -m tests` to config
  .github/workflows/tests.yaml
  setup.cfg
  tests/__main__.py
  tests/conftest.py
Labels: skip-changelog, testing

#4944 types: fix typechecking errors in dvc/repo
  dvc/repo/__init__.py
  dvc/repo/get.py
  dvc/repo/get_url.py
  dvc/repo/ls.py
Labels: skip-changelog, testing

#4945 types: fix typechecking errors around a few random places
  dvc/cache/base.py
  dvc/external_repo.py
  dvc/hash_info.py
  dvc/path_info.py
  dvc/scm/base.py
  dvc/scm/git.py
  dvc/stage/__init__.py
  dvc/stage/serialize.py
Labels: skip-changelog, testing

#4949 types: fix type checking errors in dvc.experiments
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor.py
Labels: skip-changelog, testing

#4948 types: fix type errors on dvc.collect
  dvc/repo/collect.py
  dvc/types.py
Labels: skip-changelog, testing

#4947 types: add types to dvc/tree
  dvc/tree/base.py
  dvc/tree/dvc.py
  dvc/tree/local.py
  dvc/tree/repo.py
Labels: skip-changelog, testing

#4946 types: fix typechecking errors (2)
  dvc/command/dag.py
  dvc/command/experiments.py
  dvc/dependency/base.py
  dvc/output/base.py
  dvc/output/gs.py
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/remote/local.py
  dvc/remote/slow_link_detection.py
  dvc/repo/params/show.py
  dvc/repo/plots/template.py
Labels: skip-changelog, testing

#4951 Add mypy config, fix type errors in a few remaining places
  dvc/parsing/context.py
  dvc/tree/base.py
  dvc/tree/ssh/connection.py
  dvc/utils/serialize/__init__.py
  dvc/utils/serialize/_common.py
  setup.cfg
  setup.py
Labels: skip-changelog, testing

#4950 parametrization: prevent dumping parametrized stages
  dvc/dvcfile.py
  dvc/stage/__init__.py
  dvc/stage/loader.py
  tests/func/test_dvcfile.py
Labels: enhancement, skip-changelog

#4953 parametrization: print pretty interpolation errors
  dvc/parsing/interpolate.py
  dvc/utils/__init__.py
  tests/func/test_stage_resolver_error_msg.py
Labels: enhancement, skip-changelog, ui

#4961 parse: parse target correctly for generated stages
  dvc/utils/__init__.py
  tests/unit/utils/test_utils.py
Labels: enhancement, parametrization

#4964 pre-commit: update hooks
  .pre-commit-config.yaml
  tests/remotes/__init__.py
Labels: ci, skip-changelog

#4966 Remove libs used in pre-commit
  setup.py
Labels: skip-changelog, testing

#4967 tests/ci: update docker image for Azurite
  tests/docker-compose.yml
Labels: ci, skip-changelog

#4968 s3: use mocked s3 instead of the real one
  setup.py
  tests/func/test_api.py
  tests/func/test_checkout.py
Labels: ci, testing

#4982 parametrization: support loading vars partially
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  tests/func/test_stage_resolver.py
  tests/func/test_stage_resolver_error_msg.py
Labels: enhancement, parametrization, skip-changelog

#4976 repro: support glob/foreach-group to run at once through CLI
  dvc/command/repro.py
  dvc/repo/__init__.py
  dvc/repo/freeze.py
  dvc/repo/remove.py
  dvc/repo/reproduce.py
  dvc/repo/stage.py
  dvc/stage/loader.py
  dvc/utils/__init__.py
  tests/func/test_dvcfile.py
  tests/func/test_repo.py
  tests/unit/command/test_repro.py
Labels: enhancement, parametrization, skip-changelog

#4993 Move `Repo.collect` and `collect_granular` to `Repo.stage`
  dvc/command/dag.py
  dvc/repo/__init__.py
  dvc/repo/checkout.py
  dvc/repo/commit.py
  dvc/repo/graph.py
  dvc/repo/reproduce.py
  dvc/repo/stage.py
  dvc/repo/status.py
  dvc/repo/update.py
  dvc/types.py
  tests/func/test_repo.py
  tests/func/test_stage.py
  tests/func/test_stage_load.py
  tests/unit/repo/test_repo.py
Labels: refactoring

#4994 stage: move is_cached logic to Stage.can_be_skipped
  dvc/repo/add.py
  dvc/repo/imp_url.py
  dvc/repo/run.py
  dvc/stage/__init__.py
Labels: refactoring, skip-changelog
