Repository iterative/dvc, pull requests merged in 2021-07, with the labels that each got.

#6220 separate validation and transformation of args from the add func
  dvc/repo/add.py
  dvc/utils/collections.py
  tests/unit/utils/test_collections.py
Labels: enhancement, refactoring

#6274 pygit: handle annotated tags in resolve_refish
  dvc/scm/git/backend/pygit2.py
  tests/unit/scm/test_git.py
Labels: bugfix

#6277 output: optimize obj collection
  dvc/fs/base.py
  dvc/fs/dvc.py
  dvc/fs/git.py
  dvc/fs/local.py
  dvc/fs/repo.py
  dvc/output.py
Labels: regression

#6239 add: do not delete stage files before add
  dvc/repo/add.py
  tests/func/test_add.py
Labels: enhancement, performance

#6197 `run`: update `-h` message
  dvc/command/experiments.py
Labels: skip-changelog

#6224 cleaning up add, progress bars and status
  dvc/repo/add.py
  dvc/stage/__init__.py
  dvc/ui/__init__.py
  tests/func/test_add.py
Labels: enhancement, refactoring, ui

#6280 ui: Prevent tqdm from breaking on output
  dvc/ui/__init__.py
Labels: bugfix, enhancement, ui

#6288 add: fix progress bar on single target
  dvc/progress.py
  dvc/repo/add.py
Labels: enhancement, ui

#6287 add: reduce os.fspath calls on recursive add
  dvc/repo/add.py
Labels: enhancement, refactoring

#6229 Fix #6205: Fixed diff summary to only show states with values.
  dvc/command/diff.py
  tests/unit/command/test_diff.py
Labels: ui

#6294 Fix typos discovered by codespell
  .pre-commit-config.yaml
  README.rst
  dvc/dagascii.py
  dvc/fs/azure.py
  dvc/fs/fsspec_wrapper.py
  dvc/repo/experiments/__init__.py
  dvc/scm/git/backend/base.py
  scripts/innosetup/setup.iss
  tests/func/plots/test_show.py
  tests/func/test_status.py
Labels: maintenance

#6273 doctor: show versions for fs requirements
  dvc/fs/http.py
  dvc/info.py
  setup.py
  tests/func/test_version.py
  tests/unit/test_info.py
Labels: skip-changelog

#6299 pkg: don't build universal wheels
  scripts/build_package.sh
  scripts/pypi_upload.sh
  setup.cfg
Labels: bugfix, build

#6195 objects: use separate staging ODB for staging trees
  dvc/checkout.py
  dvc/dependency/repo.py
  dvc/fs/dvc.py
  dvc/fs/local.py
  dvc/fs/memory.py
  dvc/objects/__init__.py
  dvc/objects/db/__init__.py
  dvc/objects/db/base.py
  dvc/objects/db/git.py
  dvc/objects/db/ssh.py
  dvc/objects/errors.py
  dvc/objects/stage.py
  dvc/objects/tree.py
  dvc/output.py
  dvc/remote/base.py
  dvc/repo/diff.py
  dvc/repo/fetch.py
  dvc/repo/gc.py
  dvc/scheme.py
  tests/func/test_commit.py
  tests/func/test_data_cloud.py
  tests/func/test_external_repo.py
  tests/func/test_remote.py
  tests/unit/objects/db/test_local.py
Labels: refactoring

#6286 add: ignore duplicated targets?
  dvc/repo/add.py
  dvc/ui/__init__.py
  tests/func/test_add.py
Labels: enhancement, ui

#6174 exp show: display running/queued state for experiments
  dvc/command/experiments.py
  dvc/compare.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/executor/local.py
  dvc/repo/experiments/show.py
  tests/func/experiments/test_show.py
Labels: A: experiments, enhancement, ui

#6309 fsspec: create directories on upload/upload_fobj
  dvc/fs/base.py
  dvc/fs/fsspec_wrapper.py
  dvc/fs/hdfs.py
  dvc/fs/local.py
  dvc/fs/ssh/__init__.py
  dvc/fs/webdav.py
  tests/func/test_fs.py
Labels: maintenance

#6308 objects: migrate remote push/pull to objects.transfer
  dvc/checkout.py
  dvc/data_cloud.py
  dvc/dependency/repo.py
  dvc/exceptions.py
  dvc/fs/dvc.py
  dvc/objects/db/__init__.py
  dvc/objects/db/base.py
  dvc/objects/db/index.py
  dvc/objects/db/slow_link_detection.py
  dvc/objects/stage.py
  dvc/objects/status.py
  dvc/objects/transfer.py
  dvc/objects/tree.py
  dvc/output.py
  dvc/remote/__init__.py
  dvc/remote/base.py
  dvc/remote/index.py
  dvc/remote/local.py
  dvc/repo/add.py
  dvc/repo/fetch.py
  dvc/repo/gc.py
  dvc/repo/imp_url.py
  dvc/repo/push.py
  dvc/repo/status.py
  dvc/stage/cache.py
  dvc/stage/imports.py
  dvc/state.py
  tests/func/objects/__init__.py
  tests/func/objects/db/__init__.py
  tests/func/objects/db/test_index.py
  tests/func/remote/test_index.py
  tests/func/test_checkout.py
  tests/func/test_data_cloud.py
  tests/func/test_external_repo.py
  tests/func/test_import.py
  tests/func/test_remote.py
  tests/func/test_update.py
  tests/unit/objects/db/test_local.py
  tests/unit/remote/test_index.py
  tests/unit/remote/test_remote_tree.py
  tests/unit/remote/test_slow_link_detection.py
  tests/unit/test_state.py
Labels: refactoring

#6343 update webdav4 to latest fsspec version
  setup.py
Labels: maintenance

#6344 do not print in style by default for errors
  dvc/ui/__init__.py
Labels: bugfix, ui

#6348 ci: temporarily mark gdrive xfail
  tests/func/test_data_cloud.py
Labels: ci, skip-changelog

#6358 fsspec: use rm_file()
  dvc/fs/fsspec_wrapper.py
  dvc/fs/oss.py
Labels: optimize

#6365 odb: use regular upload() when the source filesystem is local
  dvc/objects/db/base.py
  tests/func/objects/db/test_index.py
  tests/func/test_external_repo.py
  tests/func/test_import.py
  tests/func/test_remote.py
  tests/func/test_update.py
Labels: optimize

#6367 setup: relax aiobotocore requirements
  setup.py
Labels: fs: s3
