Repository iterative/dvc, pull requests merged in 2021-10, with the labels that each got.

#6723 Use latest pygit2 from master for 3.10
  .github/workflows/tests.yaml
Labels: p0-critical, testing, build, ci, skip-changelog

#6706 benedict: monkeypatch, performance improvements, bugfixes
  dvc/utils/_benedict.py
  dvc/utils/collections.py
  requirements/default.txt
  tests/unit/utils/test_collections.py
Labels: enhancement, A: experiments, skip-changelog, bugfix, optimize

#6724 deps: loose requirements for dataclasses and aiohttp-retry
  requirements/default.txt
Labels: skip-changelog, dependencies

#6716 exp init: introduce `--with={default,live}` flag
  dvc/command/experiments.py
Labels: ui, A: experiments, A: cli, A: pipelines

#6581 Move static metadata to setup.cfg
  setup.cfg
  setup.py
Labels: skip-changelog

#6727 setup: bump fsspec/s3fs/gcsfs
  requirements/default.txt
  requirements/gs.txt
  requirements/s3.txt
Labels: maintenance, fs: s3, fs: http, fs: gs

#6728 http: explicitly retry all http-related errors
  dvc/fs/http.py
Labels: fs: http

#6738 move exp init logic to dvc.repo.experiments.init
  dvc/command/experiments.py
  dvc/repo/experiments/init.py
Labels: refactoring, skip-changelog

#6739 exp init: only ask for that are not provided in an interactive mode
  dvc/repo/experiments/init.py
Labels: enhancement, A: experiments, skip-changelog

#6749 gha: benchmarks: fix pytest flags
  .github/workflows/benchmarks.yaml
Labels: :bug: bug, maintenance, skip-changelog, github_actions
