Repository iterative/dvc, pull requests merged in 2021-03, with the labels that each got.

#5532 exp: bash tab completion
  dvc/command/completion.py
  dvc/command/experiments.py
  tests/unit/command/test_experiments.py
Labels: skip-changelog, ui

#5543 exp diff: fix unresolved experiment names bug
  dvc/repo/experiments/diff.py
Labels: bugfix

#5544 repro/exp run: use git status when reminding to git-track files
  dvc/repo/reproduce.py
  dvc/scm/git/__init__.py
  tests/unit/scm/test_git.py
Labels: bugfix

#5545 dulwich: update to 0.20.20
  setup.py
Labels: skip-changelog

#5598 exp: subclass tempfile.TemporaryDirectory to handle cleanup
  dvc/repo/experiments/executor/local.py
Labels: skip-changelog

#5603 update pylint and pin dependencies
  .pylintrc
  setup.py
Labels: skip-changelog

#5602 http: fix info() if there is no content-length header
  dvc/fs/http.py
  tests/unit/remote/test_http.py
Labels: bugfix

#5601 Add a link to help debugging more information regarding the issue
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: skip-changelog

#5607 dvc: refactor objects
  dvc/api.py
  dvc/checkout.py
  dvc/dependency/repo.py
  dvc/dir_info.py
  dvc/fs/dvc.py
  dvc/fs/memory.py
  dvc/hash_info.py
  dvc/objects/__init__.py
  dvc/objects/stage.py
  dvc/objects/tree.py
  dvc/output/base.py
  dvc/repo/__init__.py
  dvc/repo/diff.py
  dvc/repo/fetch.py
  tests/func/remote/test_index.py
  tests/func/test_add.py
  tests/func/test_checkout.py
  tests/func/test_data_cloud.py
  tests/func/test_external_repo.py
  tests/func/test_remote.py
  tests/unit/fs/test_dvc.py
  tests/unit/fs/test_repo.py
  tests/unit/objects/__init__.py
  tests/unit/objects/test_tree.py
  tests/unit/output/test_local.py
Labels: refactoring, skip-changelog

#5609 objects: split into separate files
  dvc/checkout.py
  dvc/objects/__init__.py
  dvc/objects/db/base.py
  dvc/objects/db/local.py
  dvc/objects/errors.py
  dvc/objects/file.py
  dvc/objects/stage.py
  dvc/objects/transfer.py
  dvc/objects/tree.py
  dvc/output/base.py
  dvc/remote/base.py
  dvc/repo/add.py
  tests/func/test_odb.py
  tests/unit/objects/test_tree.py
Labels: refactoring, skip-changelog

#5584 plots: support opening plots file directly in the browser
  dvc/command/plots.py
  tests/unit/command/test_plots.py
Labels: feature

#5596 repro/exp run: revert use git status when reminding to git-track files
  dvc/scm/git/__init__.py
  tests/unit/scm/test_git.py
Labels: performance

#5600 exp run: do nothing if result matches parent (HEAD)
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor/base.py
Labels: bugfix

#5611 exp run: fix issue where duplicate workspace runs would incorrectly conflict
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor/base.py
Labels: bugfix

#5652 diff: clear calculated renamed files from inverted hashmap
  dvc/repo/diff.py
  tests/func/test_diff.py
Labels: bugfix

#5673 Update pylint-pytest to 1.0.3
  setup.py
Labels: maintenance, skip-changelog

#5682 build: upgrade pyinstaller to 4.2
  .github/workflows/packages.yaml
  scripts/build-requirements.txt
  scripts/pyinstaller/hooks/hook-googleapiclient.model.py
Labels: build

#5653 ui: use global singleton UI object for printing
  dvc/command/status.py
  dvc/main.py
  dvc/ui/__init__.py
Labels: discussion, ui

#5670 plots: quote and resolve paths properly
  dvc/command/plots.py
  tests/func/plots/test_show.py
  tests/unit/command/test_plots.py
Labels: bugfix

#5687 build: osxpkg: build lxml
  .github/workflows/packages.yaml
Labels: build

#5674 Move tests requirements to test_requirements.txt
  setup.py
  test_requirements.txt
Labels: build

#5697 Add dependabot to update github-actions and python requirements
  .github/dependabot.yml
  .github/workflows/tests.yaml
Labels: build, ci

#5713 test requirements: remove pytest-tap
  .github/workflows/tests.yaml
  test_requirements.txt
Labels: dependencies

#5714 dependencies: pin urllib3 to 1.26.4
  test_requirements.txt
Labels: dependencies

#5716 dvc: update precommit hooks
  .pre-commit-config.yaml
  dvc/fs/ssh/connection.py
  dvc/utils/table.py
Labels: maintenance

#5723 deps: limit rich version to <10
  setup.py
Labels: dependencies

#5724 Add test_requirements.txt to the manifest
  MANIFEST.in
Labels: build, skip-changelog

#5729 ui: Use sys.stdout and sys.stderr dynamically
  dvc/ui/__init__.py
  tests/conftest.py
  tests/unit/ui/__init__.py
  tests/unit/ui/test_console.py
Labels: enhancement, testing, ui

#5734 parsing: resolve relative paths when loading parameters
  dvc/parsing/context.py
  tests/func/parsing/test_resolver.py
Labels: bugfix

#5745 dvcignore: ignore file '.git' by default
  dvc/ignore.py
  tests/func/test_ignore.py
Labels: bugfix

#5742 webdav: use root url to check and on mkdir to find recurse depth
  dvc/fs/webdav.py
Labels: bugfix

#5741 status: collect stages only once
  dvc/command/status.py
  tests/unit/command/test_status.py
Labels: optimize
