Repository iterative/dvc, pull requests merged in 2021-01, with the labels that each got.

#4902 live logs initial
  dvc/api/__init__.py
  dvc/api/live.py
  dvc/cli.py
  dvc/command/live.py
  dvc/command/plots.py
  dvc/command/run.py
  dvc/env.py
  dvc/exceptions.py
  dvc/output/__init__.py
  dvc/output/base.py
  dvc/repo/__init__.py
  dvc/repo/collect.py
  dvc/repo/live.py
  dvc/repo/metrics/show.py
  dvc/repo/plots/__init__.py
  dvc/repo/plots/data.py
  dvc/repo/reproduce.py
  dvc/repo/run.py
  dvc/schema.py
  dvc/stage/__init__.py
  dvc/stage/loader.py
  dvc/stage/params.py
  dvc/stage/run.py
  dvc/stage/serialize.py
  dvc/stage/utils.py
  dvc/utils/html.py
  tests/func/api/__init__.py
  tests/func/api/test_api.py
  tests/func/api/test_live.py
  tests/func/plots/test_modify.py
  tests/func/plots/test_show.py
  tests/func/plots/utils.py
  tests/func/test_live.py
  tests/unit/command/test_live.py
  tests/unit/command/test_run.py
  tests/utils/__init__.py
Labels: feature

#5197 Reraise exception after pdb.post_mortem()
  dvc/_debug.py
Labels: bugfix

#5195 experiments: fix logging bugs
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/executor/local.py
  dvc/repo/reproduce.py
  dvc/scm/git/__init__.py
Labels: bugfix, skip-changelog, ui

#5202 debug functions: have a good default value
  dvc/_debug.py
Labels: maintenance

#5203 scm: lazily load Git backends
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/pygit2.py
Labels: optimize, skip-changelog

#5201 add: handle long filenames
  dvc/tree/local.py
  tests/func/test_add.py
Labels: backport-1.11

#5205 diff: account for deleted workspace data
  dvc/repo/diff.py
  tests/func/test_diff.py
Labels: bugfix, skip-changelog

#5210 analytics: lazily import
  dvc/analytics.py
Labels: optimize, performance, skip-changelog

#5128 Add versioning scheme in the dvc.lock
  dvc/dvcfile.py
  dvc/parsing/versions.py
  dvc/schema.py
  dvc/stage/loader.py
  tests/func/test_dvcfile.py
  tests/func/test_lockfile.py
  tests/func/test_repro_multistage.py
  tests/func/test_run_multistage.py
  tests/unit/stage/test_serialize_pipeline_lock.py
  tests/unit/test_lockfile.py
Labels: breaking-change, enhancement

#5212 package: Increment shtab's version
  setup.py
Labels: performance, skip-changelog

#5211 config command: lazily import
  dvc/command/config.py
Labels: optimize, performance, skip-changelog

#5214 Move misc. imports from command, make them lazy
  dvc/command/add.py
  dvc/command/dag.py
  dvc/command/experiments.py
  dvc/command/repro.py
  dvc/command/version.py
  dvc/dvcfile.py
  dvc/exceptions.py
  dvc/utils/flatten.py
Labels: optimize, performance, skip-changelog

#5215 Misc imports lazy
  dvc/command/plots.py
  dvc/command/remote.py
  dvc/repo/__init__.py
Labels: optimize, performance, skip-changelog

#5220 repo.tree: make imports lazy
  dvc/external_repo.py
  dvc/repo/__init__.py
  dvc/repo/diff.py
  dvc/tree/repo.py
Labels: optimize, performance, skip-changelog

#5221 lazy imports on misc. repo command
  dvc/exceptions.py
  dvc/repo/add.py
  dvc/repo/brancher.py
  dvc/repo/commit.py
  dvc/repo/get_url.py
  dvc/repo/reproduce.py
  dvc/repo/run.py
  dvc/repo/update.py
  dvc/updater.py
Labels: optimize, performance, skip-changelog

#5218 Misc. imports made lazy: scm,experiments,stage
  dvc/repo/experiments/__init__.py
  dvc/scm/git/__init__.py
  dvc/stage/__init__.py
  dvc/stage/utils.py
Labels: optimize, performance, skip-changelog

#5219 Make some imports lazy for plots
  dvc/repo/collect.py
  dvc/repo/plots/__init__.py
  dvc/repo/plots/template.py
Labels: optimize, performance, skip-changelog

#5217 parametrization: do not load parser on import
  dvc/parsing/interpolate.py
Labels: optimize, parametrization, performance, skip-changelog

#5222 Use 'schema' top-level element in the lockfile for version
  dvc/dvcfile.py
  dvc/parsing/versions.py
  dvc/schema.py
  tests/func/test_lockfile.py
  tests/func/test_run_multistage.py
  tests/unit/test_lockfile.py
Labels: bugfix

#5224 utils.serialize: lazy imports
  dvc/utils/serialize/_common.py
  dvc/utils/serialize/_toml.py
  dvc/utils/serialize/_yaml.py
Labels: performance, refactoring, skip-changelog

#5226 cmd: imports lazy
  dvc/command/check_ignore.py
  dvc/command/checkout.py
  dvc/command/commit.py
  dvc/command/data_sync.py
  dvc/command/destroy.py
  dvc/command/diff.py
Labels: optimize, performance, skip-changelog

#5225 parsing: make imports lazy
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/parsing/interpolate.py
Labels: performance, refactoring, skip-changelog

#5227 Make imports on dvc.repo and dvc.repo.plots lazy
  dvc/repo/__init__.py
  dvc/repo/fetch.py
  dvc/repo/get.py
  dvc/repo/live.py
  dvc/repo/plots/__init__.py
  dvc/repo/run.py
  dvc/repo/stage.py
Labels: performance, refactoring, skip-changelog

#5228 Misc. imports lazy on utils,stage.cache and dvc.*
  dvc/_debug.py
  dvc/data_cloud.py
  dvc/rwlock.py
  dvc/stage/cache.py
  dvc/state.py
  dvc/utils/__init__.py
  dvc/utils/fs.py
  dvc/utils/html.py
Labels: optimize, performance, skip-changelog

#5229 Split config and schema
  dvc/cache/__init__.py
  dvc/config.py
  dvc/config_schema.py
  dvc/tree/__init__.py
Labels: optimize, performance, skip-changelog

#5233 Make few imports lazy on dvc.main
  dvc/main.py
Labels: optimize, performance, skip-changelog

#5237 fix mypy errors; add mypy precommit hooks
  .pre-commit-config.yaml
  dvc/repo/add.py
  dvc/repo/params/show.py
  dvc/repo/plots/__init__.py
  dvc/stage/__init__.py
  dvc/types.py
  dvc/utils/collections.py
  setup.cfg
Labels: ci

#5234 erepo: refactor download/fetch logic
  dvc/cache/base.py
  dvc/dependency/repo.py
  dvc/external_repo.py
  dvc/repo/fetch.py
  dvc/repo/get.py
  dvc/tree/base.py
  dvc/tree/repo.py
  dvc/utils/__init__.py
  tests/func/test_external_repo.py
  tests/func/test_get.py
  tests/func/test_get_url.py
  tests/func/test_import.py
  tests/func/test_import_url.py
  tests/func/test_repro.py
  tests/unit/test_external_repo.py
  tests/unit/tree/test_repo.py
Labels: skip-changelog

#5240 s3: Allow authentication using session token
  dvc/config_schema.py
  dvc/tree/s3.py
  tests/unit/tree/test_s3.py
Labels: feature

#5243 scm: implement gitignore
  dvc/repo/__init__.py
  dvc/scm/base.py
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/backend/pygit2.py
  tests/func/test_scm.py
Labels: enhancement, performance, skip-changelog

#5250 dvc: bump to 2.0.0a0
  dvc/version.py
Labels: major, skip-changelog

#5245 git: implement merge/checkout via pygit2
  .pylintrc
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/apply.py
  dvc/repo/experiments/executor/base.py
  dvc/scm/base.py
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/backend/pygit2.py
  tests/unit/scm/test_git.py
Labels: maintenance, skip-changelog

#5258 experiments: exp res bug fixes
  dvc/repo/experiments/__init__.py
  dvc/repo/reproduce.py
Labels: bugfix, experiments, skip-changelog

#5259 move parsing params to utils
  dvc/repo/experiments/run.py
  dvc/repo/run.py
  dvc/utils/cli_parse.py
  dvc/utils/collections.py
  tests/unit/test_run.py
  tests/unit/utils/test_cli_parse.py
  tests/unit/utils/test_collections.py
Labels: enhancement, refactoring, skip-changelog

#5260 system: prevent mypy from checking windows-related method
  dvc/system.py
Labels: maintenance, skip-changelog

#5262 refactor run; move to stage.utils
  dvc/dvcfile.py
  dvc/repo/experiments/run.py
  dvc/repo/run.py
  dvc/stage/__init__.py
  dvc/stage/utils.py
  dvc/utils/cli_parse.py
  tests/unit/test_run.py
  tests/unit/utils/test_cli_parse.py
Labels: enhancement, refactoring

#5187 dvc: redefine is_callback as cmd and no outs/deps
  dvc/stage/__init__.py
  dvc/stage/run.py
  tests/func/test_lockfile.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_run_single_stage.py
  tests/unit/stage/test_run.py
Labels: breaking-change

#5272 tests: upgrade azurite and enable loose mode
  tests/docker-compose.yml
  tests/func/test_tree.py
Labels: bug, skip-changelog, testing

#5271 dvc: move protect from tree to cache
  dvc/cache/base.py
  dvc/cache/local.py
  dvc/output/base.py
  dvc/remote/base.py
  dvc/repo/__init__.py
  dvc/tree/base.py
  dvc/tree/local.py
  tests/func/test_add.py
  tests/unit/cache/test_local.py
  tests/unit/tree/test_tree.py
Labels: refactoring, skip-changelog

#5277 hdfs: copy: don't read everything into memory
  dvc/tree/hdfs.py
  dvc/tree/webhdfs.py
Labels: backport-1.11, bug

#5263 introduce stage:add command
  dvc/cli.py
  dvc/command/run.py
  dvc/command/stage.py
  dvc/repo/run.py
  dvc/stage/utils.py
  tests/func/test_live.py
  tests/unit/command/test_run.py
  tests/unit/command/test_stage.py
Labels: enhancement, feature

#5257 checkpoints/live: move execution env to stage
  dvc/output/base.py
  dvc/stage/__init__.py
  dvc/stage/run.py
Labels: refactoring, skip-changelog

#5281 use `repo.stage.create_from_cli` to create stages
  dvc/command/stage.py
  dvc/repo/__init__.py
  dvc/repo/add.py
  dvc/repo/run.py
  dvc/repo/stage.py
  dvc/stage/utils.py
  tests/unit/command/test_stage.py
Labels: refactoring

#5270 scm: implement pygit2 resolve rev and native checkout
  dvc/repo/experiments/apply.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/backend/pygit2.py
  tests/func/test_install.py
  tests/unit/scm/test_git.py
Labels: maintenance, skip-changelog

#5282 Introduce stage:list command with autocompletions
  dvc/command/completion.py
  dvc/command/repro.py
  dvc/command/stage.py
  dvc/repo/__init__.py
  dvc/repo/stage.py
  dvc/stage/__init__.py
Labels: enhancement, feature

#5294 pylint: enable no-else-return
  .pylintrc
  dvc/cache/base.py
  dvc/command/experiments.py
  dvc/ignore.py
  dvc/parsing/context.py
  dvc/parsing/interpolate.py
  dvc/pathspec_math.py
  dvc/repo/plots/data.py
  dvc/repo/stage.py
  dvc/scm/git/backend/gitpython.py
  tests/func/test_repro.py
Labels: skip-changelog

#5295 erepo: separate caching and repo
  dvc/external_repo.py
Labels: refactoring, skip-changelog

#5296 erepo: move misc stuff out of erepo
  dvc/external_repo.py
  dvc/repo/__init__.py
Labels: refactoring, skip-changelog

#5298 checkout: don't filter hash if it is a file
  dvc/cache/base.py
  tests/func/test_checkout.py
Labels: bug, skip-changelog

#5299 Fix code-style issues in the parsing module
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/parsing/interpolate.py
Labels: refactoring, skip-changelog

#5306 reqs: tests: remove awscli
  setup.py
Labels: skip-changelog

#5309 dvc: get rid of ExternalRepo
  dvc/external_repo.py
  dvc/repo/__init__.py
  dvc/tree/repo.py
  tests/unit/test_external_repo.py
  tests/unit/tree/test_repo.py
Labels: bugfix, refactoring, skip-changelog

#5314 dvc: refactor cache saving
  dvc/cache/base.py
  dvc/cache/local.py
  dvc/exceptions.py
  dvc/remote/base.py
  dvc/stage/cache.py
  dvc/tree/base.py
  dvc/tree/local.py
  dvc/tree/ssh/__init__.py
  dvc/tree/webdav.py
  dvc/tree/webhdfs.py
  dvc/utils/fs.py
  tests/func/test_cache.py
  tests/unit/stage/test_cache.py
  tests/unit/tree/test_tree.py
Labels: refactoring, skip-changelog

#5319 hash_info: add __str__
  dvc/hash_info.py
Labels: skip-changelog, ui

#5290 show `git-add` hint on `stage:add`, refactor scm_context
  dvc/command/stage.py
  dvc/repo/scm_context.py
  dvc/scm/base.py
  tests/unit/scm/test_git.py
  tests/unit/scm/test_scm.py
Labels: enhancement

#5323 repo: remove unused find_out_by_relpath
  dvc/repo/__init__.py
Labels: refactoring, skip-changelog

#5329 exp show: cleanup data column handling
  dvc/command/experiments.py
Labels: bugfix, skip-changelog, ui

#5333 tests: limit pytest version by <6.2.2
  setup.py
Labels: skip-changelog, testing

#5334 dvc: move 'verify' property from tree to cache
  dvc/cache/__init__.py
  dvc/cache/base.py
  dvc/cache/gdrive.py
  dvc/remote/base.py
  dvc/tree/base.py
  dvc/tree/gdrive.py
Labels: refactoring, skip-changelog

#5351 experiments: drop `exp resume` in favor of auto-resuming in `exp run`
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/run.py
  tests/func/experiments/conftest.py
  tests/func/experiments/test_checkpoints.py
  tests/unit/command/test_experiments.py
Labels: experiments, ui
