Repository iterative/dvc, pull requests merged in 2021-12, with the labels that each got.

#7077 tests: introduce dvc.testing
  dvc/testing/__init__.py
  dvc/testing/cloud.py
  dvc/testing/conftest.py
  dvc/testing/fixtures.py
  dvc/testing/path_info.py
  dvc/testing/test_api.py
  dvc/testing/test_remote.py
  dvc/testing/test_workspace.py
  dvc/testing/tmp_dir.py
  setup.cfg
  tests/conftest.py
  tests/dir_helpers.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_remote.py
  tests/func/experiments/test_remove.py
  tests/func/test_add.py
  tests/func/test_api.py
  tests/func/test_data_cloud.py
  tests/func/test_gc.py
  tests/func/test_ignore.py
  tests/func/test_import_url.py
  tests/func/test_merge_driver.py
  tests/func/test_run_multistage.py
  tests/func/test_update.py
  tests/remotes/__init__.py
  tests/remotes/azure.py
  tests/remotes/gdrive.py
  tests/remotes/gs.py
  tests/remotes/hdfs.py
  tests/remotes/http.py
  tests/remotes/local.py
  tests/remotes/oss.py
  tests/remotes/s3.py
  tests/remotes/ssh.py
  tests/remotes/webdav.py
  tests/remotes/webhdfs.py
Labels: refactoring, testing, skip-changelog

#7087 tests: remove redundant remote tests
  dvc/repo/experiments/__init__.py
  dvc/testing/fixtures.py
  dvc/testing/test_workspace.py
  setup.cfg
  tests/docker-compose.yml
  tests/func/experiments/executor/test_ssh.py
  tests/func/test_add.py
  tests/func/test_api.py
  tests/func/test_checkout.py
  tests/func/test_data_cloud.py
  tests/func/test_fs.py
  tests/func/test_gc.py
  tests/func/test_import_url.py
  tests/func/test_merge_driver.py
  tests/func/test_remote.py
  tests/func/test_run_multistage.py
  tests/func/test_scm.py
  tests/func/test_update.py
  tests/remotes/__init__.py
  tests/remotes/azure.py
  tests/remotes/gdrive.py
  tests/remotes/git_server.py
  tests/remotes/gs.py
  tests/remotes/hdfs.py
  tests/remotes/http.py
  tests/remotes/local.py
  tests/remotes/oss.py
  tests/remotes/s3.py
  tests/remotes/ssh.py
  tests/remotes/webdav.py
  tests/remotes/webhdfs.py
  tests/unit/fs/test_s3.py
  tests/unit/remote/test_http.py
  tests/unit/remote/test_remote_tree.py
  tests/utils/httpd.py
Labels: refactoring, testing, skip-changelog

#7090 gha: remove remote leftovers
  .github/workflows/tests.yaml
Labels: skip-changelog, github_actions

#7091 ci: fix ci failure
  tests/unit/proc/test_manager.py
Labels: ci, skip-changelog

#7075 render: image: make html less ugly
  dvc/render/image.py
Labels: enhancement, A: plots

#7067 proc: implement cleanup/removal (#7063)
  dvc/proc/manager.py
  tests/unit/proc/test_manager.py
Labels: skip-changelog, A: executors

#6912 plots: revert templates in packages change
  dvc/repo/plots/__init__.py
  dvc/repo/plots/template.py
  tests/unit/render/test_vega.py
Labels: skip-changelog, A: plots

#7097 odb: make some listing methods private
  dvc/objects/db/base.py
  tests/unit/remote/test_base.py
Labels: refactoring, skip-changelog

#7099 setup: bump scmrepo
  setup.cfg
Labels: skip-changelog

#7098 exp init: change type to --type=live to --type=dl
  dvc/command/experiments.py
  dvc/repo/experiments/init.py
  tests/func/experiments/test_init.py
  tests/unit/command/test_experiments.py
Labels: enhancement, A: experiments, skip-changelog

#7104 exp init: minor refactoring
  dvc/command/experiments.py
  dvc/repo/experiments/init.py
  tests/unit/command/test_experiments.py
Labels: A: experiments, skip-changelog, A: cli

#7106 exp init: unhide from `dvc exp --help`
  dvc/command/experiments.py
Labels: enhancement, A: experiments, skip-changelog, A: cli

#7111 fs: path: use ntpath/posixpath
  dvc/fs/path.py
Labels: enhancement, skip-changelog

#7117 setup: bump gcsfs
  setup.cfg
Labels: dependencies, fs: oss, fs: s3, fs: gs

#7121 fs: get rid of CHECKSUM_DIR_SUFFIX and is_dir_hash
  dvc/fs/base.py
  dvc/objects/db/__init__.py
  dvc/objects/db/base.py
  dvc/objects/db/index.py
  tests/unit/remote/test_base.py
  tests/unit/remote/test_index.py
Labels: refactoring, skip-changelog

#7123 fs: get rid of unused DETAIL_FIELDS
  dvc/fs/azure.py
  dvc/fs/base.py
  dvc/fs/gs.py
  dvc/fs/oss.py
  dvc/fs/s3.py
  dvc/fs/webdav.py
Labels: refactoring, skip-changelog

#7134 tests: remove func.test_scm
  tests/func/test_scm.py
Labels: testing, skip-changelog

#7135 exp: split exp sub command (#5489)
  dvc/command/experiments.py
  dvc/command/experiments/__init__.py
  dvc/command/experiments/apply.py
  dvc/command/experiments/branch.py
  dvc/command/experiments/diff.py
  dvc/command/experiments/gc.py
  dvc/command/experiments/init.py
  dvc/command/experiments/ls.py
  dvc/command/experiments/pull.py
  dvc/command/experiments/push.py
  dvc/command/experiments/remove.py
  dvc/command/experiments/run.py
  dvc/command/experiments/show.py
  tests/func/experiments/test_init.py
  tests/unit/command/test_experiments.py
Labels: refactoring, A: experiments, skip-changelog

#7146 tests: get rid of GitFS related tests
  tests/basic_env.py
  tests/func/test_fs.py
Labels: testing, skip-changelog

#7172 s3: remove explicit dependency on aiobotocore; simplify constraints
  setup.cfg
Labels: skip-changelog, dependencies

#7189 fs.hdfs: skip port if not available
  dvc/fs/hdfs.py
  tests/unit/fs/test_hdfs.py
Labels: :bug: bug, p0-critical, fs: hdfs

#7178 deps: remove requests-kerberos from `webdhfs`; provide it via `webdhfs_kerberos`.
  setup.cfg
Labels: dependencies

#7179 deps: explicitly specify pyarrow for hdfs
  setup.cfg
Labels: dependencies

#7195 odb: move verify option to config
  dvc/config_schema.py
  dvc/objects/db/__init__.py
  dvc/objects/db/gdrive.py
  dvc/objects/db/oss.py
  tests/func/test_config.py
  tests/func/test_remote.py
Labels: refactoring, skip-changelog

#7197 fs: remove unused RemoteCmdError
  dvc/fs/base.py
  tests/unit/remote/test_base.py
Labels: refactoring, skip-changelog

#7214 repo: use fs instead of scm
  dvc/external_repo.py
  dvc/fs/repo.py
  dvc/repo/__init__.py
  tests/unit/repo/test_repo.py
  tests/unit/test_external_repo.py
Labels: refactoring, skip-changelog

#7216 config: remove useless os.path.join
  dvc/config.py
Labels: refactoring, skip-changelog
