Repository iterative/dvc, pull requests merged in 2021-02, with the labels that each got.

#5373 don't allow loading stages without `cmd`
  dvc/schema.py
  dvc/stage/serialize.py
  tests/conftest.py
  tests/unit/command/test_status.py
Labels: bugfix, parametrization

#5365 cache pip directory on github actions
  .github/workflows/tests.yaml
Labels: ci, skip-changelog

#5363 params: support unicode characters
  dvc/dvcfile.py
  tests/unit/test_params.py
Labels: backport-1.11

#5350 stage:add: use remainder as a command script
  dvc/command/run.py
  dvc/command/stage.py
  tests/func/test_cli.py
  tests/unit/command/test_stage.py
Labels: bugfix, skip-changelog

#5360 exp apply: force apply by default
  dvc/command/experiments.py
  dvc/repo/experiments/apply.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_gc.py
  tests/func/experiments/test_show.py
  tests/unit/command/test_experiments.py
Labels: skip-changelog, ui

#5361 exp show: cleanup UI issues
  dvc/command/experiments.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/show.py
  tests/func/experiments/test_show.py
  tests/unit/command/test_experiments.py
Labels: skip-changelog, ui

#5382 keep stage.dump() and dvcfile.dump() in sync
  dvc/command/stage.py
  dvc/stage/__init__.py
  tests/unit/test_params.py
Labels: refactoring, skip-changelog

#5386 tests: mock global config dir for Updater
  dvc/config.py
  tests/unit/test_analytics.py
  tests/unit/test_updater.py
Labels: skip-changelog, testing

#5393 repo: remove unneeded filter
  dvc/repo/trie.py
Labels: skip-changelog

#5401 api: use Repo.open
  dvc/api/__init__.py
  dvc/repo/__init__.py
Labels: refactoring, skip-changelog

#5403 tree: stop using self.path_info outside of __init__
  dvc/tree/azure.py
  dvc/tree/gdrive.py
  dvc/tree/http.py
  dvc/tree/oss.py
  dvc/tree/webdav.py
  dvc/tree/webhdfs.py
Labels: refactoring, skip-changelog

#5407 experiments: bug fixes
  dvc/command/experiments.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_show.py
Labels: bugfix, skip-changelog, ui

#5408 exp gc: prune any exp/exec refs which point to gc'd experiments
  dvc/repo/experiments/gc.py
Labels: bugfix, skip-changelog

#5411 refactor webdav to use client; extract write_text to base remote fixture
  tests/remotes/azure.py
  tests/remotes/base.py
  tests/remotes/gs.py
  tests/remotes/hdfs.py
  tests/remotes/http.py
  tests/remotes/s3.py
  tests/remotes/ssh.py
  tests/remotes/webdav.py
  tests/remotes/webhdfs.py
Labels: skip-changelog, testing

#5412 cache: generalize save and checkout
  dvc/cache/base.py
  dvc/cache/local.py
  dvc/dependency/repo.py
  dvc/output/base.py
  dvc/tree/ssh/__init__.py
  tests/func/test_run_cache.py
  tests/unit/stage/test_cache.py
Labels: refactoring, skip-changelog

#5415 dvc: move checkout out of cache
  dvc/cache/base.py
  dvc/cache/local.py
  dvc/checkout.py
  dvc/dependency/repo.py
  dvc/output/base.py
  tests/func/test_run_cache.py
  tests/unit/stage/test_cache.py
Labels: refactoring, skip-changelog

#5414 pygit2, gitpython: handle relpaths in reset/checkout_index backends
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/backend/pygit2.py
  tests/unit/scm/test_git.py
Labels: bugfix, p0-critical, skip-changelog

#5280 term: replace 'DVC-file' and 'stage file' with correct terms (#3960)
  dvc/command/add.py
  dvc/command/commit.py
  dvc/command/destroy.py
  dvc/command/imp.py
  dvc/command/imp_url.py
  dvc/command/move.py
  dvc/command/remove.py
  dvc/command/repro.py
  dvc/command/run.py
  dvc/command/update.py
  dvc/dependency/base.py
  dvc/dvcfile.py
  dvc/exceptions.py
  dvc/output/base.py
  dvc/repo/add.py
  dvc/repo/get.py
  dvc/repo/move.py
  dvc/stage/__init__.py
  dvc/stage/exceptions.py
  dvc/stage/utils.py
  tests/func/test_add.py
  tests/func/test_merge_driver.py
Labels: awaiting response

#5420 git: update dulwich dependency to 0.20.18
  setup.py
Labels: skip-changelog

#5421 cache: use add() to add objects to cache
  dvc/cache/base.py
Labels: refactoring, skip-changelog

#5423 utils: don't use unnecessary exists() calls
  dvc/checkout.py
  dvc/tree/local.py
  dvc/tree/repo.py
  dvc/utils/__init__.py
  tests/func/test_add.py
  tests/func/test_install.py
  tests/func/test_repro.py
  tests/func/test_run_single_stage.py
  tests/func/test_state.py
  tests/func/test_utils.py
  tests/unit/utils/test_stream.py
Labels: optimize, refactoring, skip-changelog

#5425 exp: cleanup executor temp directories ourselves
  dvc/repo/experiments/executor/local.py
Labels: ci, skip-changelog

#5397 stage: implement add/create methods in stage loader
  dvc/command/stage.py
  dvc/repo/run.py
  dvc/repo/stage.py
  dvc/stage/utils.py
  dvc/utils/cli_parse.py
  tests/conftest.py
  tests/unit/command/test_stage.py
  tests/unit/test_metrics.py
  tests/unit/test_params.py
  tests/unit/test_plots.py
  tests/unit/utils/test_cli_parse.py
Labels: refactoring, skip-changelog

#5424 dvc: introduce File/Tree cache objects
  dvc/cache/base.py
  dvc/cache/local.py
  dvc/checkout.py
  dvc/dependency/repo.py
  dvc/objects.py
  dvc/output/base.py
  dvc/repo/fetch.py
  dvc/tree/base.py
  dvc/tree/dvc.py
  dvc/tree/memory.py
  setup.py
  tests/func/test_add.py
  tests/func/test_cache.py
  tests/func/test_checkout.py
  tests/func/test_commit.py
  tests/func/test_external_repo.py
  tests/unit/output/test_local.py
  tests/unit/test_external_repo.py
  tests/unit/tree/test_dvc.py
  tests/unit/tree/test_repo.py
Labels: refactoring, skip-changelog

#5430 cache: move save() to objects
  dvc/cache/base.py
  dvc/dependency/repo.py
  dvc/objects.py
  dvc/output/base.py
  dvc/repo/fetch.py
  tests/func/test_external_repo.py
  tests/unit/test_external_repo.py
Labels: refactoring, skip-changelog

#5431 cache: add: accept object id and it's path
  dvc/cache/base.py
  dvc/objects.py
Labels: refactoring, skip-changelog

#5426 exp run: clean untracked lockfiles before running
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor/base.py
Labels: bugfix, experiments, skip-changelog

#5381 exp show: customize rich table rendering behavior
  dvc/command/experiments.py
  dvc/utils/pager.py
  dvc/utils/table.py
  setup.py
Labels: skip-changelog, ui

#5439 cache: move unrelated helpers out of CloudCache class
  dvc/cache/base.py
  dvc/cache/local.py
  dvc/checkout.py
  dvc/objects.py
  dvc/remote/base.py
  dvc/repo/add.py
  dvc/system.py
  dvc/tree/local.py
  dvc/utils/fs.py
  tests/func/test_add.py
  tests/func/test_s3.py
Labels: refactoring, skip-changelog

#5443 exp: add `exp remove` command
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/gc.py
  dvc/repo/experiments/remove.py
  dvc/repo/experiments/utils.py
  tests/func/experiments/test_experiments.py
  tests/unit/command/test_experiments.py
Labels: experiments, ui

#5442 exp run: remove `exp reset` in favor of `exp run --reset`
  dvc/command/experiments.py
  tests/unit/command/test_experiments.py
Labels: ui

#5447 cache: misc cleanups
  dvc/cache/base.py
  dvc/cache/local.py
  dvc/cache/ssh.py
  dvc/checkout.py
  dvc/data_cloud.py
  dvc/objects.py
  dvc/output/base.py
  dvc/remote/base.py
  dvc/tree/base.py
  dvc/tree/dvc.py
  tests/func/test_cache.py
  tests/func/test_checkout.py
  tests/func/test_gc.py
  tests/func/test_remote.py
Labels: refactoring, skip-changelog

#5441 tests: use -n=auto and --dist loadscope
  .github/workflows/tests.yaml
  tests/__main__.py
Labels: skip-changelog, testing

#5448 output: handle missing hash_info.nfiles
  dvc/output/base.py
  tests/func/test_checkout.py
Labels: skip-changelog

#5348 introduce dvc.io module to consolidate io utilities
  dvc/ui/__init__.py
  dvc/utils/__init__.py
Labels: skip-changelog, ui

#5452 tree: get_hash: accept explicit hash name
  dvc/api/__init__.py
  dvc/checkout.py
  dvc/dependency/repo.py
  dvc/objects.py
  dvc/output/base.py
  dvc/repo/diff.py
  dvc/tree/azure.py
  dvc/tree/base.py
  dvc/tree/dvc.py
  dvc/tree/gdrive.py
  dvc/tree/gs.py
  dvc/tree/hdfs.py
  dvc/tree/http.py
  dvc/tree/local.py
  dvc/tree/memory.py
  dvc/tree/repo.py
  dvc/tree/s3.py
  dvc/tree/ssh/__init__.py
  dvc/tree/webdav.py
  dvc/tree/webhdfs.py
  tests/func/test_remote.py
  tests/func/test_tree.py
  tests/unit/remote/test_azure.py
  tests/unit/remote/test_remote_tree.py
  tests/unit/tree/test_dvc.py
  tests/unit/tree/test_repo.py
Labels: refactoring, skip-changelog

#5453 metrics/params: fix bug preventing usage from being displayed
  dvc/command/metrics.py
  dvc/command/params.py
Labels: skip-changelog

#5460 tree: move get_hash to object id logic
  dvc/api/__init__.py
  dvc/checkout.py
  dvc/dependency/repo.py
  dvc/objects.py
  dvc/oid.py
  dvc/output/base.py
  dvc/repo/diff.py
  dvc/tree/azure.py
  dvc/tree/base.py
  dvc/tree/dvc.py
  dvc/tree/gdrive.py
  dvc/tree/git.py
  dvc/tree/gs.py
  dvc/tree/hdfs.py
  dvc/tree/http.py
  dvc/tree/local.py
  dvc/tree/memory.py
  dvc/tree/repo.py
  dvc/tree/s3.py
  dvc/tree/ssh/__init__.py
  dvc/tree/ssh/connection.py
  dvc/tree/webdav.py
  dvc/tree/webhdfs.py
  dvc/utils/__init__.py
  tests/func/test_add.py
  tests/func/test_data_cloud.py
  tests/func/test_install.py
  tests/func/test_remote.py
  tests/func/test_repro.py
  tests/func/test_run_single_stage.py
  tests/func/test_state.py
  tests/func/test_tree.py
  tests/func/test_utils.py
  tests/unit/remote/test_azure.py
  tests/unit/remote/test_remote_tree.py
  tests/unit/tree/test_dvc.py
  tests/unit/tree/test_repo.py
  tests/unit/utils/test_stream.py
  tests/unit/utils/test_utils.py
Labels: refactoring, skip-changelog

#5462 fs/outs/deps: remove supported() logic
  dvc/dependency/__init__.py
  dvc/fs/__init__.py
  dvc/fs/base.py
  dvc/info.py
  dvc/output/__init__.py
  dvc/output/base.py
Labels: refactoring, skip-changelog

#5465 gs: ls: add etag
  dvc/fs/gs.py
Labels: bug, skip-changelog

#5467 build: deb/rpm: require git >= 1.7.0
  scripts/build_posix.sh
Labels: backport-1.11, build

#5469 fs: remove unused use_state decorator
  dvc/fs/base.py
  setup.py
Labels: refactoring, skip-changelog

#5470 objects: separate staging
  dvc/api/__init__.py
  dvc/checkout.py
  dvc/dependency/repo.py
  dvc/objects/__init__.py
  dvc/objects/stage.py
  dvc/output/base.py
  dvc/repo/diff.py
  dvc/repo/fetch.py
  tests/func/test_add.py
  tests/func/test_data_cloud.py
  tests/func/test_external_repo.py
  tests/func/test_remote.py
  tests/unit/fs/test_dvc.py
  tests/unit/fs/test_repo.py
  tests/unit/test_external_repo.py
Labels: refactoring, skip-changelog

#5474 state: remove unused files property
  dvc/state.py
Labels: refactoring, skip-changelog

#5476 parametrization: remove support for double braces
  dvc/parsing/interpolate.py
  tests/unit/test_interpolate.py
Labels: parametrization, skip-changelog

#5479 fs: detach state from fs
  dvc/cache/base.py
  dvc/checkout.py
  dvc/fs/base.py
  dvc/fs/local.py
  dvc/objects/__init__.py
  dvc/objects/stage.py
  dvc/remote/base.py
  dvc/repo/checkout.py
  dvc/state.py
  tests/func/test_state.py
Labels: refactoring, skip-changelog

#5481 dvc: rename cache -> odb
  dvc/cache/gdrive.py
  dvc/data_cloud.py
  dvc/dependency/repo.py
  dvc/external_repo.py
  dvc/fs/base.py
  dvc/fs/dvc.py
  dvc/info.py
  dvc/objects/db/__init__.py
  dvc/objects/db/base.py
  dvc/objects/db/gdrive.py
  dvc/objects/db/local.py
  dvc/objects/db/ssh.py
  dvc/objects/stage.py
  dvc/output/base.py
  dvc/remote/base.py
  dvc/repo/__init__.py
  dvc/repo/add.py
  dvc/repo/diff.py
  dvc/repo/experiments/__init__.py
  dvc/repo/fetch.py
  dvc/repo/gc.py
  dvc/stage/__init__.py
  dvc/stage/cache.py
  tests/func/api/test_api.py
  tests/func/experiments/test_remote.py
  tests/func/metrics/test_show.py
  tests/func/plots/test_show.py
  tests/func/remote/test_index.py
  tests/func/test_add.py
  tests/func/test_checkout.py
  tests/func/test_data_cloud.py
  tests/func/test_diff.py
  tests/func/test_external_repo.py
  tests/func/test_gc.py
  tests/func/test_get.py
  tests/func/test_import.py
  tests/func/test_import_url.py
  tests/func/test_odb.py
  tests/func/test_remote.py
  tests/func/test_remove.py
  tests/func/test_repo.py
  tests/func/test_repro.py
  tests/func/test_run_single_stage.py
  tests/func/test_s3.py
  tests/remotes/__init__.py
  tests/unit/objects/db/__init__.py
  tests/unit/objects/db/test_local.py
  tests/unit/output/test_output.py
  tests/unit/remote/test_base.py
  tests/unit/repo/test_repo.py
  tests/unit/stage/test_cache.py
  tests/unit/test_external_repo.py
  tests/unit/test_info.py
Labels: refactoring, skip-changelog

#5483 tests: temporarily exclude gdrivefs from extras
  .github/workflows/tests.yaml
  setup.py
  tests/remotes/gdrive.py
Labels: build, skip-changelog

#5484 dvc.lock: raise error if the file is gitignored
  dvc/dvcfile.py
  tests/unit/test_lockfile.py
Labels: enhancement, skip-changelog

#5491 git: implement dulwich add --update
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/backend/pygit2.py
  tests/unit/scm/test_git.py
Labels: skip-changelog

#5495 pygit: implement get_refs_containing
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/pygit2.py
Labels: skip-changelog

#5496 pygit: implement resolve_commit
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/show.py
  dvc/repo/experiments/utils.py
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/backend/pygit2.py
  dvc/scm/git/objects.py
Labels: skip-changelog

#5497 pygit/dulwich: implement create branch
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/pygit2.py
Labels: skip-changelog

#5498 stage:list: move truncating text logic to utils, add tests
  dvc/command/stage.py
  dvc/utils/humanize.py
  tests/unit/utils/test_humanize.py
Labels: refactoring, skip-changelog

#5499 stage:list: update output and help text
  dvc/command/stage.py
Labels: enhancement, skip-changelog, ui

#5512 dir_info: only build trie when needed
  dvc/checkout.py
  dvc/dir_info.py
  dvc/fs/dvc.py
  dvc/objects/__init__.py
  dvc/objects/stage.py
  dvc/output/base.py
  dvc/path_info.py
  tests/unit/test_dir_info.py
Labels: performance, refactoring, skip-changelog

#5517 exp show: fix bug where already collected experiment results could be dropped
  dvc/repo/experiments/show.py
Labels: bugfix, skip-changelog
