Repository iterative/dvc, pull requests merged in 2021-09, with the labels that each got.

#6501 machine: add `dvc machine ssh`
  dvc/command/machine.py
  dvc/machine/__init__.py
  dvc/machine/backend/base.py
  dvc/machine/backend/terraform.py
  setup.py
  tests/unit/command/test_machine.py
  tests/unit/machine/test_terraform.py
Labels: A: executors

#6526 tpi: lazily import python_terraform
  .github/workflows/packages.yaml
  dvc/machine/backend/terraform.py
  dvc/tpi/__init__.py
  tests/unit/machine/test_terraform.py
Labels: skip-changelog, A: executors

#6520 gha: allow running tests on other branches
  .github/workflows/tests.yaml
Labels: maintenance, skip-changelog, github_actions

#6528 machine: move to `tpi[ssh]`
  dvc/machine/__init__.py
  dvc/machine/backend/base.py
  dvc/machine/backend/terraform.py
  dvc/tpi/__init__.py
  dvc/tpi/templates/main.tf
  setup.py
  tests/unit/machine/test_terraform.py
Labels: refactoring, build, external-product, dependencies, A: executors

#6535 docs: add missing stage name
  README.rst
Labels: maintenance

#6406 s3: inline bucket region caching
  dvc/config_schema.py
  dvc/fs/s3.py
Labels: optimize, fs: s3

#6541 try to fix flaky dvclive test
  tests/func/test_live.py
Labels: testing, ci

#6539 extract transfer related logic from odb to fs.utils.transfer
  dvc/fs/__init__.py
  dvc/fs/utils.py
  dvc/objects/db/base.py
Labels: refactoring

#6537 machine: support instance size & startup script config
  dvc/config.py
  dvc/config_schema.py
  dvc/machine/__init__.py
Labels: skip-changelog, A: executors

#6545 Set timeout for jobs in Github Actions
  .github/workflows/tests.yaml
  setup.cfg
Labels: testing, github_actions

#6552 add contrib avatars
  README.rst
Labels: p3-nice-to-have, maintenance

#6554 remove `tpi.base` dependency
  dvc/machine/backend/base.py
  dvc/machine/backend/terraform.py
Labels: refactoring, A: executors

#6567 state: get rid of self.fs
  dvc/state.py
Labels: refactoring, skip-changelog

#6569 Move install requires to requirements/default.txt
  requirements/default.txt
  setup.py
Labels: build, skip-changelog, dependencies

#6591 objects.transfer: minor refactoring, move lazier taskset inside custom executor
  dvc/objects/transfer.py
  dvc/utils/threadpool.py
Labels: refactoring, A: object-storage

#6600 output: use remote kwarg instead of odb
  dvc/output.py
  tests/func/test_data_cloud.py
Labels: bugfix

#6620 TmpDir: add serialization utilities
  dvc/utils/serialize/__init__.py
  dvc/utils/serialize/_common.py
  dvc/utils/serialize/_json.py
  dvc/utils/serialize/_toml.py
  dvc/utils/serialize/_yaml.py
  tests/dir_helpers.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_show.py
  tests/func/metrics/test_diff.py
  tests/func/metrics/test_show.py
  tests/func/params/test_diff.py
  tests/func/parsing/test_errors.py
  tests/func/parsing/test_foreach.py
  tests/func/parsing/test_interpolated_entry.py
  tests/func/parsing/test_resolver.py
  tests/func/plots/test_diff.py
  tests/func/plots/test_modify.py
  tests/func/plots/test_show.py
  tests/func/plots/utils.py
  tests/func/test_add.py
  tests/func/test_checkout.py
  tests/func/test_commit.py
  tests/func/test_data_cloud.py
  tests/func/test_dvcfile.py
  tests/func/test_lockfile.py
  tests/func/test_move.py
  tests/func/test_repo_index.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_run_multistage.py
  tests/func/test_stage.py
  tests/func/test_stage_load.py
  tests/unit/render/test_vega.py
  tests/unit/test_context.py
  tests/unit/test_dvcfile.py
  tests/unit/test_lockfile.py
Labels: refactoring, testing, skip-changelog

#6615 ssh: ask password before setting it
  dvc/fs/ssh.py
  tests/unit/fs/test_ssh.py
Labels: fs: ssh

#6621 exp init: add simple dvc exp init command
  dvc/command/experiments.py
  tests/func/experiments/test_init.py
Labels: A: experiments, feature, A: cli

#6645 gha: increase timeouts
  .github/workflows/tests.yaml
Labels: skip-changelog

#6664 debug: add yappi, callgrind output support
  dvc/_debug.py
Labels: A: debug

#6648 checkout: start switching to obj-based workflow
  dvc/checkout.py
  dvc/fs/webhdfs.py
  dvc/objects/diff.py
  tests/func/test_add.py
Labels: refactoring, performance, skip-changelog

#6661 merge yaml parsing and schema validation into one, aka strictyaml.load
  dvc/dvcfile.py
  dvc/stage/exceptions.py
  dvc/utils/strictyaml.py
  tests/func/test_dvcfile.py
  tests/func/test_lockfile.py
  tests/unit/test_dvcfile.py
Labels: enhancement

#6678 ssh: bundle bcrypt by default
  requirements/ssh.txt
Labels: fs: ssh

#6677 ssh: use a docker-based testing environment
  tests/conftest.py
  tests/docker-compose.yml
  tests/remotes/__init__.py
  tests/remotes/ssh.py
Labels: maintenance, fs: ssh

#6517 ssh: fix path normalization on windows
  dvc/fs/ssh.py
  tests/unit/fs/test_ssh.py
Labels: bugfix, P: windows

#6684 state: cleanup redundant or localfs-specific logic
  dvc/state.py
Labels: refactoring, skip-changelog

#6685 system: remove legacy code
  dvc/ignore.py
  dvc/system.py
  requirements/default.txt
  requirements/tests.txt
  scripts/pyinstaller/hooks/hook-win32file.py
  tests/func/test_system.py
Labels: refactoring, skip-changelog

#6686 system: get rid of speedcopy
  dvc/system.py
  requirements/default.txt
Labels: refactoring

#6688 http: allow reading proxies from the current environment;
  dvc/fs/http.py
Labels: bugfix, fs: http

#6683 add alias ls for dvc list
  dvc/command/ls/__init__.py
  tests/unit/command/ls/test_ls.py
Labels: enhancement

#6690 ui: use ui.rich_text instead of rich.text.Text
  dvc/command/experiments.py
  dvc/ui/__init__.py
  dvc/ui/table.py
  dvc/updater.py
  dvc/utils/strictyaml.py
Labels: skip-changelog

#6701 exp init: show heading based on the presence of dvc.yaml file
  dvc/command/experiments.py
Labels: enhancement

#6700 utils.http: remove open url
  dvc/utils/http.py
  dvc/utils/stream.py
  tests/unit/utils/test_http.py
Labels: refactoring, skip-changelog

#6705 deps: add contextvars as a dependency for Python3.6
  requirements/default.txt
Labels: skip-changelog, dependencies

#6711 cli: add short alias for --show-{csv,json,md}
  dvc/command/data_sync.py
  dvc/command/diff.py
  dvc/command/experiments.py
  dvc/command/ls/__init__.py
  dvc/command/metrics.py
  dvc/command/params.py
  dvc/command/status.py
  dvc/compare.py
  tests/func/experiments/test_show.py
  tests/unit/command/ls/test_ls.py
  tests/unit/command/test_compat_flag.py
  tests/unit/command/test_diff.py
  tests/unit/command/test_experiments.py
  tests/unit/command/test_metrics.py
  tests/unit/command/test_params.py
  tests/unit/command/test_status.py
  tests/unit/test_compare.py
Labels: enhancement, ui, A: cli

#6721 checkout: move to objects
  dvc/dependency/repo.py
  dvc/objects/checkout.py
  dvc/output.py
  tests/func/test_add.py
Labels: refactoring, skip-changelog
