Repository iterative/dvc, pull requests merged in 2021-08, with the labels that each got.

#6377 setup: limit python-benedict version
  setup.py
Labels: bugfix, skip-changelog

#6378 Fix merging of params when empty
  dvc/repo/experiments/__init__.py
  dvc/utils/collections.py
  setup.py
  tests/unit/utils/test_collections.py
Labels: ci, testing

#6380 benedict: cleanup code and add tests
  dvc/utils/collections.py
  tests/unit/utils/test_collections.py
Labels: bugfix, p0-critical

#6381 exp gc: fix `--queued` warning message
  dvc/command/experiments.py
Labels: skip-changelog, ui

#6360 objects: use object IDs and references instead of naive objs in status/transfer
  dvc/checkout.py
  dvc/data_cloud.py
  dvc/dependency/repo.py
  dvc/external_repo.py
  dvc/fs/__init__.py
  dvc/fs/base.py
  dvc/fs/dvc.py
  dvc/fs/repo.py
  dvc/hash_info.py
  dvc/objects/__init__.py
  dvc/objects/db/base.py
  dvc/objects/db/reference.py
  dvc/objects/file.py
  dvc/objects/reference.py
  dvc/objects/stage.py
  dvc/objects/status.py
  dvc/objects/transfer.py
  dvc/objects/tree.py
  dvc/output.py
  dvc/path_info.py
  dvc/repo/diff.py
  dvc/repo/fetch.py
  dvc/repo/gc.py
  dvc/repo/push.py
  dvc/repo/status.py
  dvc/stage/__init__.py
  dvc/state.py
  dvc/utils/fs.py
  tests/func/objects/db/test_index.py
  tests/func/test_commit.py
  tests/func/test_data_cloud.py
  tests/func/test_external_repo.py
  tests/func/test_import.py
  tests/func/test_ls.py
  tests/func/test_remote.py
  tests/func/test_run_single_stage.py
  tests/unit/fs/test_dvc.py
  tests/unit/fs/test_repo.py
  tests/unit/objects/db/test_local.py
  tests/unit/repo/test_repo.py
  tests/unit/utils/test_fs.py
  tests/utils/__init__.py
Labels: refactoring

#6300 introduce index
  dvc/command/dag.py
  dvc/command/stage.py
  dvc/command/status.py
  dvc/objects/__init__.py
  dvc/output.py
  dvc/repo/__init__.py
  dvc/repo/add.py
  dvc/repo/checkout.py
  dvc/repo/collect.py
  dvc/repo/destroy.py
  dvc/repo/diff.py
  dvc/repo/imp_url.py
  dvc/repo/index.py
  dvc/repo/params/show.py
  dvc/repo/reproduce.py
  dvc/repo/run.py
  dvc/repo/stage.py
  dvc/stage/utils.py
  dvc/utils/__init__.py
  dvc/utils/fs.py
  tests/dir_helpers.py
  tests/func/conftest.py
  tests/func/test_add.py
  tests/func/test_dvcfile.py
  tests/func/test_repo_index.py
  tests/func/test_repro.py
  tests/func/test_stage_load.py
  tests/unit/command/test_dag.py
  tests/unit/command/test_status.py
  tests/unit/repo/test_repo.py
Labels: refactoring

#6382 Show name of experiments in the queue
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/show.py
  tests/func/experiments/test_show.py
Labels: ui, A: experiments

#6390 cleanup index, and add test for used_objs
  dvc/repo/index.py
  dvc/repo/run.py
  tests/func/test_repo_index.py
Labels: enhancement, testing

#6392 refodb: cache ref objects
  dvc/objects/db/base.py
  dvc/objects/db/reference.py
Labels: performance, skip-changelog, regression

#6401 repofs: use underlying fs.download to download files
  dvc/fs/dvc.py
  dvc/fs/git.py
  dvc/fs/repo.py
Labels: performance, optimize

#6408 pygit: account for locked dirs on windows during checkout
  dvc/scm/git/backend/pygit2.py
  tests/unit/scm/test_git.py
Labels: bugfix

#6407 Fix issue while sending analytics report
  dvc/analytics.py
  tests/func/test_analytics.py
Labels: p0-critical, bugfix, P: windows

#6332 Push running checkpoint to remote
  dvc/env.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/push.py
  dvc/scm/base.py
  dvc/scm/git/__init__.py
  dvc/scm/git/backend/base.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/backend/pygit2.py
  tests/func/experiments/conftest.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_remote.py
Labels: p1-important, external-product, A: experiments

#6425 pyinstaller: build: check dvc doctor output
  scripts/build-requirements.txt
  scripts/pyinstaller/build.py
  scripts/pyinstaller/hooks/hook-dvc.py
Labels: maintenance, skip-changelog

#6422 add support for Python 3.10
  .github/workflows/tests.yaml
  setup.py
  tests/dir_helpers.py
  tests/remotes/hdfs.py
Labels: maintenance

#6432 fs: find(..., detail=True) now casts values properly
  dvc/fs/fsspec_wrapper.py
  setup.py
  tests/func/test_fs.py
Labels: bugfix

#6247 updater: only notify in dvc doctor
  dvc/command/base.py
  dvc/command/version.py
Labels: enhancement, p1-important, ui

#6437 Change ui message for the updater
  dvc/command/version.py
  dvc/updater.py
  tests/unit/test_updater.py
Labels: enhancement, ui

#6448 analytics: add DVC_ANALYTICS env var
  dvc/analytics.py
  dvc/env.py
  tests/unit/test_analytics.py
Labels: p0-critical, c1-quick-fix, feature

#6458 exp run: pass recursive args to checkout
  dvc/repo/experiments/executor/base.py
  tests/func/experiments/test_experiments.py
Labels: c1-quick-fix, A: experiments, bugfix

#6464 ruamel.yaml: adjust to new DuplicatedKeyError
  dvc/utils/serialize/_yaml.py
  setup.py
  tests/unit/utils/serialize/test_yaml.py
Labels: refactoring, p0-critical
