Repository iterative/dvc, pull requests merged in 2021-04, with the labels that each got.

#5752 exp show: fix queued exp display
  dvc/command/experiments.py
Labels: bugfix, ui

#5753 exp show: fix column collapse behavior
  dvc/utils/table.py
Labels: bugfix, skip-changelog, ui

#5754 git: better error message if commit user is not configured
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/pygit2.py
Labels: skip-changelog, ui

#5765 Fix test assertion with environment when using pyenv
  tests/unit/fs/test_hdfs.py
Labels: skip-changelog, testing

#5751 exp run: --reset no longer implies --force
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor/base.py
Labels: bugfix

#5756 ui: unify tables
  dvc/types.py
  dvc/ui/__init__.py
  dvc/ui/table.py
  dvc/utils/pager.py
  tests/unit/ui/test_table.py
Labels: ui

#5813 exp show: fix bug where params from commits were merged with workspace values
  dvc/repo/experiments/show.py
Labels: bugfix, ui

#5822 repo: handle rev without scm
  dvc/repo/__init__.py
  tests/func/test_api.py
Labels: bugfix

#5830 exp run: suppress "finished run" output on --dry
  dvc/repo/experiments/executor/base.py
Labels: ui

#5831 exp run: disallow --rev for workspace runs
  dvc/command/experiments.py
Labels: ui

#5809 Add support for kerberos token based auth
  dvc/config_schema.py
  dvc/fs/hdfs.py
Labels: awaiting response

#5818 exp: use exp baseline for DVC commands that compare to HEAD during `exp run`
  dvc/repo/diff.py
  dvc/repo/experiments/diff.py
  dvc/repo/experiments/show.py
  dvc/repo/experiments/utils.py
  dvc/repo/metrics/diff.py
  dvc/repo/params/diff.py
  dvc/repo/plots/diff.py
  dvc/scm/git/__init__.py
  tests/func/experiments/test_experiments.py
  tests/unit/repo/plots/test_diff.py
Labels: ui

#5823 gha: tests: don't set sensitive env secrets for all steps
  .github/workflows/tests.yaml
Labels: maintenance, skip-changelog

#5847 cmd: stage list: use ui.table
  dvc/command/stage.py
Labels: skip-changelog, ui

#5694 html: enable providing custom html page templates
  dvc/command/live.py
  dvc/command/plots.py
  dvc/config_schema.py
  dvc/repo/live.py
  dvc/repo/plots/__init__.py
  dvc/utils/html.py
  tests/func/utils/test_html.py
Labels: enhancement, needs-review, ui

#5859 exp run: `dvc commit` DVC-tracked data deps when stashing an experiment
  dvc/repo/commit.py
  dvc/repo/experiments/__init__.py
  dvc/stage/__init__.py
  tests/func/experiments/test_experiments.py
Labels: enhancement

#5876 dagascii: remove unused pager
  dvc/dagascii.py
  tests/unit/test_dagascii.py
Labels: maintenance

#5852 ui: tabular data
  .coveragerc
  dvc/compare.py
  dvc/ui/table.py
  tests/unit/test_tabular_data.py
Labels: enhancement, refactoring, skip-changelog

#5872 refactor diff and show to use new table ui and new data structure
  dvc/command/experiments.py
  dvc/command/metrics.py
  dvc/command/params.py
  dvc/command/repro.py
  dvc/compare.py
  tests/basic_env.py
  tests/func/metrics/test_diff.py
  tests/func/test_repro.py
  tests/unit/command/test_metrics.py
  tests/unit/command/test_params.py
  tests/unit/test_compare.py
Labels: enhancement, ui

#5880 refactor exp show: use new abstractions
  dvc/command/experiments.py
Labels: enhancement, ui

#5887 diff: use ui.table for --show-md
  dvc/command/diff.py
  dvc/utils/diff.py
  tests/unit/command/test_diff.py
Labels: enhancement, ui

#5885 exp show: separate ui representation of exp names and identifiers
  dvc/command/experiments.py
  dvc/compare.py
  tests/unit/test_tabular_data.py
Labels: enhancement, refactoring, ui

#5898 dependabot: use "maintenance" label
  .github/dependabot.yml
Labels: maintenance

#5849 pygit: force release of odb contexts after checkout/merge
  dvc/scm/git/backend/pygit2.py
Labels: bugfix

#5829 exp run: error out when trying to resume from intermediate checkpoint w/no modifications
  dvc/command/experiments.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/apply.py
  dvc/repo/experiments/base.py
  dvc/scm/git/__init__.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_show.py
Labels: enhancement, experiments

#5901 simplify experiments row collection logic
  dvc/command/experiments.py
Labels: skip-changelog, ui
