Repository iterative/dvc, pull requests merged in 2021-06, with the labels that each got.

#6090 try skipping local pre-commit hooks
  .pre-commit-config.yaml
Labels: ci, skip-changelog

#6059 odb: don't use fs.path_info
  dvc/checkout.py
  dvc/fs/__init__.py
  dvc/fs/azure.py
  dvc/fs/base.py
  dvc/fs/gdrive.py
  dvc/fs/gs.py
  dvc/fs/hdfs.py
  dvc/fs/http.py
  dvc/fs/local.py
  dvc/fs/oss.py
  dvc/fs/s3.py
  dvc/fs/ssh/__init__.py
  dvc/fs/webdav.py
  dvc/fs/webhdfs.py
  dvc/objects/db/__init__.py
  dvc/objects/db/base.py
  dvc/objects/db/local.py
  dvc/objects/db/ssh.py
  dvc/objects/stage.py
  dvc/output.py
  dvc/remote/__init__.py
  dvc/remote/base.py
  dvc/stage/cache.py
  tests/func/test_fs.py
  tests/func/test_odb.py
  tests/func/test_remote.py
  tests/unit/fs/test_azure.py
  tests/unit/fs/test_s3.py
  tests/unit/fs/test_tree.py
  tests/unit/objects/db/test_local.py
  tests/unit/remote/ssh/test_ssh.py
  tests/unit/remote/test_base.py
  tests/unit/remote/test_http.py
  tests/unit/remote/test_oss.py
  tests/unit/remote/test_remote.py
  tests/unit/remote/test_remote_tree.py
  tests/unit/remote/test_webdav.py
  tests/unit/remote/test_webhdfs.py
Labels: refactoring, skip-changelog

#6008 output/remote: get rid of NamedCache
  dvc/data_cloud.py
  dvc/dependency/repo.py
  dvc/hash_info.py
  dvc/objects/db/__init__.py
  dvc/objects/db/base.py
  dvc/objects/file.py
  dvc/objects/tree.py
  dvc/output.py
  dvc/remote/base.py
  dvc/repo/__init__.py
  dvc/repo/fetch.py
  dvc/repo/gc.py
  dvc/repo/push.py
  dvc/repo/status.py
  dvc/stage/__init__.py
  dvc/stage/cache.py
  tests/func/test_data_cloud.py
  tests/func/test_remote.py
  tests/unit/objects/db/test_local.py
  tests/unit/output/test_output.py
  tests/unit/repo/test_repo.py
Labels: refactoring, skip-changelog

#6099 webdav4: migrate to new library
  dvc/fs/webdav.py
  setup.py
  tests/remotes/webdav.py
  tests/unit/remote/test_webdav.py
Labels: fs: webdav

#6121 ls: specify rev as kwarg
  dvc/repo/ls.py
  tests/func/test_ls.py
Labels: bugfix

#6142 http/webdav: support specifying custom certs in `ssl_verify`
  dvc/config_schema.py
  dvc/fs/webdav.py
  tests/unit/remote/test_http.py
  tests/unit/remote/test_webdav.py
Labels: fs: http, fs: webdav

#6137 setup: bump fsspec/s3fs/gcsfs to 2021.06.0
  setup.py
Labels: upstream

#6155 webdav: minor updates
  dvc/fs/__init__.py
  dvc/fs/webdav.py
  dvc/fs/webdavs.py
  setup.py
  tests/unit/remote/test_webdav.py
Labels: fs: webdav

#6189 fix webdav tests and then add some
  dvc/fs/webdav.py
  tests/unit/remote/test_webdav.py
  tests/utils/__init__.py
  tests/utils/asserts.py
Labels: testing

#6109 odb: treat external repo dependencies as objects
  dvc/dependency/repo.py
  dvc/exceptions.py
  dvc/fs/repo.py
  dvc/objects/__init__.py
  dvc/objects/db/base.py
  dvc/objects/db/git.py
  dvc/output.py
  dvc/remote/base.py
  dvc/repo/__init__.py
  dvc/repo/fetch.py
  dvc/repo/gc.py
  dvc/repo/push.py
  dvc/repo/status.py
  dvc/stage/__init__.py
  dvc/stage/cache.py
  tests/func/test_data_cloud.py
  tests/func/test_import.py
  tests/unit/output/test_output.py
  tests/unit/repo/test_repo.py
Labels: refactoring

#6202 env: track DVC_IGNORE_ISATTY as a env that we support
  dvc/env.py
  dvc/progress.py
Labels: skip-changelog

#6176 ui: migrating rest to the ui.write
  dvc/command/config.py
  dvc/command/data_sync.py
  dvc/command/destroy.py
  dvc/command/diff.py
  dvc/command/experiments.py
  dvc/command/gc.py
  dvc/command/get.py
  dvc/command/init.py
  dvc/command/live.py
  dvc/command/metrics.py
  dvc/command/params.py
  dvc/command/plots.py
  dvc/command/remote.py
  dvc/command/repro.py
  dvc/command/root.py
  dvc/command/status.py
  dvc/command/version.py
  dvc/ui/__init__.py
  tests/func/plots/test_show.py
  tests/func/test_config.py
  tests/func/test_data_cloud.py
  tests/func/test_root.py
  tests/func/test_version.py
  tests/unit/command/test_diff.py
  tests/unit/command/test_get.py
  tests/unit/command/test_metrics.py
  tests/unit/command/test_params.py
  tests/unit/command/test_plots.py
  tests/unit/command/test_status.py
Labels: skip-changelog, ui

#6187 pass size to upload_fobj
  dvc/fs/base.py
  dvc/fs/fsspec_wrapper.py
  dvc/fs/gdrive.py
  dvc/fs/hdfs.py
  dvc/fs/http.py
  dvc/fs/local.py
  dvc/fs/oss.py
  dvc/fs/ssh/__init__.py
  dvc/fs/webdav.py
  dvc/fs/webhdfs.py
  dvc/objects/stage.py
  setup.py
Labels: enhancement, fs: webdav

#6217 obj: staging: remove redundant exists() call
  dvc/objects/stage.py
  tests/func/test_data_cloud.py
Labels: optimize

#6236 utils: normalize case in path_isin functions
  dvc/utils/fs.py
  tests/unit/utils/test_fs.py
Labels: bugfix

#6232 git: Keep trailing slash when checking if directory is gitignored
  dvc/repo/stage.py
  dvc/scm/git/backend/dulwich.py
  dvc/scm/git/backend/gitpython.py
  dvc/scm/git/backend/pygit2.py
  tests/func/test_scm.py
  tests/func/test_stage.py
Labels: bugfix

#6254 push params in the experiments table to the right
  dvc/command/experiments.py
Labels: A: cli, A: experiments, bugfix
