Repository iterative/dvc, pull requests merged in 2021-05, with the labels that each got.

#5904 metrics diff/show: rollback to rounding fractional digits with precision
  dvc/command/metrics.py
  dvc/compare.py
  tests/func/metrics/test_diff.py
  tests/unit/command/test_metrics.py
  tests/unit/test_compare.py
Labels: enhancement, skip-changelog, ui

#5952 tests: mark test_stash_pop as xfail on linux
  tests/func/test_scm.py
Labels: ci, testing

#5907 dvcfile/stage: check if dvcfile would be gitignored on stage creation
  dvc/dvcfile.py
  dvc/stage/__init__.py
  tests/func/test_add.py
  tests/unit/test_dvcfile.py
Labels: bugfix

#5903 exp show: decoupling tree and styling from row collection
  dvc/command/experiments.py
Labels: skip-changelog, ui

#5954 output: resolve path for path_isin checks
  dvc/output/local.py
Labels: ci, skip-changelog, testing

#5959 tests: rerun gdrive and gs on failures
  setup.cfg
  tests/conftest.py
  tests/func/test_add.py
  tests/func/test_api.py
  tests/func/test_data_cloud.py
  tests/func/test_fs.py
  tests/func/test_import_url.py
  tests/func/test_update.py
  tests/unit/remote/test_remote_tree.py
Labels: build, ci, skip-changelog, testing

#5953 move: validate new stage before move
  dvc/repo/move.py
  dvc/stage/utils.py
  tests/func/test_move.py
Labels: bugfix

#5974 run gdrive tests in a single job, run all on schedule
  .github/workflows/tests.yaml
  tests/dir_helpers.py
Labels: ci, testing

#5962 try to close dvc.state on exit
  dvc/command/base.py
  dvc/command/init.py
  dvc/info.py
  dvc/main.py
  dvc/repo/__init__.py
  tests/basic_env.py
  tests/dir_helpers.py
  tests/func/test_add.py
  tests/func/test_checkout.py
  tests/func/test_cli.py
  tests/func/test_run_single_stage.py
Labels: ci, skip-changelog, testing

#5977 tests: skip copying sqlite files in test directories
  dvc/utils/fs.py
  tests/dir_helpers.py
Labels: ci, skip-changelog, testing

#5812 Decoupling dvcignore and fs
  dvc/checkout.py
  dvc/command/check_ignore.py
  dvc/config.py
  dvc/dependency/repo.py
  dvc/dvcfile.py
  dvc/fs/azure.py
  dvc/fs/base.py
  dvc/fs/fsspec_wrapper.py
  dvc/fs/gdrive.py
  dvc/fs/git.py
  dvc/fs/gs.py
  dvc/fs/hdfs.py
  dvc/fs/http.py
  dvc/fs/local.py
  dvc/fs/memory.py
  dvc/fs/oss.py
  dvc/fs/repo.py
  dvc/fs/s3.py
  dvc/fs/ssh/__init__.py
  dvc/fs/webdav.py
  dvc/fs/webhdfs.py
  dvc/ignore.py
  dvc/objects/stage.py
  dvc/output/base.py
  dvc/output/local.py
  dvc/repo/__init__.py
  dvc/repo/add.py
  dvc/repo/brancher.py
  dvc/repo/collect.py
  dvc/repo/fetch.py
  dvc/repo/get.py
  dvc/repo/stage.py
  dvc/scm/git/__init__.py
  dvc/state.py
  dvc/utils/fs.py
  tests/func/test_external_repo.py
  tests/func/test_fs.py
  tests/func/test_ignore.py
  tests/func/test_ls.py
  tests/func/test_stage.py
  tests/func/test_state.py
  tests/unit/fs/test_repo.py
  tests/unit/test_dvcfile.py
  tests/unit/test_external_repo.py
  tests/unit/utils/test_fs.py
Labels: refactoring

#6000 fs: get rid of fs_root
  dvc/fs/git.py
  dvc/fs/local.py
  dvc/ignore.py
  tests/unit/test_ignore.py
Labels: refactoring, skip-changelog

#6002 dvcignore: refactor from_file(s)
  dvc/ignore.py
  tests/unit/test_ignore.py
Labels: refactoring, skip-changelog

#6004 ls: use ui.write
  dvc/command/ls/__init__.py
  tests/func/test_ls.py
  tests/unit/command/ls/test_ls.py
  tests/unit/command/ls/test_ls_colors.py
Labels: refactoring, skip-changelog, ui

#6007 stage: allow duplicate values in _read_env
  dvc/stage/__init__.py
  tests/unit/stage/test_stage.py
Labels: bugfix, skip-changelog

#6021 ui: migrate cache:dir and check-ignore to ui.write
  dvc/command/cache.py
  dvc/command/check_ignore.py
  tests/func/test_check_ignore.py
  tests/func/test_odb.py
  tests/unit/command/test_cache.py
Labels: skip-changelog, ui

#6026 rwlock: add missing space to the message
  dvc/rwlock.py
Labels: skip-changelog

#6028 ui: migrate checkout to ui.write
  dvc/command/checkout.py
  tests/func/test_checkout.py
  tests/func/test_data_cloud.py
  tests/unit/command/test_checkout.py
Labels: skip-changelog, ui

#6029 ui: migrate completion to ui.write
  dvc/command/completion.py
Labels: skip-changelog, ui

#6017 dvcfs: open: raise FileNotFoundError on missing version info
  dvc/fs/dvc.py
  tests/unit/fs/test_dvc.py
Labels: bugfix

#6044 ui: migrate dag to ui.write
  dvc/command/dag.py
Labels: enhancement, skip-changelog, ui

#6049 git: update dulwich to 0.20.22
  setup.py
  tests/conftest.py
Labels: bugfix, performance

#6062 fix mypy errors
  dvc/compare.py
Labels: skip-changelog

#6061 output/dep: specify schema as a dictionary
  dvc/dependency/__init__.py
  dvc/output.py
Labels: skip-changelog

#6037 [RFC] ui: write gets a styled param with rich console printing
  dvc/command/checkout.py
  dvc/ui/__init__.py
  tests/func/test_checkout.py
  tests/func/test_data_cloud.py
  tests/unit/command/test_checkout.py
Labels: enhancement, skip-changelog, ui

#6074 fix empty string parsing for the command
  dvc/command/stage.py
  tests/unit/command/test_stage.py
Labels: A: cli, bugfix

#6075 use kwargs when passing command line args to run
  dvc/command/run.py
  tests/unit/command/test_run.py
  tests/unit/command/test_stage.py
  tests/utils/asserts.py
Labels: testing

#6081 fix errors raised by pylint
  .pylintrc
  dvc/checkout.py
  dvc/command/destroy.py
  dvc/command/experiments.py
  dvc/command/gc.py
  dvc/fs/http.py
  dvc/fs/ssh/__init__.py
  dvc/logger.py
  dvc/output.py
  dvc/path_info.py
  dvc/progress.py
  dvc/repo/get_url.py
  dvc/stage/__init__.py
  tests/unit/command/test_experiments.py
  tests/unit/command/test_repro.py
  tests/unit/test_daemon.py
Labels: build, ci

#6085 pin networkx to 2.5
  setup.py
Labels: dependencies, maintenance
