Repository iterative/dvc, pull requests merged in 2022-05, with the labels that each got.

#7672 deps: bump s3fs to >=2022.02.0
  setup.cfg
Labels: dependencies

#7682 fs: remove download
  dvc/fs/_callback.py
  dvc/fs/base.py
  dvc/fs/utils.py
  dvc/output.py
  dvc/repo/get.py
  tests/func/test_external_repo.py
  tests/func/test_fs.py
  tests/func/test_repro.py
Labels: refactoring, skip-changelog

#7683 fs.utils.transfer: remove tqdm progress bars
  dvc/data/checkout.py
  dvc/data/db/reference.py
  dvc/fs/utils.py
  dvc/objects/db.py
Labels: refactoring, skip-changelog

#7697 fs: add more fsspec methods
  dvc/fs/base.py
  dvc/fs/local.py
Labels: refactoring, skip-changelog

#7524 `run/repro/stage add`: regroup options/flags
  dvc/commands/repro.py
  dvc/commands/run.py
  dvc/commands/stage.py
Labels: enhancement, type: enhancement

#7699 fs.get: use async implementation when supported by the filesystem
  dvc/fs/_callback.py
  dvc/fs/base.py
Labels: refactoring, skip-changelog, A: object-storage, A: data-management

#7701 fs.put: introduce non-recursive async put
  dvc/fs/base.py
Labels: refactoring, skip-changelog, A: object-storage, A: data-management

#7694 FileSystem: handle `encoding` via `kwargs`.
  dvc/fs/base.py
Labels: bugfix, fs: http

#7712 repofs: use / as root_marker
  dvc/api.py
  dvc/fs/base.py
  dvc/fs/dvc.py
  dvc/fs/git.py
  dvc/fs/path.py
  dvc/fs/repo.py
  dvc/repo/__init__.py
  dvc/repo/collect.py
  dvc/repo/diff.py
  dvc/repo/get.py
  dvc/repo/ls.py
  dvc/repo/metrics/show.py
  dvc/repo/plots/__init__.py
  tests/unit/fs/test_dvc.py
  tests/unit/fs/test_repo.py
  tests/unit/fs/test_repo_info.py
Labels: refactoring, skip-changelog

#7715 TqdmCallback: make it lazy
  dvc/fs/_callback.py
Labels: enhancement, refactoring, ui, skip-changelog, A: data-management

#7719 exp: use celery threadpool worker instead of prefork
  dvc/repo/experiments/queue/local.py
  setup.cfg
Labels: A: experiments

#7720 TqdmCallback: minor fixup, check for None explicitly
  dvc/fs/_callback.py
Labels: refactoring, skip-changelog

#7722 fs.callbacks: simplify, ensure `None` does not break them, lazy richcallbacks
  dvc/data/checkout.py
  dvc/data/stage.py
  dvc/fs/_callback.py
  dvc/objects/db.py
  dvc/output.py
  dvc/repo/get.py
  dvc/stage/cache.py
  dvc/ui/_rich_progress.py
  dvc/utils/fs.py
  tests/func/test_fs.py
Labels: refactoring, ui, A: data-management

#6120 dvc ls: not raise PathMissingError on empty dir.
  dvc/repo/ls.py
  tests/func/test_ls.py
Labels: bugfix, A: data-management

#7727 dvc.objects: move hash_info, state and meta into dvc.objects
  dvc/data/__init__.py
  dvc/data/db/local.py
  dvc/data/db/reference.py
  dvc/data/diff.py
  dvc/data/gc.py
  dvc/data/reference.py
  dvc/data/stage.py
  dvc/data/status.py
  dvc/data/transfer.py
  dvc/data/tree.py
  dvc/data_cloud.py
  dvc/dependency/param.py
  dvc/dependency/repo.py
  dvc/fs/dvc.py
  dvc/objects/db.py
  dvc/objects/file.py
  dvc/objects/hash_info.py
  dvc/objects/meta.py
  dvc/objects/state.py
  dvc/output.py
  dvc/repo/__init__.py
  dvc/repo/index.py
  dvc/schema.py
  dvc/stage/__init__.py
  dvc/stage/cache.py
  dvc/stage/loader.py
  dvc/stage/utils.py
  dvc/utils/stream.py
  tests/func/test_add.py
  tests/func/test_lockfile.py
  tests/func/test_odb.py
  tests/func/test_repo_index.py
  tests/func/test_repro.py
  tests/func/test_state.py
  tests/unit/fs/test_dvc.py
  tests/unit/fs/test_repo.py
  tests/unit/objects/db/test_local.py
  tests/unit/objects/test_tree.py
  tests/unit/output/test_local.py
  tests/unit/repo/test_repo.py
  tests/unit/stage/test_loader_pipeline_file.py
  tests/unit/stage/test_serialize_pipeline_lock.py
Labels: refactoring, skip-changelog

#7724 dvc: detach gitfs from local paths
  dvc/config.py
  dvc/external_repo.py
  dvc/fs/git.py
  dvc/fs/local.py
  dvc/fs/path.py
  dvc/fs/repo.py
  dvc/ignore.py
  dvc/output.py
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/pathspec_math.py
  dvc/repo/__init__.py
  dvc/repo/brancher.py
  dvc/repo/collect.py
  dvc/repo/diff.py
  dvc/repo/params/show.py
  dvc/repo/plots/__init__.py
  dvc/repo/stage.py
  dvc/stage/loader.py
  dvc/stage/utils.py
  dvc/utils/__init__.py
  setup.cfg
  tests/func/experiments/test_experiments.py
  tests/func/parsing/test_resolver.py
  tests/func/test_fs.py
  tests/func/test_ignore.py
  tests/func/test_used_objs.py
  tests/unit/stage/test_utils.py
  tests/unit/test_external_repo.py
  tests/unit/test_ignore.py
Labels: refactoring, skip-changelog

#7725 dag: fix dot file rendering order.
  dvc/commands/dag.py
  tests/unit/command/test_dag.py
Labels: bugfix

#7732 fs: rename DvcFileSystem to DataFileSystem
  dvc/fs/data.py
  dvc/fs/repo.py
  dvc/repo/__init__.py
  dvc/repo/get.py
  tests/unit/fs/test_data.py
Labels: refactoring, skip-changelog

#7733 fs: rename RepoFileSystem to DvcFileSystem
  dvc/api.py
  dvc/data/reference.py
  dvc/dependency/repo.py
  dvc/fs/dvc.py
  dvc/repo/__init__.py
  dvc/repo/collect.py
  dvc/repo/diff.py
  dvc/repo/get.py
  dvc/repo/ls.py
  dvc/repo/metrics/show.py
  dvc/repo/plots/__init__.py
  dvc/repo/reproduce.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_experiments.py
  tests/func/test_api.py
  tests/func/test_external_repo.py
  tests/func/test_fs.py
  tests/func/test_get.py
  tests/func/test_import.py
  tests/func/test_update.py
  tests/unit/fs/test_data.py
  tests/unit/fs/test_dvc.py
  tests/unit/fs/test_dvc_info.py
  tests/unit/test_external_repo.py
Labels: refactoring, skip-changelog

#7734 dvc.objects: extend diskcache to handle pickle errors
  dvc/cli/__init__.py
  dvc/data/db/index.py
  dvc/objects/cache.py
  dvc/objects/state.py
  dvc/utils/decorators.py
  tests/unit/cli/__init__.py
  tests/unit/cli/test_main.py
  tests/unit/objects/test_cache.py
Labels: refactoring, skip-changelog, A: data-management

#7597 dvc.data: save and try loading raw dir objects
  dvc/data/stage.py
  dvc/data/tree.py
  dvc/objects/hash_info.py
  tests/func/test_commit.py
  tests/func/test_external_repo.py
  tests/func/test_gc.py
  tests/func/test_odb.py
  tests/func/test_remote.py
  tests/func/test_stage.py
  tests/unit/test_hashinfo.py
Labels: performance, optimize, A: status

#7741 dvc.objects.cache: set type in a more compatible way
  dvc/data/db/index.py
  dvc/objects/cache.py
  tests/unit/objects/test_cache.py
Labels: refactoring, skip-changelog

#7714 exp: implement internal queue.kill support(#7587)
  dvc/repo/experiments/queue/base.py
  dvc/repo/experiments/queue/local.py
  dvc/repo/experiments/remove.py
  tests/unit/repo/experiments/queue/test_local.py
Labels: A: experiments, A: task-queue

#7744 dvc.fs: fix iscopy
  dvc/fs/base.py
Labels: skip-changelog, bugfix, A: data-management

#7747 fs.utils: copy dvc.utils.fs to dvc.fs.utils
  dvc/data/db/index.py
  dvc/data/db/local.py
  dvc/data/stage.py
  dvc/data/tree.py
  dvc/fs/dvc.py
  dvc/fs/gdrive.py
  dvc/fs/generic.py
  dvc/fs/local.py
  dvc/fs/s3.py
  dvc/fs/ssh.py
  dvc/fs/utils.py
Labels: refactoring, skip-changelog

#7760 objects.fs: use getpass for prompts
  dvc/objects/fs/implementations/http.py
  dvc/objects/fs/implementations/ssh.py
Labels: A: object-storage

#7762 objects.fs: copy executors to dvc.objects
  dvc/data/transfer.py
  dvc/objects/executors.py
  dvc/objects/fs/base.py
Labels: refactoring, skip-changelog, A: object-storage

#7763 fs: move GitFileSystem out of dvc.objects.fs
  dvc/fs/__init__.py
  dvc/fs/git.py
  dvc/objects/fs/__init__.py
Labels: refactoring, skip-changelog, A: object-storage

#7761 objects.fs: move schemes inside objects.fs
  dvc/data/checkout.py
  dvc/data/db/__init__.py
  dvc/data/db/reference.py
  dvc/data/reference.py
  dvc/data/stage.py
  dvc/data/status.py
  dvc/fs/__init__.py
  dvc/fs/data.py
  dvc/fs/dvc.py
  dvc/fs/git.py
  dvc/ignore.py
  dvc/info.py
  dvc/objects/db.py
  dvc/objects/file.py
  dvc/objects/fs/__init__.py
  dvc/objects/fs/base.py
  dvc/objects/fs/implementations/azure.py
  dvc/objects/fs/implementations/gdrive.py
  dvc/objects/fs/implementations/gs.py
  dvc/objects/fs/implementations/hdfs.py
  dvc/objects/fs/implementations/http.py
  dvc/objects/fs/implementations/https.py
  dvc/objects/fs/implementations/local.py
  dvc/objects/fs/implementations/memory.py
  dvc/objects/fs/implementations/oss.py
  dvc/objects/fs/implementations/s3.py
  dvc/objects/fs/implementations/ssh.py
  dvc/objects/fs/implementations/webdav.py
  dvc/objects/fs/implementations/webhdfs.py
  dvc/objects/fs/scheme.py
  dvc/objects/hash.py
  dvc/output.py
  dvc/repo/__init__.py
  dvc/repo/checkout.py
  dvc/repo/fetch.py
  dvc/repo/index.py
  dvc/repo/move.py
  dvc/repo/stage.py
  dvc/stage/cache.py
  tests/unit/remote/test_remote.py
Labels: refactoring, skip-changelog, A: object-storage

#7765 fs: do not use DvcException in filesystems
  dvc/cli/__init__.py
  dvc/objects/fs/base.py
  dvc/objects/fs/generic.py
  dvc/output.py
  tests/unit/cli/test_main.py
  tests/unit/fs/test_base.py
  tests/unit/output/test_output.py
Labels: refactoring, skip-changelog, A: object-storage

#7766 objects.fs: do not use format_link, DvcException and fix_env from DVC
  dvc/cli/__init__.py
  dvc/fs/__init__.py
  dvc/objects/fs/base.py
  dvc/objects/fs/errors.py
  dvc/objects/fs/implementations/azure.py
  dvc/objects/fs/implementations/gdrive.py
  dvc/objects/fs/implementations/hdfs.py
  dvc/objects/fs/implementations/http.py
  dvc/objects/fs/implementations/s3.py
  dvc/objects/fs/utils.py
  tests/unit/fs/test_s3.py
Labels: refactoring, A: object-storage, A: cli

#7764 objects.fs: use split in Path.name
  dvc/objects/fs/path.py
Labels: performance

#7768 fs: path: don't overuse parts
  dvc/objects/fs/path.py
Labels: refactoring, performance, skip-changelog

#7721 exp queue: Add two command `queue remove` and `queue kill`
  dvc/cli/parser.py
  dvc/commands/queue/__init__.py
  dvc/commands/queue/kill.py
  dvc/commands/queue/remove.py
  tests/unit/command/test_queue.py
Labels: A: experiments, A: cli, A: task-queue

#7759 exp queue: Add two command queue start and stop
  dvc/commands/queue/__init__.py
  dvc/commands/queue/start.py
  dvc/commands/queue/stop.py
  tests/unit/command/test_queue.py
Labels: A: cli, A: task-queue

#7770 dvc.objects: fix typing imports
  dvc/data/checkout.py
  dvc/data/db/index.py
Labels: refactoring, skip-changelog, A: object-storage

#7771 dvc.objects: use stub ignore in dvc.objects/dvc.data
  dvc/cli/__init__.py
  dvc/data/checkout.py
  dvc/data/stage.py
  dvc/dependency/repo.py
  dvc/exceptions.py
  dvc/objects/_ignore.py
  dvc/objects/state.py
  dvc/objects/utils.py
  dvc/output.py
  dvc/repo/diff.py
  tests/func/test_external_repo.py
  tests/func/test_ignore.py
  tests/unit/cli/test_main.py
Labels: refactoring, skip-changelog, A: object-storage

#7772 dvc.data: use own internal error instead of DvcException
  dvc/data/db/local.py
  dvc/data/transfer.py
  dvc/data/tree.py
  dvc/data_cloud.py
  dvc/output.py
  tests/func/test_remove.py
Labels: A: object-storage

#7778 fs/data: move repo related utils to dvc
  dvc/data/db/__init__.py
  dvc/data/reference.py
  dvc/fs/__init__.py
  dvc/objects/fs/__init__.py
  dvc/odbmgr.py
  dvc/repo/__init__.py
  dvc/repo/experiments/executor/ssh.py
  dvc/testing/fixtures.py
  dvc/testing/test_workspace.py
  tests/func/test_add.py
  tests/func/test_get.py
  tests/func/test_import.py
  tests/func/test_odb.py
  tests/func/test_repo.py
  tests/unit/stage/test_cache.py
Labels: refactoring, skip-changelog, A: object-storage

#7780 data.checkout: remove dependency on DVC; prompts and DvcException
  dvc/data/checkout.py
  dvc/data/slow_link_detection.py
  dvc/dependency/repo.py
  dvc/output.py
  tests/unit/remote/test_slow_link_detection.py
Labels: refactoring, skip-changelog, A: data-management

#7781 objects: use separate Tqdm implementation
  dvc/data/_progress.py
  dvc/data/checkout.py
  dvc/data/db/reference.py
  dvc/data/stage.py
  dvc/data/transfer.py
  dvc/fs/_callback.py
  dvc/fs/callbacks.py
  dvc/fs/data.py
  dvc/fs/dvc.py
  dvc/objects/_tqdm.py
  dvc/objects/db.py
  dvc/objects/fs/base.py
  dvc/objects/fs/callbacks.py
  dvc/objects/fs/generic.py
  dvc/objects/fs/implementations/http.py
  dvc/objects/fs/implementations/ssh.py
  dvc/objects/fs/utils.py
  dvc/objects/hash.py
  dvc/output.py
  dvc/repo/get.py
  dvc/stage/cache.py
  dvc/utils/fs.py
  tests/func/test_fs.py
Labels: refactoring, skip-changelog, A: object-storage, A: data-management

#7783 data/objects: reduce log levels in dvc-objects and dvc-data
  dvc/data/gc.py
  dvc/data/status.py
  dvc/data/transfer.py
  dvc/data/tree.py
  dvc/data_cloud.py
  dvc/objects/db.py
Labels: refactoring, skip-changelog, A: object-storage, A: data-management

#7784 tests: restructure some tests for objects/data
  tests/func/data/__init__.py
  tests/func/data/db/__init__.py
  tests/func/data/db/test_index.py
  tests/func/objects/test_hash.py
  tests/unit/data/__init__.py
  tests/unit/data/db/__init__.py
  tests/unit/data/db/test_local.py
  tests/unit/data/test_tree.py
  tests/unit/objects/test_cache.py
  tests/unit/objects/test_hash.py
  tests/unit/objects/test_hash_stream.py
Labels: refactoring, skip-changelog, A: object-storage, A: data-management

#7794 dvc: prune unused utils and redundant tests, remove some deps
  dvc/testing/test_remote.py
  dvc/utils/__init__.py
  dvc/utils/conversions.py
  dvc/utils/fs.py
  setup.cfg
  tests/func/test_checkout.py
  tests/func/test_fs.py
  tests/func/utils/test_fs.py
  tests/unit/utils/test_conversions.py
  tests/unit/utils/test_fs.py
  tests/unit/utils/test_utils.py
Labels: refactoring, skip-changelog

#7750 Catch correct exception class in params.show()
  dvc/repo/params/show.py
Labels: bugfix, git

#7797 fix linter issue
  dvc/fs/data.py
  dvc/fs/dvc.py
Labels: ci

#7798 formatting/isort: consider dvc-render as a known first party for ordering imports
  dvc/commands/plots.py
  dvc/render/match.py
  dvc/repo/plots/__init__.py
  pyproject.toml
Labels: ci, skip-changelog

#7739 dvc.stage.cache: fix typo, was using src filesystem to transfer
  dvc/stage/cache.py
  dvc/testing/test_run_cache.py
Labels: c1-quick-fix, bugfix, A: run-cache, release-blocker

#7801 tests: move run cache test to test_remote
  dvc/testing/test_remote.py
  dvc/testing/test_run_cache.py
Labels: testing, skip-changelog

#7803 dag: mermaid: Use quotation marks to escape node name.
  dvc/commands/dag.py
  tests/unit/command/test_dag.py
Labels: bugfix

#7799 exp: implement `celery_queue.shutdown(kill=...)`
  dvc/repo/experiments/queue/base.py
  dvc/repo/experiments/queue/local.py
  tests/unit/repo/experiments/queue/test_local.py
Labels: A: experiments

#7826 dvc: drop python 3.7
  .github/workflows/benchmarks.yaml
  .github/workflows/packages.yaml
  .github/workflows/tests.yaml
  dvc/commands/experiments/init.py
  dvc/info.py
  dvc/proc/manager.py
  dvc/testing/fixtures.py
  dvc/utils/strictyaml.py
  setup.cfg
  tests/dir_helpers.py
  tests/func/machine/test_machine_config.py
  tests/func/test_ignore.py
  tests/integration/plots/test_json.py
  tests/unit/command/test_experiments.py
  tests/unit/command/test_machine.py
  tests/unit/fs/test_ssh.py
  tests/unit/remote/test_http.py
  tests/unit/test_analytics.py
  tests/unit/utils/test_collections.py
Labels: refactoring

#7827 testing: use shutil.copytree with dirs_exist_ok
  dvc/testing/fixtures.py
Labels: refactoring, testing, skip-changelog

#7820 plots: Pass `templates_dir` to `match_renderers`.
  dvc/commands/plots.py
  dvc/render/match.py
  dvc/repo/plots/__init__.py
  tests/unit/command/test_plots.py
  tests/unit/render/test_match.py
Labels: bugfix, A: plots
