Repository iterative/dvc, pull requests merged in 2022-08, with the labels that each got.

#8075 build: add pyinstaller hooks for dvc-task and celery
  scripts/pyinstaller/hooks/hook-celery.py
  scripts/pyinstaller/hooks/hook-dvc_task.py
Labels: build, bugfix

#8073 plots: remove legacy code from verify_metrics
  dvc/output.py
Labels: refactoring, maintenance, A: metrics

#8086 dvc-task: update to 0.1.2
  setup.cfg
Labels: maintenance

#8069 api: Fix params_show when stage has no params
  dvc/repo/params/show.py
  tests/func/api/test_params.py
Labels: bugfix, A: api

#8067 exp run: Use hydra for parsing `--set-param`.
  dvc/repo/experiments/queue/base.py
  dvc/repo/experiments/run.py
  dvc/utils/_benedict.py
  dvc/utils/cli_parse.py
  dvc/utils/collections.py
  dvc/utils/hydra.py
  setup.cfg
  tests/func/experiments/conftest.py
  tests/func/experiments/test_experiments.py
  tests/func/utils/test_hydra.py
  tests/unit/utils/test_cli_parse.py
  tests/unit/utils/test_collections.py
Labels: A: experiments, feature

#8105 fix logic for unlock on unlocked lock calls
  dvc/lock.py
  tests/func/test_lock.py
Labels: bugfix

#8099 queue status: ERROR: Invalid experiment
  dvc/repo/experiments/queue/celery.py
  tests/unit/repo/experiments/queue/test_local.py
Labels: A: experiments, bugfix, A: task-queue

#8104 queue status: show final experiment name
  dvc/repo/experiments/queue/base.py
  tests/unit/repo/experiments/queue/test_local.py
Labels: enhancement

#8107 data status: handle path joining properly for tree leaves/items
  dvc/repo/data.py
Labels: bugfix, A: cli, A: status

#8108 Add flaky to a queue related test.
  tests/func/experiments/test_queue.py
Labels: testing, A: task-queue

#8119 exp run: account for repo root when staging git-deps
  dvc/repo/reproduce.py
  tests/unit/repo/test_reproduce.py
Labels: A: experiments, bugfix, A: pipelines

#8136 deps: bump dvc-http to 0.0.2
  setup.cfg
Labels: dependencies

#8142 pyinstaller: Restrict to 5.0
  scripts/build-requirements.txt
Labels: build

#8146 Add python version label to the readme
  README.rst
Labels: skip-changelog

#8153 deps: bump dvc-data to 0.1.22 and dvc-s3 to 0.0.2
  setup.cfg
Labels: skip-changelog

#8154 build: bump ruby to 2.6
  .github/workflows/packages.yaml
Labels: build, skip-changelog

#8156 ci: refactor binary executable building workflow
  .github/workflows/packages.yaml
  scripts/build.py
Labels: build, ci, skip-changelog

#8157 ci: drop __token__, it's the default
  .github/workflows/packages.yaml
Labels: build, ci

#8152 metrics: show: Fix show from subdir.
  dvc/repo/metrics/show.py
  tests/func/metrics/test_show.py
Labels: bugfix, A: metrics

#8185 data status: test cleanup and improvements
  dvc/repo/data.py
  tests/func/test_data_status.py
  tests/unit/command/test_data_status.py
Labels: skip-changelog

#8186 tests: mark exp queue func tests xfail
  tests/func/experiments/test_queue.py
Labels: ci, maintenance

#8166 api: Fix `params_show` for untracked targets.
  dvc/repo/params/show.py
  tests/func/api/test_params.py
Labels: bugfix, A: api

#8167 api: Add details for`params_show` `stages` syntax.
  dvc/api/params.py
  tests/func/api/test_params.py
Labels: ui, A: api

#8189 data status: remove --withdirs, show unknowns in CLI
  dvc/commands/data.py
  dvc/repo/data.py
  tests/func/test_data_status.py
  tests/unit/command/test_data_status.py
Labels: enhancement

#8201 info: Include subprojects.
  dvc/info.py
  tests/func/test_version.py
  tests/unit/test_info.py
Labels: enhancement, ui

#8206 info: skip missing subprojects
  dvc/info.py
  tests/func/test_version.py
Labels: skip-changelog
