Repository iterative/dvc, pull requests merged in 2022-10, with the labels that each got.

#8389 deps: bump dvc-data to 0.14.0
  dvc/repo/push.py
  setup.cfg
Labels: dependencies

#8395 logger: init logging config before colorama
  dvc/logger.py
Labels: maintenance

#8416 deps: bump dvc-data to 0.17.1
  setup.cfg
Labels: dependencies

#8432 deps: bump dvc-data to 0.18.0
  dvc/fs/callbacks.py
  dvc/output.py
  dvc/repo/checkout.py
  setup.cfg
Labels: maintenance, dependencies

#8412 plots: allow definition of plots section as list
  dvc/repo/plots/__init__.py
  dvc/schema.py
  tests/func/test_dvcfile.py
Labels: A: plots

#8452 tests: Remove test_ssh
  tests/unit/fs/test_ssh.py
Labels: testing, skip-changelog

#8454 _debug: minor refactor on debugtools
  dvc/_debug.py
  tests/unit/command/test_debug.py
Labels: skip-changelog

#8455 debug: add --show-stack/--ss flag
  dvc/_debug.py
Labels: skip-changelog, A: debug

#8453 exp show: Use batch call on `scm.describe`
  dvc/commands/experiments/ls.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/show.py
  setup.cfg
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_show.py
Labels: performance, A: experiments

#8436 Give lock acquiring more time in concurrency situation.
  dvc/repo/experiments/queue/base.py
Labels: A: experiments, A: executors, A: task-queue, bug

#8369 Use celery status as the exp show status
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/show.py
  tests/func/experiments/test_show.py
Labels: ui, A: experiments, bug

#8495 ci: push package to test.pypi.org
  .github/workflows/packages.yaml
  pyproject.toml
  scripts/build_package.sh
Labels: skip-changelog
