Repository iterative/dvc, pull requests merged in 2022-04, with the labels that each got.

#7554 erepo: include exp refs in clones
  dvc/external_repo.py
  dvc/repo/experiments/utils.py
  dvc/scm.py
  tests/func/experiments/test_remote.py
Labels: A: experiments, bugfix

#7572 exp show: prefer exp names for experiments
  dvc/repo/experiments/show.py
Labels: ui, A: experiments, bugfix

#7583 fs: get rid of CallbackMixin in azure/gs/hdfs/webhdfs
  dvc/fs/azure.py
  dvc/fs/fsspec_wrapper.py
  dvc/fs/gs.py
  dvc/fs/hdfs.py
  dvc/fs/webhdfs.py
Labels: refactoring, skip-changelog

#7586 fs: move NoDirectoriesMixin to http filesystem
  dvc/fs/fsspec_wrapper.py
  dvc/fs/http.py
Labels: fs: http

#7595 completion: fix dvc exp completion on zsh/bash
  dvc/commands/completion.py
Labels: completion

#7600 bump pydrive: improves and fixes thread safety
  setup.cfg
Labels: A: object-storage, fs: gdrive

#7599 completion: decouple completion related stuff from command
  dvc/cli/__init__.py
  dvc/cli/completion.py
  dvc/commands/add.py
  dvc/commands/cache.py
  dvc/commands/check_ignore.py
  dvc/commands/checkout.py
  dvc/commands/commit.py
  dvc/commands/completion.py
  dvc/commands/daemon.py
  dvc/commands/data_sync.py
  dvc/commands/diff.py
  dvc/commands/experiments/apply.py
  dvc/commands/experiments/diff.py
  dvc/commands/experiments/push.py
  dvc/commands/experiments/run.py
  dvc/commands/experiments/show.py
  dvc/commands/freeze.py
  dvc/commands/get.py
  dvc/commands/get_url.py
  dvc/commands/imp.py
  dvc/commands/imp_url.py
  dvc/commands/ls/__init__.py
  dvc/commands/metrics.py
  dvc/commands/move.py
  dvc/commands/params.py
  dvc/commands/plots.py
  dvc/commands/remove.py
  dvc/commands/repro.py
  dvc/commands/stage.py
  dvc/commands/unprotect.py
  dvc/commands/update.py
Labels: enhancement, refactoring, A: cli

#7598 stage/exp list: alias `--names-only` to `--name-only`
  dvc/commands/experiments/ls.py
  dvc/commands/stage.py
  tests/unit/command/test_compat_flag.py
  tests/unit/command/test_experiments.py
Labels: enhancement, ui, A: cli

#7574 exp show: lockless behavior
  dvc/commands/experiments/show.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/show.py
  tests/unit/command/test_experiments.py
Labels: external-product, A: experiments, bugfix

#7602 executors: add support for cancel_futures=True in Python<3.9
  dvc/utils/threadpool.py
  tests/unit/utils/test_executors.py
Labels: refactoring, skip-changelog

#7383 dag: Add `--mermaid` and `--md` option.
  dvc/commands/dag.py
  tests/unit/command/test_compat_flag.py
  tests/unit/command/test_dag.py
Labels: feature, A: pipelines

#7363 tests: add test for dvc.api.open with remote
  tests/func/test_api.py
Labels: testing, skip-changelog

#7608 fs: make localfs fsspec-compliant
  dvc/fs/fsspec_wrapper.py
  dvc/fs/local.py
  tests/func/test_add.py
Labels: refactoring, skip-changelog, fs: local

#7588 gitfs: add regression test for broken stage.collect on gitfs when cwd != repo_root
  tests/func/test_api.py
  tests/func/test_used_objs.py
Labels: testing

#7606 render.match: Skip errored revisions in `get_files`
  dvc/render/match.py
  tests/unit/render/test_match.py
Labels: bugfix

#7612 fs: unify fs.base.FileSystem with FSSpecWrapper
  dvc/data/db/reference.py
  dvc/data/reference.py
  dvc/data/stage.py
  dvc/fs/azure.py
  dvc/fs/base.py
  dvc/fs/dvc.py
  dvc/fs/fsspec_wrapper.py
  dvc/fs/gdrive.py
  dvc/fs/git.py
  dvc/fs/gs.py
  dvc/fs/hdfs.py
  dvc/fs/http.py
  dvc/fs/local.py
  dvc/fs/memory.py
  dvc/fs/oss.py
  dvc/fs/repo.py
  dvc/fs/s3.py
  dvc/fs/ssh.py
  dvc/fs/webdav.py
  dvc/fs/webhdfs.py
  dvc/ignore.py
  dvc/objects/db.py
  dvc/objects/file.py
  dvc/repo/collect.py
  dvc/repo/experiments/executor/ssh.py
  tests/unit/remote/test_base.py
Labels: refactoring

#7624 dvc.objects: add callbacks for listing and estimating hashes
  dvc/data/_progress.py
  dvc/data/db/local.py
  dvc/data/gc.py
  dvc/data/status.py
  dvc/objects/db.py
  tests/unit/remote/test_base.py
Labels: refactoring, A: data-management

#7625 fs: rename getsize to size
  dvc/data/stage.py
  dvc/data/tree.py
  dvc/fs/base.py
  dvc/fs/utils.py
  dvc/utils/__init__.py
  tests/func/test_fs.py
Labels: refactoring, skip-changelog

#7629 fs.upload/download: simplify, remove unused kwargs, callbacks
  dvc/data/stage.py
  dvc/fs/_callback.py
  dvc/fs/base.py
  dvc/fs/utils.py
  dvc/progress.py
  dvc/utils/fs.py
Labels: refactoring, ui

#7627 dvc.objects: add callbacks for listing and estimating hashes
  dvc/data/_progress.py
  dvc/data/db/local.py
  dvc/data/gc.py
  dvc/data/status.py
  dvc/objects/db.py
  tests/unit/remote/test_base.py
Labels: refactoring, A: data-management

#7634 build: try fixing exe package
  dvc/data/_progress.py
Labels: build, skip-changelog

#7643 `plots`: Fix repo with removed plots
  dvc/render/convert.py
  setup.cfg
  tests/integration/plots/test_json.py
Labels: external-product, bugfix, release-blocker

#7632 scm: fix progress bar, show progress and repo being cloned
  dvc/scm.py
Labels: enhancement, refactoring, ui

#7646 fs.s3: remove custom put_file/get_file
  dvc/fs/s3.py
Labels: refactoring, fs: s3

#7645 fs.ssh: remove unused vars
  dvc/fs/ssh.py
  dvc/machine/backend/terraform.py
  tests/unit/fs/test_ssh.py
Labels: refactoring, fs: ssh

#7647 fs.ossfs: remove unused var COPY_POLL_SECONDS
  dvc/fs/oss.py
Labels: refactoring, skip-changelog, fs: oss

#7648 fs: remove unused CHUNK_SIZE var
  dvc/data/stage.py
  dvc/fs/base.py
Labels: refactoring, skip-changelog

#7617 dvc.stage: log time duration on stage collection walk in verbose mode
  .dvcignore
  .gitignore
  dvc/repo/index.py
  dvc/repo/stage.py
Labels: enhancement, skip-changelog

#7653 fs.put_file: don't require size to be passed
  dvc/fs/base.py
Labels: refactoring, skip-changelog

#7654 fs.put_file: fix function signature for size
  dvc/fs/http.py
  dvc/fs/ssh.py
Labels: skip-changelog

#7659 repofs: only use dvcfs when --dvc-only is specified
  dvc/fs/repo.py
  dvc/repo/ls.py
Labels: optimize

#7649 fs.utils: add atomic upload function
  dvc/data/checkout.py
  dvc/data/stage.py
  dvc/fs/base.py
  dvc/fs/local.py
  dvc/fs/ssh.py
  dvc/fs/utils.py
  dvc/objects/db.py
  dvc/repo/experiments/executor/ssh.py
  dvc/stage/cache.py
  tests/func/objects/db/test_index.py
  tests/func/test_fs.py
  tests/func/test_remote.py
Labels: refactoring, skip-changelog
