Repository iterative/dvc, pull requests merged in 2022-02, with the labels that each got.

#7108 plots: make templates generation explicit
  dvc/commands/plots.py
  dvc/repo/init.py
  dvc/repo/plots/template.py
  tests/unit/command/test_plots.py
  tests/unit/repo/plots/test_templates.py
Labels: enhancement, A: plots

#7315 `exp show`: Sort `deps` columns.
  dvc/commands/experiments/show.py
  tests/func/experiments/test_show.py
Labels: skip-changelog

#7333 Delete scripts/schema directory
  scripts/schema/dvc-yaml.json
Labels: skip-changelog

#7345 dvcfs: use info() instead of metadata()
  dvc/api.py
  dvc/fs/_metadata.py
  dvc/fs/dvc.py
  dvc/fs/repo.py
  dvc/repo/diff.py
  dvc/repo/ls.py
  tests/unit/fs/test_repo_info.py
  tests/unit/fs/test_repo_metadata.py
Labels: refactoring, skip-changelog

#7346 repofs: don't use outs
  dvc/fs/repo.py
Labels: refactoring, skip-changelog

#7347 ls: don't use outs
  dvc/repo/ls.py
Labels: refactoring, skip-changelog

#7355 dvcfs: use paths relative to the repo root
  dvc/api.py
  dvc/fs/dvc.py
  dvc/fs/repo.py
  tests/func/test_fs.py
  tests/unit/fs/test_dvc.py
  tests/unit/fs/test_repo.py
Labels: refactoring, skip-changelog

#7264 exp show: handle extending/renaming of metrics/params.
  dvc/commands/experiments/show.py
  tests/func/experiments/test_show.py
Labels: bugfix

#7399 fs: git: move isfile/walk to fsspec wrapper
  dvc/fs/fsspec_wrapper.py
  dvc/fs/git.py
Labels: refactoring, skip-changelog

#7401 fs: walk: get rid of onerror
  dvc/fs/base.py
  dvc/fs/dvc.py
  dvc/fs/fsspec_wrapper.py
  dvc/fs/local.py
  dvc/fs/repo.py
  dvc/repo/ls.py
  tests/unit/fs/test_dvc.py
  tests/unit/fs/test_repo.py
Labels: refactoring, skip-changelog

#7396 exp init: refactor and simplify interactive mode
  dvc/repo/experiments/init.py
  tests/func/experiments/test_init.py
Labels: enhancement, refactoring, A: experiments, A: cli

#7339 Remove outdated SSH default jobs.
  dvc/commands/add.py
  dvc/commands/data_sync.py
  dvc/commands/gc.py
  dvc/commands/get.py
  dvc/commands/get_url.py
  dvc/commands/imp.py
  dvc/commands/imp_url.py
  dvc/commands/update.py
Labels: maintenance, skip-changelog
