Repository iterative/dvc, pull requests merged in 2022-07, with the labels that each got.

#7477 Initial support for flexible plots
  dvc/commands/plots.py
  dvc/output.py
  dvc/render/__init__.py
  dvc/render/convert.py
  dvc/render/converter/__init__.py
  dvc/render/converter/image.py
  dvc/render/converter/vega.py
  dvc/render/match.py
  dvc/render/vega_converter.py
  dvc/repo/plots/__init__.py
  dvc/schema.py
  dvc/utils/plots.py
  setup.cfg
  tests/func/plots/test_diff.py
  tests/func/plots/test_modify.py
  tests/func/plots/test_show.py
  tests/func/test_live.py
  tests/integration/plots/conftest.py
  tests/integration/plots/test_json.py
  tests/integration/plots/test_plots.py
  tests/integration/plots/test_repo_plots_api.py
  tests/unit/command/test_plots.py
  tests/unit/render/test_convert.py
  tests/unit/render/test_image_converter.py
  tests/unit/render/test_match.py
  tests/unit/render/test_vega_converter.py
  tests/unit/test_plots.py
  tests/utils/plots.py
Labels: enhancement, feature, A: plots

#7958 Help text for `dvc update`
  dvc/commands/update.py
Labels: ui

#7907 parsing: Support dict unpacking in `cmd`.
  dvc/config_schema.py
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/parsing/interpolate.py
  tests/func/parsing/test_errors.py
  tests/func/parsing/test_interpolated_entry.py
Labels: feature, A: templating

#7938 api: params_show: Raise exception if no params found.
  dvc/api/params.py
  tests/func/api/test_params.py
Labels: ui, A: api

#7965 metrics: support TOML files
  dvc/repo/metrics/show.py
  tests/func/metrics/test_show.py
Labels: feature, A: metrics

#7992 deps: bump dvc-data to 0.0.20
  dvc/cli/__init__.py
  dvc/dependency/repo.py
  dvc/output.py
  dvc/repo/diff.py
  setup.cfg
  tests/func/test_add.py
  tests/func/test_external_repo.py
  tests/func/test_ignore.py
  tests/func/test_remote.py
  tests/unit/cli/test_main.py
  tests/unit/data/db/test_local.py
  tests/unit/fs/test_data.py
  tests/unit/fs/test_dvc.py
Labels: dependencies

#7998 tests: limit printed durations to 50
  tests/__main__.py
Labels: testing, skip-changelog

#8021 deps: bump dvc-data to 0.0.24
  setup.cfg
Labels: dependencies

#8005 readme: How it works (2)
  README.rst
Labels: product

#8000 exp: init: Use `persist: true` if checkpoint.
  dvc/repo/experiments/init.py
  dvc/stage/utils.py
  tests/func/experiments/test_init.py
Labels: ui, A: experiments

#8041 utils: remove dead code
  dvc/utils/__init__.py
Labels: skip-changelog

#8032 exp branch: update -h stdout
  dvc/commands/experiments/branch.py
Labels: enhancement, ui, A: experiments, A: cli

#8042 readme: link to docs for related tech
  README.rst
Labels: skip-changelog

#8050 data status: add spinners during diff
  dvc/repo/data.py
Labels: ui

#8063 queue: missing `f` format for the error message.
  dvc/repo/experiments/queue/celery.py
Labels: ui, A: experiments, A: task-queue
