Repository iterative/dvc, pull requests merged in 2022-12, with the labels that each got.

#8648 deps: bump dvc-data to 0.28.3
  pyproject.toml
Labels: maintenance

#8644 stage add: don't fail if unable to create .gitignore
  dvc/repo/stage.py
Labels: bugfix

#8662 remote: disable gc/status for versioned remotes
  dvc/data_cloud.py
Labels: A: data-sync, A: cloud-versioning

#8672 worktree: fix default worktree remote/odb exception
  dvc/data_cloud.py
Labels: bugfix, A: data-sync, A: cloud-versioning

#8659 exp: Generate a human-readable name beforehand.
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/queue/base.py
  dvc/repo/experiments/utils.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_show.py
  tests/func/experiments/test_utils.py
Labels: A: experiments, feature

#8679 Reset all indices on the brancher iteration
  dvc/repo/__init__.py
  dvc/repo/brancher.py
Labels: bugfix, A: Repo

#8683 Bump dvclive lower bound
  pyproject.toml
Labels: skip-changelog, A: live, release-blocker

#8694 exp: remove a few experiments names
  dvc/repo/experiments/utils.py
Labels: skip-changelog

#8695 bump DVCLive lower bound
  pyproject.toml
Labels: skip-changelog

#8703 plots: fix regressions to top-level plots
  dvc/render/converter/vega.py
  tests/unit/render/test_vega_converter.py
Labels: bugfix, A: plots

#8688 Add post_to_studio `start` and `done` calls.
  dvc/repo/experiments/queue/workspace.py
  pyproject.toml
  tests/func/experiments/test_utils.py
Labels: product, feature

#8726 tests: Fix flaky `test_show_only_changed`.
  tests/func/experiments/test_show.py
Labels: testing, skip-changelog

#8608 `exp run --run-all`: re-enable --jobs concurrency
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/queue/celery.py
  tests/unit/command/test_queue.py
  tests/unit/repo/experiments/conftest.py
Labels: A: experiments, A: task-queue

#8668 Make temp dir executed checkpoint experiment return result to workspace.
  dvc/repo/experiments/queue/tempdir.py
  dvc/repo/reproduce.py
  dvc/stage/exceptions.py
  dvc/stage/monitor.py
  dvc/stage/run.py
  tests/func/experiments/conftest.py
  tests/func/experiments/test_checkpoints.py
  tests/unit/repo/experiments/conftest.py
Labels: A: experiments, bugfix

#8741 `post_live_metrics`: Pass `params` on `start` event.
  dvc/repo/experiments/queue/workspace.py
  dvc/repo/experiments/utils.py
  tests/func/experiments/test_utils.py
Labels: product, feature

#8746 scm: add cause of clone errors
  dvc/commands/get.py
  dvc/commands/imp.py
  dvc/scm.py
Labels: ui

#8657 Use `SIGINT` as the default signal in `queue kill`
  dvc/commands/queue/kill.py
  dvc/repo/experiments/queue/celery.py
  dvc/stage/run.py
  pyproject.toml
  tests/unit/command/test_queue.py
  tests/unit/repo/experiments/queue/test_celery.py
Labels: enhancement, A: experiments, A: task-queue
