Repository iterative/dvc, pull requests merged in 2022-09, with the labels that each got.

#8223 output: support version ID
  dvc/config_schema.py
  dvc/output.py
  tests/unit/output/test_output.py
Labels: enhancement, A: data-management

#8247 dvc.yaml: preserve outputs' desc on rewrites/updates to the stage
  dvc/output.py
  tests/func/test_dvcfile.py
Labels: bugfix

#8210 add support for foreach target
  dvc/commands/stage.py
  dvc/dvcfile.py
  dvc/repo/remove.py
  dvc/repo/reproduce.py
  dvc/repo/stage.py
  tests/func/test_stage_load.py
Labels: feature, A: cli

#8255 deps: bump dvc-data to 0.6.1
  dvc/cli/__init__.py
  dvc/data_cloud.py
  dvc/dependency/repo.py
  dvc/odbmgr.py
  dvc/output.py
  dvc/repo/data.py
  dvc/repo/diff.py
  dvc/repo/gc.py
  dvc/stage/cache.py
  setup.cfg
  tests/func/data/db/test_index.py
  tests/func/test_add.py
  tests/func/test_checkout.py
  tests/func/test_data_cloud.py
  tests/func/test_external_repo.py
  tests/func/test_gc.py
  tests/func/test_ignore.py
  tests/func/test_import.py
  tests/func/test_odb.py
  tests/func/test_remote.py
  tests/unit/cli/test_main.py
  tests/unit/data/db/test_local.py
  tests/unit/fs/test_data.py
  tests/unit/fs/test_dvc.py
  tests/unit/remote/test_index.py
  tests/unit/remote/test_remote.py
Labels: dependencies

#8232 add metadata fields: label, type to data
  dvc/annotations.py
  dvc/commands/add.py
  dvc/commands/imp.py
  dvc/commands/imp_url.py
  dvc/output.py
  dvc/repo/add.py
  dvc/repo/imp_url.py
  dvc/schema.py
  dvc/stage/__init__.py
  dvc/stage/serialize.py
  dvc/stage/utils.py
  tests/func/test_add.py
  tests/func/test_commit.py
  tests/func/test_dvcfile.py
  tests/func/test_import.py
  tests/func/test_import_url.py
  tests/func/test_run_single_stage.py
  tests/func/test_stage.py
  tests/unit/command/test_add.py
  tests/unit/command/test_annotations_flags.py
  tests/unit/command/test_imp.py
  tests/unit/command/test_imp_url.py
  tests/unit/output/test_annotations.py
  tests/utils/asserts.py
Labels: feature, A: data-management

#8250 Add support for custom metadata
  dvc/annotations.py
  dvc/cli/actions.py
  dvc/commands/add.py
  dvc/commands/imp.py
  dvc/commands/imp_url.py
  dvc/output.py
  dvc/repo/imp_url.py
  tests/func/test_add.py
  tests/func/test_commit.py
  tests/func/test_import.py
  tests/func/test_import_url.py
  tests/func/test_run_single_stage.py
  tests/func/test_stage.py
  tests/unit/command/test_add.py
  tests/unit/command/test_annotations_flags.py
  tests/unit/command/test_imp.py
  tests/unit/command/test_imp_url.py
  tests/unit/output/test_annotations.py
Labels: feature, A: data-management

#8251 add metadata support to dvc.yaml
  dvc/output.py
  dvc/schema.py
  dvc/stage/serialize.py
  tests/func/test_dvcfile.py
Labels: feature

#8275 data status: fix type hints
  dvc/repo/data.py
Labels: skip-changelog

#8276 dvcfs: remove config
  dvc/fs/dvc.py
Labels: enhancement

#8252 data ls: new command to show metadata with outputs
  dvc/cli/actions.py
  dvc/commands/data.py
  dvc/repo/data.py
  tests/func/test_data_ls.py
  tests/unit/command/test_compat_flag.py
  tests/unit/command/test_data_ls.py
Labels: feature, A: data-management

#8277 dvcfs: remove unused config code for opening a repo, change signature
  dvc/fs/dvc.py
Labels: skip-changelog

#8187 exp run: Support hydra basic sweeper.
  dvc/repo/experiments/run.py
  dvc/utils/hydra.py
  tests/func/experiments/test_set_params.py
  tests/func/utils/test_hydra.py
Labels: A: experiments, feature

#8290 deps: remove unused mock dep
  setup.cfg
Labels: skip-changelog

#8295 dvcfs: default open to binary mode
  dvc/fs/dvc.py
Labels: skip-changelog

#8289 schema: add strict schema validation for top-level plots
  dvc/schema.py
Labels: skip-changelog

#8296 dvcfs: add fsspec-compliance tests
  dvc/fs/dvc.py
  dvc/testing/test_api.py
Labels: testing, bugfix

#8306 dvcfs: prevent opening file object in write mode
  dvc/fs/dvc.py
Labels: A: api

#8305 deps: bump dvc-azure to 2.20.4
  setup.cfg
Labels: maintenance

#8307 dvcfs: rename DvcFileSystem to DVCFileSystem
  dvc/api/__init__.py
  dvc/dependency/repo.py
  dvc/fs/__init__.py
  dvc/fs/dvc.py
  dvc/repo/__init__.py
  dvc/repo/collect.py
  dvc/repo/diff.py
  dvc/repo/ls.py
  dvc/repo/metrics/show.py
  dvc/repo/plots/__init__.py
  dvc/testing/test_api.py
  setup.cfg
  tests/unit/fs/test_data.py
  tests/unit/fs/test_dvc.py
  tests/unit/fs/test_dvc_info.py
Labels: A: api

#8313 deps: bump dvc-data to 0.10.0
  dvc/testing/test_remote.py
  setup.cfg
  tests/func/test_add.py
  tests/func/test_data_cloud.py
  tests/func/test_ignore.py
  tests/func/test_odb.py
  tests/func/test_remote.py
  tests/func/test_run_single_stage.py
Labels: dependencies

#8320 use native concurrency
  .github/workflows/benchmarks.yaml
  .github/workflows/tests.yaml
Labels: skip-changelog

#8321 cli: rename cli util, hide `data ls` from the help
  dvc/cli/utils.py
  dvc/commands/data.py
  dvc/commands/experiments/__init__.py
Labels: skip-changelog

#8323 lint: pin astroid version
  setup.cfg
Labels: skip-changelog

#8324 push: use update_pipeline=False for cloud versioning
  dvc/repo/push.py
Labels: bug

#8330 deps: bump dvc-data to 0.10.1
  setup.cfg
Labels: maintenance

#8333 deps: bump dvc-http to 2.27.2
  setup.cfg
Labels: maintenance, fs: http

#8335 fs.callback.RichCallback: add transient support
  dvc/fs/callbacks.py
Labels: skip-changelog

#8332 document dvcfs
  dvc/fs/dvc.py
Labels: skip-changelog

#8308 hydra: Fix sweeps on Defaults List.
  dvc/utils/hydra.py
  tests/func/utils/test_hydra.py
Labels: A: experiments, bugfix, A: params

#8351 Solve the on_diverged function not executed error.
  dvc/repo/experiments/executor/base.py
Labels: A: experiments, bug

#8352 cli: add help for foreach
  dvc/commands/checkout.py
  dvc/commands/commit.py
  dvc/commands/dag.py
  dvc/commands/data_sync.py
  dvc/commands/repro.py
Labels: skip-changelog

#8282 vscode: support flexible plots
  dvc/commands/plots.py
  dvc/render/convert.py
  dvc/render/converter/vega.py
  tests/integration/plots/test_plots.py
  tests/unit/command/test_plots.py
  tests/unit/render/test_convert.py
  tests/unit/render/test_match.py
  tests/unit/render/test_vega_converter.py
Labels: product, A: plots

#8375 fs: test and slightly refactor get_fs_config()
  dvc/fs/__init__.py
  dvc/info.py
  tests/unit/fs/test_fs.py
Labels: maintenance, skip-changelog, fs: local

#8380 config: wrap UnicodeDecodeErrors on load
  dvc/config.py
  tests/unit/test_config.py
Labels: maintenance, bugfix
