Repository iterative/dvc, pull requests merged in 2022-01, with the labels that each got.

#7219 Update show.py
  dvc/command/experiments/show.py
Labels: skip-changelog

#7223 ui: remove `None` in CellT type
  dvc/command/machine.py
  dvc/ui/table.py
Labels: refactoring, skip-changelog

#7222 odb: pin index pickle protocol version
  dvc/objects/db/index.py
Labels: bugfix

#7226 ls: handle broken symlink
  dvc/repo/ls.py
  tests/func/test_ls.py
Labels: bugfix

#7221 output: don't raise RemoteCacheRequiredError on instantiation, make it lazy
  dvc/output.py
  tests/func/test_remote.py
Labels: refactoring, skip-changelog

#6857 test: fix test failure in case of different default branch
  .github/workflows/tests.yaml
  dvc/testing/tmp_dir.py
  tests/basic_env.py
  tests/conftest.py
  tests/dir_helpers.py
  tests/func/metrics/test_diff.py
  tests/func/params/test_diff.py
  tests/func/test_diff.py
  tests/func/test_import.py
  tests/unit/fs/test_ssh.py
Labels: testing, ci, skip-changelog, bugfix

#7007 render: vega: data processing outside of renderers
  dvc/command/live.py
  dvc/command/plots.py
  dvc/render/base.py
  dvc/render/data.py
  dvc/render/utils.py
  dvc/render/vega.py
  tests/unit/command/test_plots.py
  tests/unit/render/test_data.py
  tests/unit/render/test_render.py
  tests/unit/render/test_vega.py
  tests/unit/repo/plots/test_templates.py
Labels: external-product, skip-changelog, A: plots

#7248 odb: move gc into a separate function
  dvc/data/gc.py
  dvc/objects/db.py
  dvc/repo/gc.py
Labels: refactoring, skip-changelog

#7256 plots: Fix `--json` requiring `-o`.
  dvc/command/plots.py
  tests/unit/command/test_plots.py
Labels: bugfix

#7280 plots: update linear template so colors can be externally overwritten
  dvc/repo/plots/templates/linear.json
Labels: external-product, A: plots

#7283 find_root: unify error message
  dvc/repo/__init__.py
Labels: bugfix

#7282 repro/exp run: display stage name instead of filepath on failure
  dvc/exceptions.py
  dvc/repo/reproduce.py
  tests/func/experiments/test_experiments.py
Labels: enhancement, ui, A: cli, A: pipelines

#7287 cli: refactor into a module
  dvc/__main__.py
  dvc/cli/__init__.py
  dvc/cli/parser.py
  dvc/command/completion.py
  dvc/command/data_sync.py
  dvc/command/git_hook.py
  dvc/daemon.py
  dvc/main.py
  dvc/repo/experiments/executor/base.py
  setup.cfg
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_init.py
  tests/func/experiments/test_show.py
  tests/func/machine/test_machine_config.py
  tests/func/machine/test_machine_status.py
  tests/func/metrics/test_diff.py
  tests/func/plots/test_show.py
  tests/func/test_add.py
  tests/func/test_analytics.py
  tests/func/test_check_ignore.py
  tests/func/test_checkout.py
  tests/func/test_config.py
  tests/func/test_data_cloud.py
  tests/func/test_gc.py
  tests/func/test_get.py
  tests/func/test_import_url.py
  tests/func/test_init.py
  tests/func/test_lock.py
  tests/func/test_merge_driver.py
  tests/func/test_move.py
  tests/func/test_odb.py
  tests/func/test_remote.py
  tests/func/test_remove.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_root.py
  tests/func/test_run_single_stage.py
  tests/func/test_stage.py
  tests/func/test_status.py
  tests/func/test_unprotect.py
  tests/func/test_version.py
  tests/func/utils/test_strict_yaml.py
  tests/unit/command/test_cache.py
  tests/unit/command/test_config.py
  tests/unit/command/test_git_hook.py
  tests/unit/test_imports.py
Labels: refactoring, A: cli

#7237 tests: clean repositories before each test runs
  tests/conftest.py
Labels: testing, skip-changelog

#7291 tests: increase timeout for exp init tests
  tests/func/experiments/test_init.py
Labels: testing, skip-changelog

#7293 cli: improve startup speed
  dvc/commands/live.py
  dvc/fs/_callback.py
  dvc/fs/base.py
  dvc/fs/dvc.py
  dvc/fs/fsspec_wrapper.py
  dvc/fs/http.py
  dvc/fs/local.py
  dvc/fs/repo.py
  dvc/fs/s3.py
  dvc/fs/ssh.py
  dvc/progress.py
  dvc/utils/fs.py
Labels: performance, optimize

#7299 TabularData: Simplify drop internals.
  dvc/commands/experiments/show.py
  dvc/compare.py
  tests/unit/command/test_experiments.py
Labels: skip-changelog

#7277 exp init: handle exception properly on missing parameters file
  dvc/dependency/param.py
  dvc/output.py
  dvc/repo/experiments/init.py
Labels: enhancement, A: experiments, A: cli

#7297 add: Update help of `--jobs`
  dvc/commands/add.py
Labels: skip-changelog

#7306 exp run: do not log message twice on workspace executor
  dvc/repo/experiments/executor/manager/local.py
  tests/func/experiments/test_experiments.py
Labels: bugfix

#7311 ignore: move debug statetement to the proper location
  dvc/repo/scm_context.py
Labels: bugfix, A: debug

#7313 output: move isexec to meta
  dvc/data/meta.py
  dvc/data/stage.py
  dvc/fs/base.py
  dvc/fs/dvc.py
  dvc/fs/git.py
  dvc/fs/local.py
  dvc/fs/repo.py
  dvc/output.py
  dvc/schema.py
  dvc/stage/loader.py
  dvc/stage/serialize.py
  dvc/stage/utils.py
  tests/unit/stage/test_loader_pipeline_file.py
  tests/unit/stage/test_serialize_pipeline_lock.py
Labels: refactoring, skip-changelog

#7321 Doc URL correction for GitAuthError
  dvc/scm.py
Labels: bugfix
