Repository iterative/dvc, pull requests merged in 2022-11, with the labels that each got.

#8502 tests: remove TestDir
  tests/basic_env.py
  tests/func/test_gc.py
Labels: testing, skip-changelog

#8504 fix release note config, it has to be inside changelog key
  .github/release.yml
Labels: skip-changelog

#8507 chore: remove bin dir and simplify tests.__main__
  .dvcignore
  bin/dvc
  bin/dvc.bat
  tests/__main__.py
Labels: skip-changelog

#8505 commit: skip changed_entries check on force commit
  dvc/repo/commit.py
Labels: bugfix, A: data-management

#8511 build: bump pyinstaller packages python version to 3.10
  .github/workflows/packages.yaml
Labels: build

#8501 use setuptools_scm provided version for pyinstaller builds
  dvc/__init__.py
  dvc/version.py
  scripts/build.py
Labels: skip-changelog

#8519 exp run: catch hydra import in 3.11
  dvc/repo/experiments/run.py
Labels: A: experiments, bugfix

#8521 hydra: Raise lazy DvcException for Python >= 3.11
  dvc/repo/experiments/queue/base.py
  dvc/repo/experiments/run.py
  dvc/utils/hydra.py
Labels: maintenance

#8527 readme: show downloads badge
  README.rst
Labels: skip-changelog

#8534 pkging: also post released packages to test.pypi.org
  .github/workflows/packages.yaml
Labels: skip-changelog

#8533 Make exp show handle errors better
  dvc/repo/experiments/diff.py
  dvc/repo/experiments/queue/utils.py
  dvc/repo/experiments/show.py
  tests/func/experiments/test_show.py
Labels: A: experiments, bug

#8543 ci: test with 3.11 on all OSes
  .github/workflows/tests.yaml
Labels: skip-changelog

#8541 Solve the crash on getting name of applied experiment branch
  dvc/repo/experiments/show.py
  tests/unit/repo/experiments/test_show.py
Labels: A: experiments, bugfix

#8551 fetch/pull: fix regression when using targeted fetch in repo containing import-url imports
  dvc/output.py
Labels: bugfix, regression, A: data-sync

#8555 typecheck: fix type error in _git_info
  dvc/repo/data.py
Labels: skip-changelog

#8556 hydra: Raise error when `name` and `sweeps`.
  dvc/repo/experiments/run.py
  tests/func/experiments/test_set_params.py
Labels: ui, A: experiments

#8204 parsing: Escape str interpolation in dict unpacking.
  dvc/parsing/interpolate.py
  tests/func/parsing/test_interpolated_entry.py
Labels: bugfix, A: templating

#8581 worktree: support push: false
  dvc/repo/fetch.py
  dvc/repo/index.py
  dvc/repo/push.py
  dvc/repo/worktree.py
Labels: A: data-sync, A: cloud-versioning

#8587 hydra: Use `OmegaConf.to_yaml` for dumping `.yaml` output.
  dvc/utils/hydra.py
  tests/func/utils/test_hydra.py
Labels: bugfix

#8594 deps: bump dvc-data, dvc-azure
  pyproject.toml
Labels: maintenance

#8595 wokrtree add: preserve version metadata for unmodified files on `dvc add`
  dvc/output.py
  dvc/repo/add.py
  dvc/stage/__init__.py
Labels: A: data-management, A: cloud-versioning

#8580 queue kill: we can manually mark problematic tasks as failure
  dvc/repo/experiments/queue/celery.py
  dvc/repo/experiments/queue/exceptions.py
  pyproject.toml
  tests/unit/repo/experiments/queue/__init__.py
  tests/unit/repo/experiments/queue/test_celery.py
Labels: A: experiments, bugfix, A: task-queue

#8596 Solve the wrong checkpoint tip info during executor running
  dvc/repo/experiments/queue/tempdir.py
  dvc/repo/experiments/queue/utils.py
  dvc/repo/experiments/show.py
  tests/unit/repo/experiments/test_show.py
Labels: A: experiments, bugfix

#8606 worktree push: do not push existing versions
  dvc/repo/worktree.py
Labels: A: data-sync, A: cloud-versioning

#8604 ui: Fix WSL check in `open_browser`
  dvc/ui/__init__.py
  tests/unit/command/test_plots.py
Labels: ui, bugfix

#8627 deps: add support for hdfs in Python 3.11
  pyproject.toml
Labels: maintenance, dependencies

#8575 exp list: cleanup and move logic inside repo api
  dvc/commands/experiments/ls.py
  dvc/repo/experiments/ls.py
  dvc/repo/experiments/refs.py
  dvc/repo/experiments/utils.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_remote.py
Labels: refactoring, A: experiments

#8633 deps: bump dvc-data to 0.28.1
  pyproject.toml
Labels: maintenance

#8632 index: skip data index load on empty view
  dvc/repo/index.py
Labels: bugfix, A: data-management

#8641 deps: bump dvc-data to 0.28.2
  pyproject.toml
Labels: maintenance

#8640 Solve the unexpected error at the end of the queued tasks running
  dvc/repo/experiments/queue/utils.py
  pyproject.toml
Labels: A: experiments, bugfix
