Repository iterative/dvc, pull requests merged in 2023-08, with the labels that each got.

#9788 ls/import/get: introduce --remote and --remote-config
  dvc/cli/utils.py
  dvc/commands/get.py
  dvc/commands/imp.py
  dvc/commands/ls/__init__.py
  dvc/dependency/repo.py
  dvc/repo/get.py
  dvc/repo/imp.py
  dvc/repo/ls.py
  tests/unit/command/ls/test_ls.py
  tests/unit/command/test_get.py
  tests/unit/command/test_imp.py
Labels: feature

#9783 Feature/hydra config modules
  dvc/config_schema.py
  dvc/repo/experiments/queue/base.py
  dvc/utils/hydra.py
  tests/func/utils/test_hydra.py
Labels: enhancement, A: hydra

#9810 fetch: add basic onerror
  dvc/repo/fetch.py
Labels: feature

#9815 repo: add basic cache_check_missing
  dvc/repo/__init__.py
  dvc/repo/cache.py
Labels: skip-changelog

#9820 index: plot_keys: relparts -> parts
  dvc/repo/index.py
Labels: skip-changelog

#9825 config: resolve: handle ~ home dir
  dvc/config.py
  dvc/config_schema.py
  tests/func/test_config.py
  tests/unit/test_config.py
Labels: bugfix

#9827 config: use local config from local_dvc_dir
  dvc/config.py
  dvc/repo/__init__.py
Labels: bugfix

#9828 fetch: merge config instead of updating
  dvc/config.py
  dvc/repo/fetch.py
Labels: bugfix

#9808 exp: Unify dvc exp list and show output
  dvc/commands/experiments/ls.py
  dvc/repo/experiments/collect.py
  dvc/repo/experiments/ls.py
  dvc/repo/experiments/utils.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_remote.py
  tests/func/experiments/test_save.py
  tests/unit/command/test_experiments.py
Labels: enhancement, ui, A: experiments

#9834 deps: bump dvc-data to 2.13.1
  dvc/repo/checkout.py
  dvc/repo/worktree.py
  pyproject.toml
Labels: bugfix

#9840 pyinstaller: declare dvc_ssh as hidden import
  dvc/__pyinstaller/hook-dvc.py
Labels: build

#9848 fs: make _prepare_credentails/fs_args lazy
  pyproject.toml
  tests/unit/fs/test_azure.py
  tests/unit/fs/test_s3.py
Labels: bugfix

#9854 ls/ls-url: introduce --size
  dvc/commands/ls/__init__.py
  dvc/commands/ls_url.py
  dvc/repo/ls.py
  dvc/repo/ls_url.py
  tests/func/test_ls.py
Labels: feature

#9855 import: set core.remote when both --remote and --remote-config are specified
  dvc/dependency/repo.py
  dvc/repo/imp.py
  tests/func/test_import.py
Labels: bugfix

#9857 ls/ls-url: use humanize.naturalsize instead of tqdm
  dvc/commands/ls/__init__.py
  pyproject.toml
Labels: skip-changelog

#9869 cache: check-missing: add type, oid name and oid
  dvc/repo/cache.py
Labels: skip-changelog

#9871 deps: unpin dvc-oss
  pyproject.toml
Labels: dependencies

#9875 update: preserve `def_path` for version-aware import update
  dvc/dependency/base.py
  dvc/testing/workspace_tests.py
Labels: bugfix, A: data-sync

#9879 Add DVC_ROOT env var into queued experiment runs
  dvc/repo/experiments/queue/base.py
  tests/func/experiments/test_experiments.py
Labels: product: VSCode

#9887 cli: utils: DictAction: limit split to 2 elements
  dvc/cli/utils.py
Labels: bugfix
