Repository iterative/dvc, pull requests merged in 2023-09, with the labels that each got.

#9905 move: Alias mv to move
  dvc/commands/experiments/ls.py
  dvc/commands/experiments/remove.py
  dvc/commands/move.py
  dvc/commands/remove.py
Labels: awaiting response

#9889 exp run: track files for skipped/run-cached stages
  dvc/repo/experiments/executor/base.py
Labels: A: experiments, bugfix

#9906 exp show: drop internal legacy checkpoint support
  dvc/repo/experiments/show.py
Labels: A: experiments, bugfix

#9919 checkout: Expose `--allow-missing` arg.
  dvc/commands/checkout.py
  tests/unit/command/test_checkout.py
Labels: ui, A: data-management

#9925 repo: use is_repo_import to check for imports in `outs_graph`
  dvc/repo/graph.py
Labels: bugfix

#9927 import: Expose `--force` flag
  dvc/commands/imp.py
  tests/unit/command/test_imp.py
Labels: ui, bugfix, A: data-sync

#9932 params/metrics: cache remote files
  dvc/dependency/param.py
  dvc/repo/metrics/show.py
  dvc/repo/params/show.py
  dvc/utils/serialize/__init__.py
  dvc/utils/serialize/_common.py
  dvc/utils/serialize/_json.py
  dvc/utils/serialize/_py.py
  dvc/utils/serialize/_toml.py
  dvc/utils/serialize/_yaml.py
Labels: feature, A: plots, A: params, A: metrics

#9933 Migrate from PyPI tokens to Trusted Publishers
  .github/workflows/build.yaml
Labels: enhancement

#9951 api.DVCFileSystem: fix fsspec compliance
  dvc/fs/dvc.py
Labels: A: api

#9812 exp: add rename command
  dvc/commands/experiments/__init__.py
  dvc/commands/experiments/rename.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/exceptions.py
  dvc/repo/experiments/rename.py
  tests/func/experiments/test_rename.py
  tests/unit/command/test_experiments.py
Labels: A: experiments, feature

#9966 build: temporarily pin setuptools-scm
  pyproject.toml
Labels: maintenance

#9974 checkout: tweak messages and don't clear pbars
  dvc/repo/checkout.py
Labels: enhancement, ui

#9975 fetch: don't clear pbars
  dvc/repo/fetch.py
Labels: ui

#9972 artifacts: Bring back `name_is_compatible`.
  dvc/repo/artifacts.py
Labels: release-blocker, A: artifacts

#9908 run-cache: Load newest instead of first found in os.listdir.
  dvc/stage/cache.py
  tests/func/test_run_cache.py
Labels: A: run-cache

#9979 cli: data_sync: show warning about missing default remote
  dvc/commands/data_sync.py
Labels: ui
