Repository iterative/dvc, pull requests merged in 2023-12, with the labels that each got.

#10125 experimental: support connection strings for databases
  dvc/commands/config.py
  dvc/commands/imp_db.py
  dvc/config.py
  dvc/config_schema.py
  dvc/database/__init__.py
  dvc/database/dbt_models.py
  dvc/database/dbt_query.py
  dvc/database/dbt_runner.py
  dvc/database/dbt_utils.py
  dvc/database/serializer.py
  dvc/database/sqla.py
  dvc/dependency/db.py
  dvc/repo/imp_db.py
  dvc/utils/db.py
  pyproject.toml
  tests/func/test_cli.py
  tests/func/test_import_db.py
  tests/func/test_import_db_e2e.py
Labels: skip-changelog, A: data-management

#10129 database: fix ui issues
  dvc/commands/imp_db.py
  dvc/database/serializer.py
  dvc/dependency/db.py
  dvc/ui/_rich_progress.py
Labels: skip-changelog

#10074 studio: Add Studio authentication to DVC
  dvc/cli/parser.py
  dvc/commands/studio.py
  pyproject.toml
  tests/unit/command/test_studio.py
Labels: enhancement, feature, A: cli, product: Studio

#10159 cli: debug: finalize profiler reports on errors
  dvc/_debug.py
Labels: A: debug

#10178 param: fix exponential memory allocation
  dvc/dependency/param.py
Labels: bug, p0-critical, A: params

#10180 param: optimize fix for exponential memory allocation
  dvc/dependency/param.py
Labels: A: params

#10190 push: leave ui messages
  dvc/repo/push.py
Labels: ui

#10191 push: only collect needed files when updating version_ids
  dvc/repo/push.py
Labels: performance, bugfix, A: cloud-versioning

#10075 webhdfs: implement support for basic auth and proxy
  dvc/config_schema.py
  pyproject.toml
Labels: feature, fs: webhdfs

#10205 fix partial fetch
  pyproject.toml
  tests/func/test_data_cloud.py
  tests/func/test_virtual_directory.py
Labels: p1-important, bugfix, regression, A: data-management
