Repository iterative/dvc, pull requests merged in 2023-02, with the labels that each got.

#8929 stage: use repo.fs directly without copying
  dvc/repo/stage.py
  tests/func/test_repo_index.py
Labels: bug

#8959 index: build_data_index: handle empty dirs
  dvc/repo/index.py
  tests/func/test_data_status.py
Labels: bugfix

#8955 studio: Move `post_live_metrics` from `queue` to `executor`
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/queue/workspace.py
  dvc/repo/experiments/utils.py
  tests/func/experiments/test_utils.py
  tests/integration/conftest.py
  tests/integration/test_studio_live_experiments.py
Labels: product, bugfix

#8907 Use pygit2 backend for fetch_refspecs
  dvc/repo/experiments/executor/base.py
  pyproject.toml
Labels: performance, A: experiments, git

#8969 logging: defer calling colorama.init() in jupyter, otherwise initialize immediately (#8969)Closes https://github.com/iterative/dvc/issues/8957
  dvc/logger.py
Labels: ui, bugfix

#8979 testing: mark 00 prefix tests xfail on fs without find()
  dvc/testing/remote_tests.py
Labels: testing, fs: http

#8949 push: check if versioning is supported or not during checkout on cloud versioning (#8949)Fixes https://github.com/iterative/dvc/issues/8824
  dvc/repo/worktree.py
  pyproject.toml
Labels: enhancement, A: cloud-versioning

#8987 repo: rename odb -> cache
  dvc/cachemgr.py
  dvc/data_cloud.py
  dvc/dependency/repo.py
  dvc/external_repo.py
  dvc/info.py
  dvc/output.py
  dvc/repo/__init__.py
  dvc/repo/diff.py
  dvc/repo/experiments/executor/local.py
  dvc/repo/experiments/executor/ssh.py
  dvc/repo/gc.py
  dvc/repo/imports.py
  dvc/stage/cache.py
  dvc/testing/api_tests.py
  dvc/testing/fixtures.py
  dvc/testing/remote_tests.py
  dvc/testing/workspace_tests.py
  tests/func/api/test_data.py
  tests/func/data/db/test_index.py
  tests/func/experiments/test_remote.py
  tests/func/metrics/test_show.py
  tests/func/plots/test_show.py
  tests/func/test_add.py
  tests/func/test_checkout.py
  tests/func/test_data_cloud.py
  tests/func/test_data_status.py
  tests/func/test_diff.py
  tests/func/test_external_repo.py
  tests/func/test_gc.py
  tests/func/test_get.py
  tests/func/test_ignore.py
  tests/func/test_import.py
  tests/func/test_odb.py
  tests/func/test_remote.py
  tests/func/test_remove.py
  tests/func/test_repo.py
  tests/func/test_repro.py
  tests/func/test_run_single_stage.py
  tests/func/test_unprotect.py
  tests/unit/data/db/test_local.py
  tests/unit/fs/test_data.py
  tests/unit/fs/test_dvc.py
  tests/unit/output/test_output.py
  tests/unit/stage/test_cache.py
  tests/unit/test_external_repo.py
  tests/unit/test_info.py
Labels: refactoring, skip-changelog

#8988 output: rename odb -> cache
  dvc/output.py
  dvc/repo/index.py
Labels: refactoring, skip-changelog

#9011 deps: bump dvc-data to 0.40.1
  dvc/repo/data.py
  dvc/repo/imports.py
  dvc/repo/index.py
  dvc/repo/worktree.py
  pyproject.toml
Labels: dependencies

#8827 index: experimental persistent data index
  dvc/config_schema.py
  dvc/repo/index.py
Labels: enhancement, performance

#9014 repo: introduce data_index
  dvc/repo/__init__.py
  dvc/repo/index.py
  tests/func/test_data_cloud.py
Labels: refactoring, skip-changelog

#9000 Handle filenames which has ":"
  dvc/config_schema.py
  tests/func/test_add.py
Labels: bugfix

#9023 scm: use dulwich backend when fetching exps during clone/pull
  dvc/external_repo.py
  dvc/repo/experiments/utils.py
  dvc/scm.py
Labels: p0-critical, bugfix

#9032 data: status: fix typo
  dvc/repo/data.py
Labels: skip-changelog

#9033 render: avoid deepcopying
  dvc/render/convert.py
  dvc/render/converter/vega.py
Labels: optimize, A: plots

#9048 deps: bump dvc-data to 0.40.4
  pyproject.toml
Labels: dependencies

#9050 bump ruff to v0.0.247
  .pre-commit-config.yaml
  dvc/cli/__init__.py
  dvc/commands/dag.py
  dvc/commands/experiments/show.py
  dvc/commands/machine.py
  dvc/commands/plots.py
  dvc/compare.py
  dvc/config_schema.py
  dvc/dagascii.py
  dvc/dependency/repo.py
  dvc/dvcfile.py
  dvc/external_repo.py
  dvc/fs/__init__.py
  dvc/fs/dvc.py
  dvc/logger.py
  dvc/output.py
  dvc/parsing/context.py
  dvc/parsing/versions.py
  dvc/progress.py
  dvc/render/converter/vega.py
  dvc/repo/__init__.py
  dvc/repo/add.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/apply.py
  dvc/repo/experiments/init.py
  dvc/repo/experiments/queue/base.py
  dvc/repo/experiments/queue/remove.py
  dvc/repo/experiments/show.py
  dvc/repo/experiments/utils.py
  dvc/repo/fetch.py
  dvc/repo/gc.py
  dvc/repo/graph.py
  dvc/repo/imp_url.py
  dvc/repo/metrics/show.py
  dvc/repo/move.py
  dvc/repo/params/show.py
  dvc/repo/pull.py
  dvc/repo/push.py
  dvc/repo/reproduce.py
  dvc/rwlock.py
  dvc/scm.py
  dvc/stage/__init__.py
  dvc/stage/monitor.py
  dvc/ui/__init__.py
  dvc/utils/collections.py
  dvc/utils/serialize/_py.py
  dvc/version.py
  pyproject.toml
  tests/func/experiments/executor/test_ssh.py
  tests/func/test_data_cloud.py
  tests/func/test_diff.py
  tests/integration/plots/test_plots.py
  tests/unit/command/test_dag.py
  tests/unit/command/test_plots.py
  tests/unit/test_logger.py
Labels: skip-changelog

#9051 pyproject.toml: cleanup metadata
  pyproject.toml
Labels: skip-changelog

#9052 deps (tests): unpin test deps
  pyproject.toml
Labels: skip-changelog

#9053 pyproject: format using pyproject-fmt
  pyproject.toml
Labels: skip-changelog

#9055 deps: drop importlib-resources and typing-extensions
  pyproject.toml
Labels: dependencies

#9056 deps: use version ranges for dvc sub-packages
  pyproject.toml
Labels: maintenance

#9042 Add metrics_show to dvc.api
  dvc/api/__init__.py
  dvc/api/show.py
  tests/func/api/test_params.py
  tests/func/api/test_show.py
Labels: feature, A: api

#9064 exp save: Use `pathspec` to handle `include_untracked`.
  dvc/repo/experiments/save.py
  tests/func/experiments/test_save.py
Labels: A: experiments, bugfix

#9071 pull: Add `allow_missing` flag.
  dvc/commands/data_sync.py
  dvc/repo/pull.py
  tests/func/test_data_cloud.py
  tests/unit/command/test_data_sync.py
Labels: feature, A: data-sync

#9077 exp show: cache git refs per show() call
  dvc/repo/experiments/show.py
Labels: performance, A: experiments

#9083 testing: fixtures: fix docker regression
  dvc/testing/fixtures.py
Labels: p0-critical, testing

#9093 exp save: Don't relink during commit
  dvc/repo/experiments/save.py
Labels: performance, A: experiments
