Repository iterative/dvc, pull requests merged in 2023-06, with the labels that each got.

#9546 remove support for reading and generating Dvcfile
  dvc/dvcfile.py
  dvc/stage/utils.py
  tests/func/params/test_diff.py
  tests/func/params/test_show.py
  tests/func/test_repro.py
  tests/func/test_run_single_stage.py
  tests/unit/stage/test_stage.py
Labels: breaking-change

#9550 add: rename jobs to remote_jobs to mirror CLI; move validation to CLI
  dvc/commands/add.py
  dvc/repo/add.py
  tests/func/test_add.py
  tests/unit/command/test_add.py
Labels: A: cli

#9551 .dvc file: remove params support
  dvc/dependency/__init__.py
  dvc/dependency/param.py
Labels: breaking-change

#9552 .dvc file: remove metrics/plots support
  dvc/output.py
  tests/func/test_repro.py
Labels: breaking-change

#9553 tests: remove single_stage tests from repro/run tests
  dvc/repo/run.py
  tests/func/test_lockfile.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_run.py
  tests/func/test_run_multistage.py
  tests/func/test_run_single_stage.py
  tests/unit/repo/test_run.py
Labels: testing

#9559 dvc.utils.pkg: move PKG to top-level dvc
  dvc/__init__.py
  dvc/_build.py
  dvc/cli/__init__.py
  dvc/info.py
  dvc/updater.py
  dvc/utils/pkg.py
  scripts/build.py
  scripts/build_package.sh
  tests/unit/cli/test_main.py
Labels: breaking-change

#9562 import: drop --file
  dvc/commands/imp.py
  dvc/commands/imp_url.py
  dvc/repo/imp.py
  dvc/repo/imp_url.py
  tests/func/test_import_url.py
  tests/unit/command/test_imp.py
  tests/unit/command/test_imp_url.py
Labels: breaking-change

#9577 deps: bump dvc-data to >= 1.2.0
  pyproject.toml
Labels: enhancement, ui

#9578 fetch: show progress when collecting
  dvc/repo/fetch.py
  pyproject.toml
Labels: enhancement, ui

#9581 deps: bump dvc-data to >=1.5.0
  pyproject.toml
Labels: dependencies

#9533 repro: check for hash mismatch between deleted dependencies and upstream outputs.
  dvc/repo/reproduce.py
  dvc/stage/__init__.py
  tests/func/repro/__init__.py
  tests/func/repro/test_repro.py
  tests/func/repro/test_repro_allow_missing.py
  tests/func/repro/test_repro_pull.py
Labels: bugfix, A: pipelines

#9596 pyproject.toml: reformat project table
  pyproject.toml
Labels: skip-changelog

#9598 checkout/fetch: finer control over steps
  dvc/repo/checkout.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/fetch.py
  dvc/repo/imports.py
  dvc/repo/worktree.py
  pyproject.toml
Labels: ui

#9605 diff: handle revisions pointing to the same sha
  dvc/repo/diff.py
  tests/func/test_diff.py
Labels: bug

#9627 gha: don't build binary packages
  .dvc/.gitignore
  .dvc/config
  .github/workflows/packages.yaml
  scripts/build.py
  scripts/fpm/.gitignore
  scripts/fpm/after-install.sh
  scripts/fpm/after-remove.sh
  scripts/fpm/build.py
  scripts/fpm/notarize.py
  scripts/fpm/sign.py
  scripts/innosetup/.gitignore
  scripts/innosetup/addSymLinkPermissions.ps1
  scripts/innosetup/addsymlink.iss
  scripts/innosetup/build.py
  scripts/innosetup/dvc.ico.dvc
  scripts/innosetup/dvc_left.bmp.dvc
  scripts/innosetup/dvc_up.bmp.dvc
  scripts/innosetup/modpath.iss
  scripts/innosetup/setup.iss
  scripts/pyinstaller/entitlements.plist
  scripts/pyinstaller/sign.py
Labels: build, skip-changelog

#9628 tests: unit: explicitly ask for dvc repo
  tests/unit/command/test_add.py
  tests/unit/command/test_data_sync.py
  tests/unit/command/test_diff.py
  tests/unit/command/test_experiments.py
  tests/unit/command/test_imp.py
  tests/unit/command/test_imp_url.py
Labels: refactoring, skip-changelog

#9634 deps: bump dvc-data to >= 2.1.0
  pyproject.toml
Labels: dependencies

#9635 checkout: friendlier UI when tryint to remove uncached files
  dvc/repo/checkout.py
  pyproject.toml
  tests/func/test_checkout.py
Labels: ui

#9643 output: preserve legacy hash_name on save() for unchanged data
  dvc/output.py
  tests/func/test_commit.py
Labels: A: experiments, bugfix

#9648 deps: bump scmrepo minver to 1.0.4
  pyproject.toml
Labels: maintenance, dependencies

#9659 checkout: use single tics instead of curly braces
  dvc/repo/checkout.py
Labels: skip-changelog

#9661 checkout: use ui.progress
  dvc/fs/callbacks.py
  dvc/progress.py
  dvc/repo/checkout.py
Labels: enhancement, ui

#9662 data: status: use ui.progress instead of ui.status
  dvc/repo/data.py
  tests/unit/command/test_data_status.py
Labels: enhancement, ui

#9660 Stable experiment range sorting
  dvc/repo/experiments/collect.py
  tests/unit/repo/experiments/test_collect.py
Labels: product: VSCode, bugfix

#9665 exp pull: update for index fetch
  dvc/repo/experiments/executor/ssh.py
  dvc/repo/experiments/pull.py
Labels: A: experiments, bugfix, regression

#9670 make it a dvc repo
  .dvc/.gitignore
  .dvc/config
Labels: skip-changelog

#9674 repro: remove on_unchanged kwarg and _repro_callback
  dvc/repo/experiments/executor/base.py
  dvc/repo/reproduce.py
Labels: refactoring, skip-changelog

#9677 stage: cache: catch CollectCacheError
  dvc/stage/cache.py
Labels: bugfix
