Repository iterative/dvc, pull requests merged in 2023-10, with the labels that each got.

#9996 deps: bump dvc-data to >=2.18.1
  pyproject.toml
Labels: dependencies

#10007 cache migrate: add --dvc-files flag to migrate .dvc and dvc.lock files
  dvc/commands/cache.py
  dvc/output.py
  dvc/repo/commit.py
Labels: A: data-management

#10024 worktree: don't modify index entries in place
  dvc/repo/worktree.py
  dvc/testing/fixtures.py
  dvc/testing/remote_tests.py
  dvc/testing/scripts.py
  tests/dir_helpers.py
  tests/func/experiments/test_experiments.py
  tests/scripts.py
Labels: bug

#10047 cli: DictAction: set default metavar
  dvc/cli/utils.py
Labels: enhancement, ui

#10058 daemon: ipc to log pid from the child
  dvc/daemon.py
  tests/func/test_daemon.py
Labels: skip-changelog
