Repository iterative/dvc, pull requests merged in 2023-04, with the labels that each got.

#9261 exp save: include untracked dvclock
  dvc/repo/experiments/executor/base.py
  tests/func/experiments/test_save.py
Labels: enhancement, A: experiments

#9300 bump ruff to 0.0.260 and enable bandit
  .pre-commit-config.yaml
  dvc/commands/completion.py
  dvc/daemon.py
  dvc/lock.py
  dvc/logger.py
  dvc/parsing/interpolate.py
  dvc/repo/__init__.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/queue/base.py
  dvc/repo/experiments/utils.py
  dvc/repo/index.py
  dvc/stage/monitor.py
  dvc/stage/run.py
  dvc/testing/fixtures.py
  dvc/ui/pager.py
  dvc/version.py
  pyproject.toml
  tests/unit/remote/test_webhdfs.py
Labels: skip-changelog

#9301 utils.studio: disallow redirects, misc API refactoring
  dvc/utils/studio.py
  tests/unit/utils/test_studio.py
Labels: skip-changelog

#9303 notify_refs; rename studio_url to base_url
  dvc/repo/experiments/push.py
  dvc/utils/studio.py
Labels: skip-changelog

#9307 deps: bump scmrepo minver to 0.2.1
  pyproject.toml
Labels: maintenance, dependencies

#9302 exp run: Add `--copy-paths` arg.
  dvc/commands/experiments/exec_run.py
  dvc/commands/experiments/run.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/executor/ssh.py
  dvc/repo/experiments/queue/base.py
  dvc/repo/experiments/queue/celery.py
  dvc/repo/experiments/queue/tasks.py
  dvc/repo/experiments/queue/tempdir.py
  dvc/repo/experiments/queue/workspace.py
  dvc/repo/experiments/run.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_queue.py
  tests/func/experiments/test_set_params.py
  tests/unit/command/test_experiments.py
Labels: enhancement, A: experiments

#9310 logger: add DVC_SHOW_TRACEBACK envvar to show traceback on exception
  dvc/env.py
  dvc/logger.py
Labels: skip-changelog

#9311 deps: bump dvc-ssh to 2.22.1
  dvc/config_schema.py
  pyproject.toml
Labels: maintenance, dependencies, fs: ssh

#9326 deps: put lower bound on dvc-http
  pyproject.toml
Labels: dependencies

#9322 tests: remove unnecessary variable interpolation
  tests/func/experiments/test_save.py
Labels: testing, skip-changelog

#9257 [DO NOT MERGE] release: remove feature flags for experiment sharing
  dvc/config_schema.py
  dvc/repo/experiments/push.py
Labels: A: experiments, blocked

#9340 add DVC_STUDIO_URL envvar support
  dvc/env.py
  dvc/repo/experiments/push.py
Labels: enhancement

#9341 utils.studio: allow any base url to be set, not just the hostname
  dvc/utils/studio.py
Labels: skip-changelog

#9344 exp run: do not autostage on dvc repro
  dvc/repo/experiments/executor/base.py
  dvc/repo/reproduce.py
Labels: p0-critical, bugfix

#9354 reproduce: remove callback
  dvc/repo/experiments/executor/base.py
  dvc/repo/reproduce.py
Labels: refactoring, skip-changelog

#9353 studio: Ensure `studio_repo_url` works with `exp run --queue`.
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/queue/base.py
  pyproject.toml
  tests/func/experiments/test_experiments.py
  tests/integration/test_studio_live_experiments.py
Labels: product, A: experiments, bugfix

#9362 tests: lazy tpi imports, ignore deprecation warning from setuptools
  pyproject.toml
  tests/func/machine/test_machine_config.py
Labels: skip-changelog

#9365 Fix: Prettifying unexpected error on FileExists for get/get-url/imp-url/add and introducing --force
  dvc/commands/add.py
  dvc/commands/get.py
  dvc/commands/get_url.py
  dvc/commands/imp_url.py
  dvc/exceptions.py
  dvc/repo/add.py
  dvc/repo/get.py
  dvc/repo/get_url.py
  dvc/repo/imp_url.py
  dvc/stage/__init__.py
  dvc/utils/__init__.py
  tests/func/test_add.py
  tests/func/test_get.py
  tests/func/test_get_url.py
  tests/func/test_import_url.py
  tests/unit/command/test_add.py
  tests/unit/command/test_get.py
  tests/unit/command/test_get_url.py
  tests/unit/command/test_imp_url.py
Labels: enhancement, ui

#9368 exp push: soft wrap link so that the URL does not break
  dvc/commands/experiments/push.py
Labels: A: experiments, A: cli

#9376 info: replace self -> repo
  dvc/info.py
Labels: refactoring, skip-changelog

#9377 info: get_fs_type -> _get_fs_type
  dvc/info.py
Labels: refactoring, skip-changelog

#9378 doctor: add system/global config location
  dvc/info.py
Labels: skip-changelog
