Repository iterative/dvc, pull requests merged in 2023-07, with the labels that each got.

#9680 build: pyinstaller: use __pyinstaller
  dvc/__pyinstaller/__init__.py
  dvc/__pyinstaller/hook-asyncssh.py
  dvc/__pyinstaller/hook-celery.py
  dvc/__pyinstaller/hook-dvc.py
  dvc/__pyinstaller/hook-dvc.system.py
  dvc/__pyinstaller/hook-dvc.tree.gs.py
  dvc/__pyinstaller/hook-dvc.utils.flatten.py
  dvc/__pyinstaller/hook-dvc_task.py
  dvc/__pyinstaller/hook-fsspec.py
  dvc/__pyinstaller/hook-google_compute_engine.logger.py
  dvc/__pyinstaller/hook-pydrive2.py
  pyproject.toml
  scripts/build-requirements.txt
  scripts/pyinstaller/.gitignore
  scripts/pyinstaller/build.py
Labels: build

#9681 deps: limit flufl-lock to <8
  pyproject.toml
Labels: dependencies

#9686 bandit: add exclusion for dvc/repo/experiments/utils.py back
  pyproject.toml
Labels: skip-changelog

#9669 fetch: warn if cloud-versioned file has no version ID
  dvc/repo/fetch.py
  dvc/repo/pull.py
Labels: A: cloud-versioning

#9687 repro: simplify _reproduce_stages
  dvc/repo/reproduce.py
Labels: refactoring, skip-changelog

#9689 repro: do not autostage stage files
  dvc/repo/experiments/executor/base.py
  dvc/repo/reproduce.py
  dvc/stage/utils.py
  tests/unit/repo/test_reproduce.py
  tests/unit/stage/test_utils.py
Labels: bugfix

#9692 repro: ignore --downstream if used together with --pipeline
  dvc/repo/reproduce.py
Labels: bugfix

#9701 repro: move code around
  dvc/repo/graph.py
  dvc/repo/reproduce.py
  tests/unit/repo/test_graph.py
Labels: refactoring, skip-changelog

#9717 deps: bump dvc-data to 2.5.0
  dvc/repo/fetch.py
  pyproject.toml
Labels: dependencies

#9729 parsing: pass config instead of loading every time
  dvc/parsing/__init__.py
  dvc/parsing/context.py
  dvc/parsing/interpolate.py
Labels: performance, optimize, A: templating

#9726 plots: log failures during datapoint conversions
  dvc/render/match.py
Labels: bugfix, A: plots

#9712 repro: introduce --keep-going/--ignore to continue on error
  dvc/commands/repro.py
  dvc/exceptions.py
  dvc/repo/reproduce.py
  tests/func/repro/test_repro.py
  tests/unit/command/test_repro.py
  tests/unit/repo/test_reproduce.py
Labels: A: cli, A: pipelines

#9746 dvcfs: handle NotADirectoryError from datafs.ls
  dvc/fs/dvc.py
  pyproject.toml
  tests/unit/fs/test_dvc.py
Labels: bugfix

#9753 fs.download: prefer generic.copy over fsspec fs.get()
  dvc/dependency/base.py
  dvc/fs/__init__.py
  dvc/repo/get.py
  dvc/repo/get_url.py
  tests/func/repro/test_repro.py
Labels: A: data-sync

#9755 fs: get_cloud_fs: accept config instead of repo
  dvc/cachemgr.py
  dvc/data_cloud.py
  dvc/fs/__init__.py
  dvc/output.py
  tests/unit/fs/test_fs.py
  tests/unit/fs/test_tree.py
  tests/unit/remote/test_remote.py
  tests/unit/remote/test_webdav.py
Labels: refactoring, skip-changelog

#9762 exp.collect: strip metrics from queued experiments
  dvc/repo/experiments/collect.py
Labels: bugfix

#9765 out: str: don't try to relpath paths outside of the repo
  dvc/output.py
  tests/unit/output/test_local.py
Labels: bugfix

#9775 deps: bump dvc-data to 0.28.0
  pyproject.toml
Labels: dependencies

#9780 dvc: don't use realpath where not needed
  dvc/config.py
  dvc/exceptions.py
  dvc/repo/__init__.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/graph.py
  dvc/repo/init.py
  dvc/repo/stage.py
  dvc/stage/utils.py
  dvc/utils/__init__.py
  tests/func/test_stage.py
  tests/unit/utils/test_utils.py
Labels: P: windows

#9782 deps: bump dvc-data to >=2.8.1
  pyproject.toml
Labels: dependencies
