Repository iterative/dvc, pull requests merged in 2023-03, with the labels that each got.

#9096 exp: use stash-apply instead of merge
  dvc/repo/experiments/executor/local.py
  dvc/repo/experiments/executor/ssh.py
Labels: A: experiments

#9101 tests: unmark exp celery tests as xfail
  tests/func/experiments/test_apply.py
Labels: ci, A: experiments

#9105 deps: Drop dvclive.
  dvc/info.py
  pyproject.toml
Labels: dependencies

#9110 update ruff to v0.0.254
  .pre-commit-config.yaml
  dvc/dvcfile.py
  dvc/parsing/interpolate.py
  dvc/repo/experiments/init.py
  dvc/repo/experiments/show.py
  dvc/repo/experiments/utils.py
  dvc/repo/plots/__init__.py
  pyproject.toml
Labels: skip-changelog

#9114 exp show: don't cache collection errors
  dvc/repo/experiments/serialize.py
  dvc/repo/experiments/show.py
Labels: ui, A: experiments

#9116 deps (tests): require pytest-xdist>=3.2, use `-n=logical` workers and workstealing scheduler
  .github/workflows/tests.yaml
  pyproject.toml
  tests/__main__.py
Labels: skip-changelog

#9128 exp show: fix cached running checkpoint state bug
  dvc/repo/experiments/show.py
Labels: ui, A: experiments, bugfix

#9129 proc: remove dvc.proc
  dvc/proc/__init__.py
  dvc/proc/exceptions.py
  dvc/proc/manager.py
  dvc/proc/process.py
  tests/unit/proc/__init__.py
  tests/unit/proc/test_manager.py
  tests/unit/proc/test_process.py
Labels: maintenance, skip-changelog

#9131 migrate from appdirs to platformdirs
  dvc/config.py
  pyproject.toml
Labels: dependencies

#9027 studio: Send `metrics` on `done` event.
  dvc/repo/experiments/executor/base.py
  pyproject.toml
  tests/integration/test_studio_live_experiments.py
Labels: product, feature

#9123 tests: error on ResourceWarning
  dvc/daemon.py
  dvc/stage/cache.py
  pyproject.toml
Labels: skip-changelog

#9111 push: allow no default remote
  dvc/repo/push.py
Labels: bug, A: data-sync

#9144 plots: avoid printing anything on --json output
  dvc/commands/plots.py
Labels: enhancement

#9112 output: suppress cloud.pull errors on cache collection
  dvc/output.py
  tests/unit/output/test_output.py
Labels: bugfix

#9149 fix(exp): cleanup help messages
  dvc/commands/experiments/clean.py
  dvc/commands/experiments/diff.py
  dvc/commands/experiments/gc.py
  dvc/commands/experiments/save.py
Labels: enhancement, A: experiments

#9155 plots: disable syntax highlighting on plots json output
  dvc/commands/plots.py
  dvc/ui/__init__.py
Labels: enhancement, optimize, A: plots

#9164 exp: push/pull: don't include baseline commit
  dvc/repo/experiments/utils.py
  tests/func/test_gc.py
  tests/unit/scm/test_scm.py
Labels: A: experiments

#9186 ui: disable colorama on write_json when highlighting is disabled
  dvc/ui/__init__.py
Labels: ui, A: experiments, optimize, A: plots

#9187 do not disable colorama in tests
  dvc/ui/__init__.py
Labels: skip-changelog

#9160 exp push: push experiments revs to studio
  dvc/config_schema.py
  dvc/repo/experiments/push.py
  tests/unit/repo/experiments/test_push.py
Labels: enhancement, product, A: experiments, feature, A: cli

#9197 deps: bump `dvc-render>=0.3.1<0.4.0`.
  dvc/commands/plots.py
  dvc/render/convert.py
  pyproject.toml
  tests/unit/command/test_plots.py
  tests/unit/render/test_convert.py
Labels: performance, A: plots

#9202 ui: flush stdout/stderr before colorama re-init
  dvc/ui/__init__.py
Labels: ui, maintenance

#9203 flush streams before fork
  dvc/daemon.py
Labels: skip-changelog

#9206 plots: small refactorings
  dvc/render/converter/vega.py
  dvc/repo/plots/__init__.py
Labels: refactoring, skip-changelog

#9207 dvc.repo.exp: import some modules lazily
  dvc/repo/experiments/__init__.py
Labels: skip-changelog

#9213 sconfig: add support for studio token
  dvc/commands/experiments/push.py
  dvc/config_schema.py
  dvc/repo/experiments/push.py
  tests/unit/repo/experiments/test_push.py
Labels: skip-changelog

#9214 scm: fetch_all_exps pass kwargs to scm.fetch_refspecs
  dvc/repo/experiments/utils.py
Labels: skip-changelog

#9212 hydra: resolve OmegaConf interpolations.
  dvc/utils/hydra.py
  tests/func/utils/test_hydra.py
Labels: bugfix, A: hydra

#9225 exp: enforce waiting for celery task completion in CI
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/queue/celery.py
  tests/func/experiments/test_apply.py
  tests/func/experiments/test_queue.py
  tests/func/experiments/test_show.py
Labels: ci, skip-changelog, A: task-queue

#8727 api: Add `exp_save`.
  dvc/api/__init__.py
  dvc/api/experiments.py
  tests/func/api/test_experiments.py
Labels: feature, A: api

#9236 exp: mark q remove test as flaky
  tests/func/experiments/test_queue.py
Labels: ci, skip-changelog, A: task-queue

#9165 exp save: Reintroduce implementation based on `executor`/`queue`.
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/executor/local.py
  dvc/repo/experiments/save.py
  tests/func/experiments/test_save.py
Labels: refactoring, A: experiments

#9237 deps: bump scmrepo to 0.1.17
  pyproject.toml
Labels: maintenance, dependencies

#9240 exp push: add trailing slash to the endpoint url
  dvc/repo/experiments/push.py
  tests/unit/repo/experiments/test_push.py
Labels: A: experiments, skip-changelog, bugfix

#9146 plots: return errors in json format
  dvc/commands/plots.py
  dvc/render/match.py
  dvc/repo/plots/__init__.py
  tests/func/plots/test_show.py
  tests/integration/plots/test_plots.py
  tests/unit/command/test_plots.py
  tests/unit/render/test_match.py
Labels: A: plots, breaking-change, blocked

#9243 Revert "exp push: add trailing slash to the endpoint url"
  dvc/repo/experiments/push.py
  tests/unit/repo/experiments/test_push.py
Labels: skip-changelog

#9253 exp push/remove: show message on failure when notifying to Studio
  dvc/utils/studio.py
Labels: skip-changelog

#9254 use git remote to find out remote repo url when pinging Studio
  dvc/repo/experiments/push.py
  dvc/repo/experiments/remove.py
  dvc/utils/studio.py
  tests/unit/utils/test_studio.py
Labels: enhancement, A: experiments, skip-changelog

#9255 utils.studio: require token
  dvc/repo/experiments/push.py
  dvc/utils/studio.py
  tests/unit/utils/test_studio.py
Labels: skip-changelog

#9256 refactor notify_refs_to_studio to take in repo instance as dependency
  dvc/repo/experiments/push.py
  dvc/repo/experiments/remove.py
Labels: refactoring, skip-changelog

#9258 remove unused type-ignore comment
  dvc/repo/experiments/push.py
Labels: skip-changelog

#9274 config: don't look for .dvc dir implicitly
  dvc/analytics.py
  dvc/commands/config.py
  dvc/config.py
  dvc/parsing/interpolate.py
  dvc/repo/__init__.py
  dvc/updater.py
  tests/func/test_config.py
  tests/unit/test_config.py
Labels: bug

#9277 utils.studio: refactor to return json response
  dvc/utils/studio.py
  tests/unit/utils/test_studio.py
Labels: refactoring, skip-changelog

#9278 exp-push: show url to the Studio project
  dvc/commands/experiments/push.py
  dvc/repo/experiments/push.py
  tests/func/experiments/test_remote.py
Labels: A: experiments, blocked

#9283 exp-push: show url to the Studio project
  dvc/commands/experiments/push.py
  dvc/repo/experiments/push.py
  tests/func/experiments/test_remote.py
Labels: A: experiments, blocked

#9284 utils.studio: reduce verbosity on exception logging
  dvc/utils/studio.py
Labels: skip-changelog

#9285 deps: bump dvc-studio-client>=0.6.1,<1
  pyproject.toml
Labels: dependencies

#9293 plots json: return definition errors unrelated to renderers
  dvc/commands/plots.py
  tests/unit/command/test_plots.py
Labels: enhancement, A: plots
