Repository iterative/dvc, pull requests merged in 2023-11, with the labels that each got.

#10078 artifacts get: fix issue where global/system config could be ignored
  dvc/repo/artifacts.py
Labels: bugfix, A: artifacts

#10079 drop pylint from linter checks
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip-changelog

#10082 remove flake8/bandit
  .flake8
  .pre-commit-config.yaml
  dvc/commands/completion.py
  dvc/commands/dag.py
  dvc/commands/experiments/show.py
  dvc/daemon.py
  dvc/env.py
  dvc/fs/dvc.py
  dvc/lock.py
  dvc/logger.py
  dvc/output.py
  dvc/parsing/interpolate.py
  dvc/repo/__init__.py
  dvc/repo/artifacts.py
  dvc/repo/brancher.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/apply.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/queue/base.py
  dvc/repo/fetch.py
  dvc/repo/imp_url.py
  dvc/repo/open_repo.py
  dvc/repo/push.py
  dvc/stage/__init__.py
  dvc/stage/loader.py
  dvc/stage/run.py
  dvc/testing/benchmarks/cli/stories/test_modify_data.py
  dvc/testing/benchmarks/fixtures.py
  dvc/testing/fixtures.py
  dvc/ui/pager.py
  pyproject.toml
Labels: skip-changelog

#10085 fix name of the loggers used
  dvc/cli/__init__.py
  dvc/log.py
Labels: skip-changelog

#10090 repo: drop_data_index: delete all first level nodes
  dvc/repo/__init__.py
Labels: bug

#10040 implement import-db command
  dvc/cli/parser.py
  dvc/commands/imp_db.py
  dvc/config_schema.py
  dvc/dependency/__init__.py
  dvc/dependency/db.py
  dvc/dependency/repo.py
  dvc/output.py
  dvc/repo/__init__.py
  dvc/repo/graph.py
  dvc/repo/imp_db.py
  dvc/repo/index.py
  dvc/stage/__init__.py
  dvc/stage/decorators.py
  dvc/stage/imports.py
  dvc/stage/utils.py
  dvc/utils/db.py
  dvc/utils/packaging.py
  pyproject.toml
  tests/unit/stage/test_stage.py
Labels: skip-changelog, A: data-management

#10106 pytest.ini_options: add --benchmark-skip to suppress pytest-benchmark warning with xdist
  pyproject.toml
Labels: testing, skip-changelog

#10107 fix(config): respect global config env variable
  dvc/dirs.py
  tests/unit/test_dirs.py
Labels: bug

#10112 test: import-db: test for external model
  dvc/dependency/db.py
  tests/func/test_import_db_e2e.py
Labels: testing, skip-changelog

#10113 deps: bump dvc-data to >=2.22.1
  pyproject.toml
Labels: performance, dependencies
