Repository iterative/dvc, pull requests merged in 2023-05, with the labels that each got.

#9384 api: exp_show: Cleanup flags.
  dvc/api/experiments.py
Labels: skip-changelog

#9380 exp push: notify studio even if cache push fails
  dvc/repo/experiments/push.py
Labels: enhancement, refactoring

#9394 testing.benchmarks: support installing remote deps in benchmark venv
  dvc/testing/benchmarks/fixtures.py
  dvc/testing/benchmarks/plugin.py
Labels: testing, skip-changelog

#9398 deps: temporarily pin ruamel.yaml
  pyproject.toml
Labels: testing

#9415 import: don't forget to set cache.dir
  dvc/dependency/repo.py
  dvc/repo/open_repo.py
  tests/unit/stage/test_stage.py
Labels: bugfix

#9391 exp: Update `--rev` to support `append` action.
  dvc/commands/experiments/__init__.py
  tests/unit/command/test_experiments.py
Labels: product, A: experiments, feature

#9392 api: exp_show: Postprocess empty strings as None.
  dvc/api/experiments.py
  tests/func/api/test_experiments.py
Labels: enhancement, A: api

#9427 testing.benchmarks: sanitize venv names containing slashes
  dvc/testing/benchmarks/fixtures.py
Labels: testing, skip-changelog

#9395 repro: pull all missing files
  dvc/repo/reproduce.py
  tests/func/test_repro_multistage.py
  tests/func/test_run_cache.py
Labels: enhancement, A: pipelines

#9389 add: support virtual operation
  dvc/commands/add.py
  dvc/output.py
  dvc/repo/add.py
  dvc/stage/__init__.py
  pyproject.toml
  tests/func/test_add.py
  tests/func/test_virtual_directory.py
  tests/unit/repo/test_repo.py
Labels: feature, A: cli, A: data-management

#9446 disable nested progress bar during checkout
  dvc/output.py
Labels: enhancement, ui, A: cli

#9345 Add API to add artifacts
  dvc/annotations.py
  dvc/repo/artifacts.py
  dvc/schema.py
  tests/func/artifacts/test_artifacts.py
Labels: A: artifacts

#9456 exp: fix temporary ref namespacing
  dvc/repo/experiments/executor/local.py
  dvc/repo/experiments/refs.py
Labels: ui, A: experiments

#9434 repro: Move pull logic to inside Stage.
  dvc/repo/reproduce.py
  dvc/stage/__init__.py
  tests/func/test_run_cache.py
Labels: refactoring

#9437 repro: Add `--allow-missing`
  dvc/commands/repro.py
  dvc/stage/__init__.py
  dvc/stage/run.py
  tests/func/test_repro_multistage.py
  tests/unit/command/test_repro.py
Labels: feature, A: pipelines

#9469 testing: Lazy import `pytest_virtualenv`
  dvc/testing/benchmarks/fixtures.py
Labels: bugfix

#9472 exp push: Handle rev arg as list.
  dvc/repo/experiments/push.py
  tests/func/experiments/test_remote.py
Labels: A: experiments, bugfix

#9269 exp: Drop `init`.
  dvc/commands/experiments/__init__.py
  dvc/commands/experiments/init.py
  dvc/repo/experiments/init.py
  dvc/ui/prompt.py
  tests/func/experiments/test_init.py
  tests/unit/command/test_experiments.py
  tests/unit/ui/test_prompt.py
Labels: A: experiments, breaking-change

#9270 exp show: Drop `--pcp`.
  dvc/commands/experiments/show.py
  dvc/compare.py
  tests/func/experiments/test_show.py
  tests/unit/test_tabular_data.py
Labels: A: experiments, breaking-change

#9481 remove `data ls` and support for --meta/--desc/--label/--type cli flags
  dvc/annotations.py
  dvc/cli/actions.py
  dvc/commands/add.py
  dvc/commands/data.py
  dvc/commands/imp.py
  dvc/commands/imp_url.py
  dvc/repo/add.py
  dvc/repo/data.py
  dvc/repo/imp_url.py
  tests/func/test_add.py
  tests/func/test_data_ls.py
  tests/func/test_import.py
  tests/func/test_import_url.py
  tests/unit/command/test_add.py
  tests/unit/command/test_annotations_flags.py
  tests/unit/command/test_data_ls.py
  tests/unit/command/test_imp.py
  tests/unit/command/test_imp_url.py
  tests/unit/output/test_annotations.py
Labels: breaking-change

#9483 exp: Fix --rev args for ls pull and remove.
  dvc/repo/experiments/ls.py
  dvc/repo/experiments/pull.py
  dvc/repo/experiments/remove.py
  tests/func/experiments/test_experiments.py
  tests/func/experiments/test_remote.py
  tests/func/experiments/test_remove.py
Labels: A: experiments, bugfix, backport

#9488 remove `dvc.main.main` alias
  dvc/main.py
Labels: breaking-change

#9489 drop Repo.stages
  dvc/repo/__init__.py
Labels: breaking-change

#9490 get_random_exp_name: Use custom random generator.
  dvc/repo/experiments/utils.py
  pyproject.toml
  tests/func/experiments/test_utils.py
Labels: A: experiments, bugfix, backport

#9486 drop top-level plots definition as mapping support
  dvc/repo/plots/__init__.py
  dvc/schema.py
  tests/func/plots/test_show.py
  tests/func/test_dvcfile.py
  tests/integration/plots/conftest.py
  tests/integration/plots/test_repo_plots_api.py
Labels: A: plots, breaking-change

#9273 exp: Drop `gc`.
  dvc/commands/experiments/__init__.py
  dvc/commands/experiments/gc.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/gc.py
  tests/func/experiments/test_gc.py
  tests/unit/command/test_experiments.py
Labels: A: experiments, breaking-change

#9458 exp run / repro: Drop --metrics.
  dvc/commands/experiments/run.py
  dvc/commands/repro.py
  tests/func/test_repro.py
Labels: breaking-change

#9271 exp: Drop `checkpoints`
  dvc/api/__init__.py
  dvc/api/experiments.py
  dvc/commands/experiments/run.py
  dvc/commands/experiments/show.py
  dvc/commands/run.py
  dvc/commands/stage.py
  dvc/env.py
  dvc/output.py
  dvc/repo/experiments/__init__.py
  dvc/repo/experiments/exceptions.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/executor/local.py
  dvc/repo/experiments/executor/ssh.py
  dvc/repo/experiments/queue/base.py
  dvc/repo/experiments/queue/tempdir.py
  dvc/repo/experiments/queue/utils.py
  dvc/repo/experiments/queue/workspace.py
  dvc/repo/experiments/refs.py
  dvc/repo/experiments/run.py
  dvc/repo/experiments/serialize.py
  dvc/repo/experiments/stash.py
  dvc/repo/experiments/utils.py
  dvc/repo/reproduce.py
  dvc/schema.py
  dvc/stage/__init__.py
  dvc/stage/exceptions.py
  dvc/stage/monitor.py
  dvc/stage/run.py
  dvc/stage/serialize.py
  dvc/stage/utils.py
  tests/func/experiments/conftest.py
  tests/func/experiments/test_checkpoints.py
  tests/func/experiments/test_remote.py
  tests/func/experiments/test_set_params.py
  tests/func/experiments/test_show.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_stage.py
  tests/unit/command/test_experiments.py
  tests/unit/command/test_run.py
  tests/unit/command/test_stage.py
  tests/unit/repo/experiments/conftest.py
  tests/unit/stage/test_stage.py
Labels: A: experiments, breaking-change

#9497 exp: fix rebased imports
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/queue/base.py
Labels: skip-changelog

#9508 cli: remove dvc run
  dvc/cli/parser.py
  dvc/commands/run.py
  tests/func/test_add.py
  tests/func/test_cli.py
  tests/func/test_data_cloud.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_run_single_stage.py
  tests/unit/command/test_run.py
Labels: breaking-change

#9522 add: rename jobs to remote-jobs
  dvc/commands/add.py
  dvc/repo/add.py
  tests/unit/command/test_add.py
Labels: breaking-change

#9524 deps: bumps dvc-azure>=2.21.2
  pyproject.toml
Labels: bugfix, dependencies
