Repository iterative/dvc, pull requests merged in 2023-01, with the labels that each got.

#8754 internal: hoist resolver/top-level metrics/plots/params data to file level
  dvc/dvcfile.py
  dvc/repo/stage.py
  dvc/stage/__init__.py
  dvc/stage/loader.py
  tests/func/test_stage.py
  tests/unit/stage/test_loader_pipeline_file.py
Labels: refactoring

#8769 tests: move tests/unit/remote/test_http.py to dvc-http repo
  tests/unit/remote/test_http.py
Labels: maintenance, skip-changelog

#8780 ls: compute relparts once for every dir
  dvc/repo/ls.py
Labels: performance

#8718 repro: Disable run-cache if --no-commit.
  dvc/stage/__init__.py
  tests/func/test_data_cloud.py
  tests/func/test_repro.py
Labels: enhancement, A: run-cache

#8790 deps: bump dvc-data to 0.28.6
  pyproject.toml
Labels: performance, maintenance

#8785 `import-url`: Update options order
  dvc/commands/imp_url.py
Labels: ui, A: cli

#8791 deps: bump dvc-data to 0.29.0
  pyproject.toml
Labels: performance, dependencies

#8777 perf: remove fs exists check in plots, parallel data collect
  dvc/repo/collect.py
  dvc/repo/experiments/show.py
  dvc/repo/metrics/show.py
  dvc/repo/params/show.py
  dvc/repo/plots/__init__.py
  tests/func/metrics/test_show.py
  tests/func/plots/test_show.py
  tests/unit/test_collect.py
Labels: performance, A: plots

#8794 ruff: ban relative parent/grandparent imports
  dvc/_debug.py
  dvc/commands/get.py
  dvc/commands/get_url.py
  dvc/commands/queue/status.py
  dvc/repo/add.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/executor/local.py
  dvc/repo/experiments/executor/ssh.py
  dvc/repo/experiments/push.py
  dvc/repo/experiments/queue/base.py
  dvc/repo/experiments/queue/celery.py
  dvc/repo/experiments/queue/tasks.py
  dvc/repo/experiments/queue/tempdir.py
  dvc/repo/experiments/queue/utils.py
  dvc/repo/experiments/queue/workspace.py
  dvc/repo/experiments/utils.py
  dvc/repo/imp_url.py
  dvc/repo/move.py
  dvc/repo/push.py
  dvc/repo/reproduce.py
  dvc/repo/update.py
  dvc/stage/__init__.py
  dvc/stage/loader.py
  dvc/stage/serialize.py
  dvc/stage/utils.py
  dvc/utils/__init__.py
  dvc/utils/pkg.py
  pyproject.toml
  tests/func/experiments/test_set_params.py
  tests/ruff.toml
Labels: skip-changelog

#8738 stage: Skip run-cache if any out has cache: false.
  dvc/stage/__init__.py
  tests/func/test_run_cache.py
  tests/unit/stage/test_cache.py
Labels: enhancement, A: run-cache

#8812 dvcfile: rename PipelineFile to ProjectFile, get rid of Dvcfile class, cleanups, etc.
  dvc/commands/git_hook.py
  dvc/dvcfile.py
  dvc/repo/collect.py
  dvc/repo/commit.py
  dvc/repo/experiments/init.py
  dvc/repo/imp_url.py
  dvc/repo/index.py
  dvc/repo/move.py
  dvc/repo/plots/__init__.py
  dvc/repo/reproduce.py
  dvc/repo/stage.py
  dvc/repo/update.py
  dvc/stage/__init__.py
  dvc/stage/utils.py
  dvc/types.py
  dvc/utils/__init__.py
  dvc/utils/serialize/_common.py
  tests/func/experiments/test_experiments.py
  tests/func/metrics/test_show.py
  tests/func/params/test_diff.py
  tests/func/params/test_show.py
  tests/func/plots/test_modify.py
  tests/func/plots/test_show.py
  tests/func/test_add.py
  tests/func/test_checkout.py
  tests/func/test_commit.py
  tests/func/test_dvcfile.py
  tests/func/test_gc.py
  tests/func/test_get.py
  tests/func/test_import.py
  tests/func/test_import_url.py
  tests/func/test_lockfile.py
  tests/func/test_ls.py
  tests/func/test_repo.py
  tests/func/test_repro.py
  tests/func/test_repro_multistage.py
  tests/func/test_run_cache.py
  tests/func/test_run_multistage.py
  tests/func/test_stage_load.py
  tests/func/test_update.py
  tests/unit/stage/test_loader_pipeline_file.py
  tests/unit/stage/test_serialize_pipeline_file.py
  tests/unit/stage/test_serialize_pipeline_lock.py
  tests/unit/test_dvcfile.py
Labels: skip-changelog

#8815 mypy: enable check-untyped-defs
  dvc/_debug.py
  dvc/analytics.py
  dvc/api/data.py
  dvc/api/params.py
  dvc/cli/__init__.py
  dvc/commands/data_sync.py
  dvc/commands/experiments/show.py
  dvc/commands/machine.py
  dvc/commands/plots.py
  dvc/commands/stage.py
  dvc/compare.py
  dvc/config.py
  dvc/daemon.py
  dvc/dependency/__init__.py
  dvc/dependency/param.py
  dvc/dependency/repo.py
  dvc/external_repo.py
  dvc/fs/dvc.py
  dvc/lock.py
  dvc/logger.py
  dvc/output.py
  dvc/parsing/context.py
  dvc/progress.py
  dvc/repo/__init__.py
  dvc/repo/checkout.py
  dvc/repo/index.py
  dvc/repo/plots/__init__.py
  dvc/repo/reproduce.py
  dvc/stage/cache.py
  dvc/stage/loader.py
  dvc/stage/serialize.py
  dvc/testing/fixtures.py
  dvc/testing/path_info.py
  dvc/testing/tmp_dir.py
  dvc/testing/workspace_tests.py
  dvc/utils/collections.py
  dvc/utils/diff.py
  dvc/utils/serialize/_common.py
  dvc/utils/serialize/_json.py
  dvc/utils/serialize/_py.py
  dvc/utils/serialize/_toml.py
  dvc/utils/serialize/_yaml.py
  dvc/utils/threadpool.py
  pyproject.toml
Labels: skip-changelog

#8822 cleanup linters: get rid of pylint-pytest, run pylint only on dvc/ directory, etc
  .pre-commit-config.yaml
  dvc/testing/api_tests.py
  dvc/testing/fixtures.py
  dvc/testing/remote_tests.py
  pyproject.toml
  tests/__init__.py
  tests/conftest.py
  tests/dir_helpers.py
  tests/func/experiments/test_set_params.py
  tests/func/test_add.py
  tests/func/test_checkout.py
  tests/func/test_dvcfile.py
  tests/func/test_repro.py
  tests/pylint_plugin_disable.py
  tests/remotes/git_server.py
  tests/unit/command/test_experiments.py
  tests/unit/command/test_repro.py
  tests/unit/fs/test_azure.py
  tests/unit/output/test_load.py
  tests/unit/remote/test_webhdfs.py
  tests/unit/repo/experiments/queue/test_celery.py
  tests/unit/repo/test_scm_context.py
  tests/unit/stage/test_stage.py
  tests/unit/test_logger.py
  tests/unit/ui/test_prompt.py
  tests/unit/utils/test_collections.py
Labels: skip-changelog

#8833 exp run: Fix `--dry` option.
  dvc/repo/experiments/executor/base.py
  tests/func/experiments/test_experiments.py
Labels: A: experiments, bugfix

#8823 param: Fix status check for Tuples.
  dvc/dependency/param.py
  tests/unit/dependency/test_params.py
Labels: bugfix, A: params

#8842 deps: bump dvc-data to 0.34.0
  pyproject.toml
Labels: performance, maintenance

#8847 deps: bump dvc-data to 0.35.0
  pyproject.toml
Labels: dependencies

#8857 deps: bump dvc-data to 0.35.1
  dvc/api/data.py
  pyproject.toml
  tests/func/test_ignore.py
  tests/func/test_state.py
Labels: maintenance

#8864 deps: bump dvc-azure to 2.21.0
  pyproject.toml
Labels: dependencies

#8849 output: Don't serialize `hash_info` or `meta` in cloud versioning.
  dvc/output.py
  dvc/stage/serialize.py
  tests/func/test_add.py
  tests/unit/output/test_output.py
  tests/unit/stage/test_serialize_pipeline_lock.py
Labels: enhancement, A: cloud-versioning

#8878 data status: check if change.old.hash_info is None or not
  dvc/repo/data.py
  tests/func/test_data_status.py
Labels: skip-changelog

#8876 import/import-url: try not to delete dvcfile before import/import-url completes
  dvc/repo/imp_url.py
Labels: enhancement

#8879 dumpd: serialize files at the end in .dvc files
  dvc/output.py
Labels: skip-changelog

#8882 output: Pass `version_aware=True` to `fs` if `files` is present.
  dvc/output.py
  tests/unit/output/test_output.py
Labels: bugfix, A: cloud-versioning

#8889 serialize: fix loading of cloud metadata from .dvc/dvc.lock files
  dvc/output.py
  dvc/schema.py
  dvc/stage/loader.py
Labels: skip-changelog, bugfix, A: cloud-versioning

#8902 mypy: unignore module override
  pyproject.toml
Labels: skip-changelog

#8913 ci: run dvc-s3 tests on DVC pull requests
  .github/workflows/plugin_tests.yaml
Labels: testing, ci

#8915 bump ruff to 0.0.238
  .pre-commit-config.yaml
  dvc/dependency/repo.py
  dvc/fs/dvc.py
  dvc/logger.py
  dvc/repo/experiments/__init__.py
  dvc/repo/metrics/show.py
  dvc/repo/params/show.py
  pyproject.toml
  tests/unit/proc/test_process.py
Labels: skip-changelog

#8919 deps: bump dvc-gs to 2.21.1
  pyproject.toml
Labels: fs: gs, A: cloud-versioning

#8918 logging: log pkg version/type, platform info and cli arguments
  dvc/cli/__init__.py
Labels: enhancement

#8921 version/info: match dashes' length below DVC version
  dvc/info.py
Labels: ui
