Repository iterative/dvc, pull requests merged in 2024-02, with the labels that each got.

#10273 repo: site_cache_dir: separate subdir from root_dir
  dvc/repo/__init__.py
Labels: bug

#10275 repo: index: don't set cache storage if there is no out.cache
  dvc/repo/index.py
Labels: bug

#10278 chore: update to ruff 0.2
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip-changelog

#10281 cli: sort commands
  dvc/cli/parser.py
Labels: skip-changelog

#10294 tests: remove pytest-lazy-fixture
  pyproject.toml
  tests/func/test_data_cloud.py
  tests/func/test_get.py
  tests/func/test_ls.py
Labels: skip-changelog

#10298 deps: bump dvc-studio-client to >=0.19,<1
  dvc/commands/studio.py
  pyproject.toml
  tests/unit/command/test_studio.py
Labels: dependencies

#10304 deps: bump dvc-data >=3.13.0
  pyproject.toml
Labels: dependencies

#10311 repo.imports: remove unused code
  dvc/repo/imports.py
Labels: maintenance, skip-changelog

#10303 studio: add subdir to live metrics post messages to support live experiments in monorepos
  dvc/repo/__init__.py
  dvc/repo/experiments/executor/base.py
  dvc/utils/studio.py
  pyproject.toml
  tests/integration/test_studio_live_experiments.py
  tests/unit/repo/test_repo.py
Labels: product: Studio

#10322 cli: fix typo in help message, replace / with : in scp style url
  dvc/commands/dataset.py
Labels: skip-changelog

#10318 plots: support x-dict in nested dvc.yaml
  dvc/repo/plots/__init__.py
  tests/func/plots/test_show.py
  tests/integration/plots/test_plots.py
Labels: bug, A: plots

#10325 dataset: provide --rev to track a different dvcx dataset version or git rev
  dvc/commands/dataset.py
  dvc/repo/datasets.py
  tests/unit/command/test_dataset.py
Labels: skip-changelog

#10302 experimental upath implementation for dvcfilesystem
  dvc/fs/dvc_path.py
  pyproject.toml
Labels: skip-changelog

#10328 fix PathInfo instantiation in Python 3.12
  dvc/testing/path_info.py
  dvc/testing/tmp_dir.py
Labels: skip-changelog
