Repository iterative/dvc, pull requests merged in 2024-03, with the labels that each got.

#10351 fix dvcx import
  dvc/repo/datasets.py
Labels: skip-changelog

#10354 add attrs explicit dependency
  pyproject.toml
Labels: bug, dependencies

#10357 DVC_STAGE: Added environment variable to track DVC stage name
  dvc/env.py
  dvc/stage/run.py
Labels: enhancement, awaiting response, p2-medium

#10371 sort imports for all libraries starting with dvc_ as a first party
  dvc/commands/studio.py
  dvc/fs/__init__.py
  dvc/repo/artifacts.py
  dvc/repo/experiments/executor/base.py
  dvc/repo/experiments/queue/base.py
  pyproject.toml
  tests/integration/test_studio_live_experiments.py
  tests/remotes/git_server.py
  tests/unit/command/test_studio.py
  tests/unit/fs/test_fs.py
  tests/unit/output/test_load.py
  tests/unit/remote/test_remote.py
  tests/unit/remote/test_webdav.py
  tests/unit/remote/test_webhdfs.py
Labels: skip-changelog

#10375 params/metrics: do not fail during dir expansion
  dvc/repo/metrics/show.py
  dvc/repo/params/show.py
  dvc/utils/__init__.py
  tests/func/metrics/test_show.py
  tests/func/params/test_show.py
Labels: bugfix, A: params, A: metrics
