Repository iterative/dvc, pull requests merged in 2025-06, with the labels that each got.

#10749 feat: ignore files not in remote when push is false
  dvc/repo/data.py
  tests/func/test_data_status.py
Labels: A: status, A: data-management

#10790 fix(data status): show committed changes in a new Git repository
  dvc/repo/data.py
  tests/func/test_data_status.py
Labels: bugfix

#10792 perf(data status): batch remote checks
  dvc/repo/data.py
Labels: performance, A: status
